// docs/src/components/ui/Input/Input.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/input/input.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/input/input.js';
import './Input.css';
import type { WaClearEvent } from '@awesome.me/webawesome-pro/dist/events/clear.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Write a boolean as the keyword an enumerated attribute expects ("on"/"off",
 * "true"/"false"), or remove the attribute when the prop is unset so the
 * element keeps its own default. Web Awesome reads these by value, not
 * presence, and React would write a DOM property or a bare attribute.
 */
function setEnumeratedAttribute(
  el: Pick<Element, 'setAttribute' | 'removeAttribute'>,
  name: string,
  value: boolean | undefined,
  keywords: { true: string; false: string }
): void {
  if (value === undefined) el.removeAttribute(name);
  else el.setAttribute(name, value ? keywords.true : keywords.false);
}

/**
 * Inputs collect data from the user
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Input />
 *
 * // With event handlers
 * <Input
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<InputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <Input ref={ref} />
 * ```
 */
export interface InputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onBlur'
  | 'onFocus'
  | 'onClear'
  | 'onInvalid'
  | 'dir'
> {
  /** Input type */
  type?:
    | 'text'
    | 'email'
    | 'password'
    | 'number'
    | 'date'
    | 'tel'
    | 'url'
    | 'search';

  /** Accessible label for the input */
  label?: string;

  /** Descriptive hint text */
  hint?: string;

  /** Placeholder text */
  placeholder?: string;

  /** Input value */
  value?: string;

  /** Visual appearance style */
  appearance?: 'filled' | 'filled-outlined' | 'outlined';

  /** Input size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Gives the input rounded edges */
  pill?: boolean;

  /** Disables the input */
  disabled?: boolean;

  /** Adds a clear button when input has content */
  'with-clear'?: boolean;

  /** Adds a toggle button for password visibility */
  'password-toggle'?: boolean;

  /** Shows the password as plain text when set */
  'password-visible'?: boolean;

  /** Makes the input readonly */
  readonly?: boolean;

  /** Makes the input required */
  required?: boolean;

  /** The name of the input for form submission */
  name?: string;

  /** A regular expression pattern the value must match */
  pattern?: string;

  /** Minimum string length */
  minlength?: number;

  /** Maximum string length */
  maxlength?: number;

  /** Minimum value for numeric and date types */
  min?: number | string;

  /** Maximum value for numeric and date types */
  max?: number | string;

  /** Step increment for numeric types */
  step?: number | string;

  /** Hides the browser's built-in spin buttons for number inputs */
  'without-spin-buttons'?: boolean;

  /** Hint for autocomplete behavior */
  autocomplete?: string;

  /** Controls automatic capitalization */
  autocapitalize?: 'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';

  /** Turns autocorrect on or off; the browser decides when unset */
  autocorrect?: boolean;

  /** Automatically focuses the input on page load */
  autofocus?: boolean;

  /** Hint for virtual keyboard type */
  inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';

  /** Hint for Enter key label on virtual keyboards */
  enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';

  /** Turns spell checking on or off; on when unset */
  spellcheck?: boolean;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the control receives input (native input event). */
  onInput?: (event: Event) => void;

  /** Emitted when an alteration to the control's value is committed by the user (native change event). */
  onChange?: (event: Event) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the clear button is activated. */
  onClear?: (event: WaClearEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface InputRef {
  /** Sets focus on the input. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the input. */
  blur: () => void;

  /** Selects all the text in the input. */
  select: () => void;

  /** Sets the start and end positions of the text selection (0-based). */
  setSelectionRange: (
    selectionStart: number,
    selectionEnd: number,
    selectionDirection: 'forward' | 'backward' | 'none'
  ) => void;

  /** Replaces a range of text with a new string. */
  setRangeText: (
    replacement: string,
    start: number,
    end: number,
    selectMode: 'select' | 'start' | 'end' | 'preserve'
  ) => void;

  /** Displays the browser picker for an input element (only works if the browser supports it for the input type). */
  showPicker: () => void;

  /** Increments the value of a numeric input type by the value of the step attribute. */
  stepUp: () => void;

  /** Decrements the value of a numeric input type by the value of the step attribute. */
  stepDown: () => void;
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Input = forwardRef<InputRef, InputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onBlur,
      onFocus,
      onClear,
      onInvalid,
      autocorrect,
      spellcheck,
      ...props
    },
    ref
  ) => {
    const inputRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            inputRef.current &&
            typeof inputRef.current.focus === 'function'
          ) {
            inputRef.current.focus(options);
          }
        },
        blur: () => {
          if (inputRef.current && typeof inputRef.current.blur === 'function') {
            inputRef.current.blur();
          }
        },
        select: () => {
          if (
            inputRef.current &&
            typeof inputRef.current.select === 'function'
          ) {
            inputRef.current.select();
          }
        },
        setSelectionRange: (
          selectionStart: number,
          selectionEnd: number,
          selectionDirection: 'forward' | 'backward' | 'none'
        ) => {
          if (
            inputRef.current &&
            typeof inputRef.current.setSelectionRange === 'function'
          ) {
            inputRef.current.setSelectionRange(
              selectionStart,
              selectionEnd,
              selectionDirection
            );
          }
        },
        setRangeText: (
          replacement: string,
          start: number,
          end: number,
          selectMode: 'select' | 'start' | 'end' | 'preserve'
        ) => {
          if (
            inputRef.current &&
            typeof inputRef.current.setRangeText === 'function'
          ) {
            inputRef.current.setRangeText(replacement, start, end, selectMode);
          }
        },
        showPicker: () => {
          if (
            inputRef.current &&
            typeof inputRef.current.showPicker === 'function'
          ) {
            inputRef.current.showPicker();
          }
        },
        stepUp: () => {
          if (
            inputRef.current &&
            typeof inputRef.current.stepUp === 'function'
          ) {
            inputRef.current.stepUp();
          }
        },
        stepDown: () => {
          if (
            inputRef.current &&
            typeof inputRef.current.stepDown === 'function'
          ) {
            inputRef.current.stepDown();
          }
        },
        get element() {
          return inputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = inputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleClear = (e: Event) => {
        if (onClear) onClear(e as WaClearEvent);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-clear', handleClear);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-clear', handleClear);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onInput, onChange, onBlur, onFocus, onClear, onInvalid]);

    useEffect(() => {
      const el = inputRef.current;
      if (!el) return;
      setEnumeratedAttribute(el, 'autocorrect', autocorrect, {
        true: 'on',
        false: 'off',
      });
      setEnumeratedAttribute(el, 'spellcheck', spellcheck, {
        true: 'true',
        false: 'false',
      });
    }, [autocorrect, spellcheck]);

    return (
      <wa-input
        ref={(el: WaElement | null) => {
          inputRef.current = el;
        }}
        class={clsx('Input', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-input>
    );
  }
);

Input.displayName = 'Input';

// templates/angular/Input/input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/input/input.js';
import type { WaClearEvent } from '@awesome.me/webawesome/dist/events/clear.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/input/input.js'));
}

/**
 * Inputs collect data from the user
 *
 * @see https://webawesome.com/docs/components/input
 */
@Component({
  selector: 'k-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-input
      #element
      [attr.type]="type"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.placeholder]="placeholder"
      [attr.value]="value"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.pill]="pill || null"
      [attr.disabled]="disabled || null"
      [attr.with-clear]="withClear || null"
      [attr.password-toggle]="passwordToggle || null"
      [attr.password-visible]="passwordVisible || null"
      [attr.readonly]="readonly || null"
      [attr.required]="required || null"
      [attr.name]="name"
      [attr.pattern]="pattern"
      [attr.minlength]="minlength"
      [attr.maxlength]="maxlength"
      [attr.min]="min"
      [attr.max]="max"
      [attr.step]="step"
      [attr.without-spin-buttons]="withoutSpinButtons || null"
      [attr.autocomplete]="autocomplete"
      [attr.autocapitalize]="autocapitalize"
      [attr.autocorrect]="
        autocorrect == null ? null : autocorrect ? 'on' : 'off'
      "
      [attr.autofocus]="autofocus || null"
      [attr.inputmode]="inputmode"
      [attr.enterkeyhint]="enterkeyhint"
      [attr.title]="title"
      [attr.spellcheck]="
        spellcheck == null ? null : spellcheck ? 'true' : 'false'
      "
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-input>
  `,
  styleUrl: './input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true,
    },
  ],
})
export class InputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Input type */
  @Input() type?:
    | 'text'
    | 'email'
    | 'password'
    | 'number'
    | 'date'
    | 'tel'
    | 'url'
    | 'search';
  /** Accessible label for the input */
  @Input() label?: string;
  /** Descriptive hint text */
  @Input() hint?: string;
  /** Placeholder text */
  @Input() placeholder?: string;
  /** Input value */
  @Input() value?: string;
  /** Visual appearance style */
  @Input() appearance?: 'filled' | 'filled-outlined' | 'outlined';
  /** Input size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Gives the input rounded edges */
  @Input() pill?: boolean;
  /** Disables the input */
  @Input() disabled?: boolean;
  /** Adds a clear button when input has content */
  @Input() withClear?: boolean;
  /** Adds a toggle button for password visibility */
  @Input() passwordToggle?: boolean;
  /** Shows the password as plain text when set */
  @Input() passwordVisible?: boolean;
  /** Makes the input readonly */
  @Input() readonly?: boolean;
  /** Makes the input required */
  @Input() required?: boolean;
  /** The name of the input for form submission */
  @Input() name?: string;
  /** A regular expression pattern the value must match */
  @Input() pattern?: string;
  /** Minimum string length */
  @Input() minlength?: number;
  /** Maximum string length */
  @Input() maxlength?: number;
  /** Minimum value for numeric and date types */
  @Input() min?: string;
  /** Maximum value for numeric and date types */
  @Input() max?: string;
  /** Step increment for numeric types */
  @Input() step?: string;
  /** Hides the browser's built-in spin buttons */
  @Input() withoutSpinButtons?: boolean;
  /** Hint for autocomplete behavior */
  @Input() autocomplete?: string;
  /** Controls automatic capitalization */
  @Input() autocapitalize?:
    'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';
  /** Turns autocorrect on or off; the browser decides when unset */
  @Input() autocorrect?: boolean;
  /** Automatically focuses the input on page load */
  @Input() autofocus?: boolean;
  /** Hint for virtual keyboard type */
  @Input() inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';
  /** Hint for Enter key label on virtual keyboards */
  @Input() enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Turns spell checking on or off; on when unset */
  @Input() spellcheck?: boolean;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() clear = new EventEmitter<WaClearEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleClear = (e: Event) => this.clear.emit(e as WaClearEvent);
    el.addEventListener('wa-clear', handleClear);
    this.cleanups.push(() => el.removeEventListener('wa-clear', handleClear));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  select(): void {
    (
      this.elementRef.nativeElement as unknown as { select: () => void }
    ).select();
  }
  setSelectionRange(
    selectionStart?: number,
    selectionEnd?: number,
    selectionDirection?: 'forward' | 'backward' | 'none'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        setSelectionRange: (
          selectionStart?: number,
          selectionEnd?: number,
          selectionDirection?: 'forward' | 'backward' | 'none'
        ) => void;
      }
    ).setSelectionRange(selectionStart, selectionEnd, selectionDirection);
  }
  setRangeText(
    replacement?: string,
    start?: number,
    end?: number,
    selectMode?: 'select' | 'start' | 'end' | 'preserve'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        setRangeText: (
          replacement?: string,
          start?: number,
          end?: number,
          selectMode?: 'select' | 'start' | 'end' | 'preserve'
        ) => void;
      }
    ).setRangeText(replacement, start, end, selectMode);
  }
  showPicker(): void {
    (
      this.elementRef.nativeElement as unknown as { showPicker: () => void }
    ).showPicker();
  }
  stepUp(): void {
    (
      this.elementRef.nativeElement as unknown as { stepUp: () => void }
    ).stepUp();
  }
  stepDown(): void {
    (
      this.elementRef.nativeElement as unknown as { stepDown: () => void }
    ).stepDown();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
