// templates/angular/RandomContent/random-content.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/random-content/random-content.js';
import type { WaContentChangeEvent } from '@awesome.me/webawesome/dist/events/random-content-change.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/random-content/random-content.js'));
}

/**
 * Randomly selects and displays one or more of its child elements
 *
 * @see https://webawesome.com/docs/components/random-content
 */
@Component({
  selector: 'k-random-content',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-random-content
      #element
      [attr.items]="items"
      [attr.mode]="mode"
      [attr.autoplay]="autoplay || null"
      [attr.autoplay-interval]="autoplayInterval"
      [attr.animation]="animation"
    >
      <ng-content />
    </wa-random-content>
  `,
  styleUrl: './random-content.component.css',
})
export class RandomContentComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The number of items to display at once */
  @Input() items?: number;
  /** How items are picked on each randomization */
  @Input() mode?: 'random' | 'unique' | 'sequence';
  /** Automatically randomizes the displayed items on an interval */
  @Input() autoplay?: boolean;
  /** The number of milliseconds between randomizations when autoplay is enabled */
  @Input() autoplayInterval?: number;
  /** The animation to apply when displayed items change */
  @Input() animation?:
    'none' | 'fade' | 'fade-up' | 'fade-down' | 'fade-left' | 'fade-right';

  @Output() contentChange = new EventEmitter<WaContentChangeEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleContentChange = (e: Event) =>
      this.contentChange.emit(e as WaContentChangeEvent);
    el.addEventListener('wa-content-change', handleContentChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-content-change', handleContentChange)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  randomize(): void {
    (
      this.elementRef.nativeElement as unknown as { randomize: () => void }
    ).randomize();
  }
}

// templates/react/RandomContent/RandomContent.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaRandomContent from '@awesome.me/webawesome/dist/components/random-content/random-content.js';
import type { WaContentChangeEvent } from '@awesome.me/webawesome/dist/events/random-content-change.js';
import './RandomContent.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/random-content/random-content.js'));
}

/**
 * Randomly selects and displays one or more of its child elements
 *
 * @example
 * ```tsx
 * // Basic usage
 * <RandomContent />
 *
 * // With event handlers
 * <RandomContent
 *   onContentChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<RandomContentRef>(null);
 * <button onClick={() => ref.current?.randomize()}>Call Method</button>
 * <RandomContent ref={ref} />
 * ```
 */
export interface RandomContentProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onContentChange' | 'dir'
> {
  /** The number of items to display at once */
  items?: number;

  /** How items are picked on each randomization */
  mode?: 'random' | 'unique' | 'sequence';

  /** Automatically randomizes the displayed items on an interval */
  autoplay?: boolean;

  /** The number of milliseconds between randomizations when autoplay is enabled */
  'autoplay-interval'?: number;

  /** The animation to apply when displayed items change */
  animation?:
    'none' | 'fade' | 'fade-up' | 'fade-down' | 'fade-left' | 'fade-right';

  /** Emitted whenever the displayed selection changes, including on first render, on `randomize()`, and on each autoplay tick. */
  onContentChange?: (event: WaContentChangeEvent) => void;
}

export interface RandomContentRef {
  /** Selects a new set of children using the current mode. Returns the elements now shown. */
  randomize: () => void;
  /** Reference to the underlying HTML element */
  element: WaRandomContent | null;
}

export const RandomContent = forwardRef<RandomContentRef, RandomContentProps>(
  ({ children, className, onContentChange, ...props }, ref) => {
    const randomcontentRef = useRef<WaRandomContent | null>(null);
    const setRandomContentRef = useCallback((el: WaRandomContent | null) => {
      randomcontentRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        randomize: () => {
          if (
            randomcontentRef.current &&
            typeof randomcontentRef.current.randomize === 'function'
          ) {
            randomcontentRef.current.randomize();
          }
        },
        get element() {
          return randomcontentRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = randomcontentRef.current;
      if (!el) return;

      const handleWaContentChange = (e: Event) => {
        if (onContentChange) onContentChange(e as WaContentChangeEvent);
      };

      el.addEventListener('wa-content-change', handleWaContentChange);

      return () => {
        el.removeEventListener('wa-content-change', handleWaContentChange);
      };
    }, [onContentChange]);

    return (
      <wa-random-content
        ref={setRandomContentRef}
        class={clsx('RandomContent', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-random-content>
    );
  }
);

RandomContent.displayName = 'RandomContent';
