// docs/src/components/ui/Tooltip/Tooltip.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/tooltip/tooltip.js';
import './Tooltip.css';

/**
 * Tooltips display additional information based on a specific action
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Tooltip />
 *
 * // With event handlers
 * <Tooltip
 *   onShow={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TooltipRef>(null);
 * <button onClick={() => ref.current?.show()}>Call Method</button>
 * <Tooltip ref={ref} />
 * ```
 */
export interface TooltipProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'dir'
> {
  /** The id of the element the tooltip will target */
  for?: string;

  /** Tooltip content */
  content?: string;

  /** Tooltip placement */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';

  /** Disables the tooltip */
  disabled?: boolean;

  /** Distance from target */
  distance?: number;

  /** Whether the tooltip is open */
  open?: boolean;

  /** Offset along target */
  skidding?: number;

  /** Activation events */
  trigger?: string;

  /** Hides the arrow */
  'without-arrow'?: boolean;

  /** Show delay (ms) */
  'show-delay'?: number;

  /** Hide delay (ms) */
  'hide-delay'?: number;

  /** Emitted when the tooltip begins to show. */
  onShow?: (event: CustomEvent) => void;

  /** Emitted after the tooltip has shown and all animations are complete. */
  onAfterShow?: (event: CustomEvent) => void;

  /** Emitted when the tooltip begins to hide. */
  onHide?: (event: CustomEvent) => void;

  /** Emitted after the tooltip has hidden and all animations are complete. */
  onAfterHide?: (event: CustomEvent) => void;
}

export interface TooltipRef {
  /** Shows the tooltip. */
  show: () => void;

  /** Hides the tooltip */
  hide: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Tooltip = forwardRef<TooltipRef, TooltipProps>(
  (
    { children, className, onShow, onAfterShow, onHide, onAfterHide, ...props },
    ref
  ) => {
    const tooltipRef = useRef<
      HTMLElement & {
        show?: () => void;
        hide?: () => void;
      }
    >(null);

    useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (
            tooltipRef.current &&
            typeof tooltipRef.current.show === 'function'
          ) {
            tooltipRef.current.show();
          }
        },
        hide: () => {
          if (
            tooltipRef.current &&
            typeof tooltipRef.current.hide === 'function'
          ) {
            tooltipRef.current.hide();
          }
        },
        get element() {
          return tooltipRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = tooltipRef.current;
      if (!el) return;

      const handleShow = (e: Event) => {
        if (onShow) onShow(e as CustomEvent);
      };

      const handleAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as CustomEvent);
      };

      const handleHide = (e: Event) => {
        if (onHide) onHide(e as CustomEvent);
      };

      const handleAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as CustomEvent);
      };

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return (
      <wa-tooltip
        ref={tooltipRef}
        class={clsx('Tooltip', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tooltip>
    );
  }
);

Tooltip.displayName = 'Tooltip';

// templates/angular/Tooltip/tooltip.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/tooltip/tooltip.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/tooltip/tooltip.js'));
}

/**
 * Tooltips display additional information based on a specific action
 *
 * @see https://webawesome.com/docs/components/tooltip
 */
@Component({
  selector: 'k-tooltip',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-tooltip
      #element
      [attr.placement]="placement"
      [attr.disabled]="disabled || null"
      [attr.distance]="distance"
      [attr.open]="open || null"
      [attr.skidding]="skidding"
      [attr.trigger]="trigger"
      [attr.without-arrow]="withoutArrow || null"
      [attr.show-delay]="showDelay"
      [attr.hide-delay]="hideDelay"
      [attr.for]="for"
    >
      <ng-content />
    </wa-tooltip>
  `,
  styleUrl: './tooltip.component.css',
})
export class TooltipComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Tooltip placement */
  @Input() placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** Disables the tooltip */
  @Input() disabled?: boolean;
  /** Distance from target */
  @Input() distance?: number;
  /** Whether the tooltip is open */
  @Input() open?: boolean;
  /** Offset along target */
  @Input() skidding?: number;
  /** Activation events */
  @Input() trigger?: string;
  /** Hides the arrow */
  @Input() withoutArrow?: boolean;
  /** Show delay (ms) */
  @Input() showDelay?: number;
  /** Hide delay (ms) */
  @Input() hideDelay?: number;
  /** The ID of the element the tooltip is anchored to */
  @Input() for?: string;

  @Output() showEvent = new EventEmitter<CustomEvent>();
  @Output() afterShow = new EventEmitter<CustomEvent>();
  @Output() hideEvent = new EventEmitter<CustomEvent>();
  @Output() afterHide = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShowEvent = (e: Event) => this.showEvent.emit(e as CustomEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-show', handleShowEvent)
    );
    const handleAfterShow = (e: Event) => this.afterShow.emit(e as CustomEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as CustomEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-hide', handleHideEvent)
    );
    const handleAfterHide = (e: Event) => this.afterHide.emit(e as CustomEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
}
