// templates/angular/Details/details.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input, Output, EventEmitter, OnDestroy } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/details/details.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/details/details.js'));
}

/**
 * Shows a brief summary and expands to show additional content
 *
 * @see https://webawesome.com/docs/components/details
 */
@Component({
  selector: 'k-details',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-details
        #element
        [attr.open]="open || null"
        [attr.summary]="summary"
        [attr.disabled]="disabled || null"
        [attr.appearance]="appearance"
        [attr.icon-placement]="iconPlacement"
        [attr.name]="name">
      <ng-content />
    </wa-details>
  `,
  styleUrl: './details.component.css',
})
export class DetailsComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Whether the details are expanded */
  @Input() open?: boolean;
  /** Summary text shown in header */
  @Input() summary?: string;
  /** Disables the details */
  @Input() disabled?: boolean;
  /** Visual appearance style */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined' | 'plain';
  /** Position of the expand icon */
  @Input() iconPlacement?: 'start' | 'end';
  /** Name for accordion grouping */
  @Input() name?: string;

  @Output() showEvent = new EventEmitter<CustomEvent>();
  @Output() afterShow = new EventEmitter<CustomEvent>();
  @Output() hideEvent = new EventEmitter<CustomEvent>();
  @Output() afterHide = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShowEvent = (e: Event) => this.showEvent.emit(e as CustomEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() => el.removeEventListener('wa-show', handleShowEvent));
    const handleAfterShow = (e: Event) => this.afterShow.emit(e as CustomEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() => el.removeEventListener('wa-after-show', handleAfterShow));
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as CustomEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() => el.removeEventListener('wa-hide', handleHideEvent));
    const handleAfterHide = (e: Event) => this.afterHide.emit(e as CustomEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() => el.removeEventListener('wa-after-hide', handleAfterHide));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
}

// docs/.kigumi/snapshots/Details/Details.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/details/details.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/details/details.js';
import './Details.css';

/**
 * Shows a brief summary and expands to show additional content
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Details />
 *
 * // With event handlers
 * <Details
 *   onShow={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<DetailsRef>(null);
 * <button onClick={() => ref.current?.show()}>Call Method</button>
 * <Details ref={ref} />
 * ```
 */
export interface DetailsProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'dir'
> {
  /** Whether the details are expanded */
  open?: boolean;

  /** Summary text shown in header */
  summary?: string;

  /** Disables the details */
  disabled?: boolean;

  /** Visual appearance style */
  appearance?: 'filled' | 'outlined' | 'filled-outlined' | 'plain';

  /** Position of the expand icon */
  'icon-placement'?: 'start' | 'end';

  /** Name for accordion grouping */
  name?: string;

  /** Emitted when the details opens. */
  onShow?: (event: CustomEvent) => void;

  /** Emitted after the details opens and all animations are complete. */
  onAfterShow?: (event: CustomEvent) => void;

  /** Emitted when the details closes. */
  onHide?: (event: CustomEvent) => void;

  /** Emitted after the details closes and all animations are complete. */
  onAfterHide?: (event: CustomEvent) => void;
}

export interface DetailsRef {
  /** Shows the details. */
  show: () => void;

  /** Hides the details */
  hide: () => void;
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Details = forwardRef<DetailsRef, DetailsProps>(
  (
    { children, className, onShow, onAfterShow, onHide, onAfterHide, ...props },
    ref
  ) => {
    const detailsRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (
            detailsRef.current &&
            typeof detailsRef.current.show === 'function'
          ) {
            detailsRef.current.show();
          }
        },
        hide: () => {
          if (
            detailsRef.current &&
            typeof detailsRef.current.hide === 'function'
          ) {
            detailsRef.current.hide();
          }
        },
        get element() {
          return detailsRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = detailsRef.current;
      if (!el) return;

      const handleShow = (e: Event) => {
        if (onShow) onShow(e as CustomEvent);
      };

      const handleAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as CustomEvent);
      };

      const handleHide = (e: Event) => {
        if (onHide) onHide(e as CustomEvent);
      };

      const handleAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as CustomEvent);
      };

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return (
      <wa-details
        ref={(el: WaElement | null) => {
          detailsRef.current = el;
        }}
        class={clsx('Details', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-details>
    );
  }
);

Details.displayName = 'Details';
