// templates/react/FormatBytes/FormatBytes.jsx
import React from 'react';
import clsx from 'clsx';
import './FormatBytes.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js'));
}

/**
 * @typedef {Object} FormatBytesProps
 * @property {number} value - The number to format in bytes
 * @property {'byte' | 'bit'} [unit] - The type of unit to display
 * @property {'long' | 'short' | 'narrow'} [display] - Determines how to display the result
 */

export const FormatBytes = React.forwardRef(({ className, ...props }, ref) => {
  React.useEffect(() => {
    ensureLoaded();
  }, []);

  return (
    <wa-format-bytes
      ref={ref}
      class={clsx('FormatBytes', className)}
      {...props}
    />
  );
});

FormatBytes.displayName = 'FormatBytes';

// templates/vue/FormatBytes/FormatBytes.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatBytes.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js'));
}

/**
 * Formats a number as a human-readable byte value
 */
export interface FormatBytesProps {
  value?: number;
  unit?: 'byte' | 'bit';
  display?: 'long' | 'short' | 'narrow';
  lang?: string;
}

const props = defineProps<FormatBytesProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-bytes
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-bytes>
</template>
