// templates/react/FormatBytes/FormatBytes.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './FormatBytes.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js'));
}

/**
 * Formats a number as a human-readable byte value
 *
 * @example
 * ```tsx
 * // Basic usage
 * <FormatBytes />
 *
 * // With event handlers
 * <FormatBytes />
 *
 * ```
 */
export interface FormatBytesProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The number to format in bytes */
  value?: number;

  /** The unit to format the value in */
  unit?: 'byte' | 'bit';

  /** Determines how to display the result */
  display?: 'long' | 'short' | 'narrow';

  /** The locale to use when formatting */
  lang?: string;
}

export interface FormatBytesRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const FormatBytes = forwardRef<FormatBytesRef, FormatBytesProps>(
  ({ children, className, ...props }, ref) => {
    const formatbytesRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return formatbytesRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-format-bytes
        ref={formatbytesRef}
        class={clsx('FormatBytes', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-format-bytes>
    );
  }
);

FormatBytes.displayName = 'FormatBytes';

// templates/vue/FormatBytes/FormatBytes.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatBytes.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js'));
}

/**
 * Formats a number as a human-readable byte value
 */
export interface FormatBytesProps {
  value?: number;
  unit?: 'byte' | 'bit';
  display?: 'long' | 'short' | 'narrow';
  lang?: string;
}

const props = defineProps<FormatBytesProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-bytes
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-bytes>
</template>
