// templates/angular/BreadcrumbItem/breadcrumb-item.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/breadcrumb-item/breadcrumb-item.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/breadcrumb-item/breadcrumb-item.js'));
}

/**
 * Breadcrumb Items are used inside breadcrumbs to represent different links
 *
 * @see https://webawesome.com/docs/components/breadcrumb-item
 */
@Component({
  selector: 'k-breadcrumb-item',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-breadcrumb-item
        #element
        [attr.href]="href"
        [attr.target]="target"
        [attr.rel]="rel">
      <ng-content />
    </wa-breadcrumb-item>
  `,
  styleUrl: './breadcrumb-item.component.css',
})
export class BreadcrumbItemComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Optional URL to direct the user to when activated */
  @Input() href?: string;
  /** Tells the browser where to open the link */
  @Input() target?: '_blank' | '_parent' | '_self' | '_top';
  /** The rel attribute to use on the link */
  @Input() rel?: string;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// docs/src/components/ui/BreadcrumbItem/BreadcrumbItem.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/breadcrumb-item/breadcrumb-item.js';
import './BreadcrumbItem.css';

/**
 * Breadcrumb Items are used inside breadcrumbs to represent different links
 *
 * @example
 * ```tsx
 * import { Breadcrumb, BreadcrumbItem } from './components/ui';
 *
 * // As buttons (default)
 * <Breadcrumb>
 *   <BreadcrumbItem>Home</BreadcrumbItem>
 *   <BreadcrumbItem>Products</BreadcrumbItem>
 * </Breadcrumb>
 *
 * // As links
 * <Breadcrumb>
 *   <BreadcrumbItem href="/">Home</BreadcrumbItem>
 *   <BreadcrumbItem href="/products">Products</BreadcrumbItem>
 *   <BreadcrumbItem>Current</BreadcrumbItem>
 * </Breadcrumb>
 *
 * // With icons
 * <Breadcrumb>
 *   <BreadcrumbItem>
 *     <wa-icon slot="start" name="house" />
 *     Home
 *   </BreadcrumbItem>
 *   <BreadcrumbItem>
 *     Products
 *     <wa-icon slot="end" name="box" />
 *   </BreadcrumbItem>
 * </Breadcrumb>
 * ```
 */
export interface BreadcrumbItemProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** Optional URL to direct the user to when activated */
  href?: string;
  /** Tells the browser where to open the link */
  target?: '_blank' | '_parent' | '_self' | '_top';
  /** The rel attribute to use on the link */
  rel?: string;
}

export const BreadcrumbItem = forwardRef<HTMLElement, BreadcrumbItemProps>(
  ({ children, className, ...props }, ref) => {
    return (
      <wa-breadcrumb-item
        ref={ref}
        class={clsx('BreadcrumbItem', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-breadcrumb-item>
    );
  }
);

BreadcrumbItem.displayName = 'BreadcrumbItem';
