// templates/angular/TimeInput/time-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/time-input/time-input.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaClearEvent } from '@awesome.me/webawesome/dist/events/clear.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/time-input/time-input.js'));
}

/**
 * Time inputs collect a time of day from the user
 *
 * @see https://webawesome.com/docs/components/time-input
 */
@Component({
  selector: 'k-time-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-time-input
      #element
      [attr.name]="name"
      [attr.value]="value"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.readonly]="readonly || null"
      [attr.size]="size"
      [attr.appearance]="appearance"
      [attr.pill]="pill || null"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.with-clear]="withClear || null"
      [attr.with-now]="withNow || null"
      [attr.min]="min"
      [attr.max]="max"
      [attr.step]="step"
      [attr.hour-format]="hourFormat"
      [attr.open]="open || null"
      [attr.placement]="placement"
      [attr.distance]="distance"
      [attr.autocomplete]="autocomplete"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-time-input>
  `,
  styleUrl: './time-input.component.css',
})
export class TimeInputComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** The current value as a 24-hour `HH:mm:ss` string */
  @Input() value?: string;
  /** Whether the control is disabled */
  @Input() disabled?: boolean;
  /** Whether a value is required before form submission */
  @Input() required?: boolean;
  /** Whether the control is read-only */
  @Input() readonly?: boolean;
  /** Controls the overall dimensions of the control */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** The visual style of the control */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** Draws the control with rounded edges */
  @Input() pill?: boolean;
  /** The control label. Use the `label` slot for rich labels. */
  @Input() label?: string;
  /** Help text shown below the control. Use the `hint` slot for rich hints. */
  @Input() hint?: string;
  /** Shows a clear button when the control has a value */
  @Input() withClear?: boolean;
  /** Shows a button that sets the value to the current time */
  @Input() withNow?: boolean;
  /** The earliest acceptable time */
  @Input() min?: string;
  /** The latest acceptable time */
  @Input() max?: string;
  /** The granularity of the value in seconds */
  @Input() step?: number;
  /** Whether to display a 12- or 24-hour clock. `auto` follows the locale. */
  @Input() hourFormat?: 'auto' | '12' | '24';
  /** Whether the time picker dropdown is open */
  @Input() open?: boolean;
  /** The preferred placement of the dropdown */
  @Input() placement?:
    'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end';
  /** Gap in pixels between the input and the dropdown */
  @Input() distance?: number;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() clear = new EventEmitter<WaClearEvent>();
  @Output() showEvent = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hideEvent = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleClear = (e: Event) => this.clear.emit(e as WaClearEvent);
    el.addEventListener('wa-clear', handleClear);
    this.cleanups.push(() => el.removeEventListener('wa-clear', handleClear));
    const handleShowEvent = (e: Event) => this.showEvent.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-show', handleShowEvent)
    );
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-hide', handleHideEvent)
    );
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
  formStateRestoreCallback(state: string | File | FormData | null): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null
        ) => void;
      }
    ).formStateRestoreCallback(state);
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// templates/react/TimeInput/TimeInput.jsx
import React from 'react';
import clsx from 'clsx';
import './TimeInput.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/time-input/time-input.js'));
}

/**
 * Time inputs collect a time of day from the user
 *
 * @example
 * ```jsx
 * // Basic usage
 * <TimeInput />
 *
 * // With event handlers
 * <TimeInput onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = React.useRef(null);
 * <button onClick={() => ref.current?.focus()}>Focus</button>
 * <TimeInput ref={ref} />
 * ```
 *
 * @param {Object} props
 * @param {string} [props.name] - The name of the control, submitted with form data
 * @param {string} [props.value] - The current value as a 24-hour `HH:mm:ss` string
 * @param {boolean} [props.disabled] - Whether the control is disabled
 * @param {boolean} [props.required] - Whether a value is required before form submission
 * @param {boolean} [props.readonly] - Whether the control is read-only
 * @param {'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl'} [props.size] - Controls the overall dimensions of the control
 * @param {'filled' | 'outlined' | 'filled-outlined'} [props.appearance] - The visual style of the control
 * @param {boolean} [props.pill] - Draws the control with rounded edges
 * @param {string} [props.label] - The control label. Use the `label` slot for rich labels.
 * @param {string} [props.hint] - Help text shown below the control. Use the `hint` slot for rich hints.
 * @param {boolean} [props['with-clear']] - Shows a clear button when the control has a value
 * @param {boolean} [props['with-now']] - Shows a button that sets the value to the current time
 * @param {string} [props.min] - The earliest acceptable time
 * @param {string} [props.max] - The latest acceptable time
 * @param {number} [props.step] - The granularity of the value in seconds
 * @param {'auto' | '12' | '24'} [props['hour-format']] - Whether to display a 12- or 24-hour clock
 * @param {boolean} [props.open] - Whether the time picker dropdown is open
 * @param {'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end'} [props.placement] - The preferred placement of the dropdown
 * @param {number} [props.distance] - Gap in pixels between the input and the dropdown
 * @param {string} [props.autocomplete] - Hint for browser autofill
 * @param {string} [props['custom-error']] - Custom validation message; the control is invalid while it is set
 * @param {function} [props.onInput] - Emitted as the user types into a segment or interacts with the popup columns.
 * @param {function} [props.onChange] - Emitted when the committed value changes.
 * @param {function} [props.onFocus] - Emitted when the control receives focus.
 * @param {function} [props.onBlur] - Emitted when the control loses focus.
 * @param {function} [props.onClear] - Emitted when the clear button is activated.
 * @param {function} [props.onShow] - Emitted when the popup is about to open. Cancelable.
 * @param {function} [props.onAfterShow] - Emitted after the popup opens and animations complete.
 * @param {function} [props.onHide] - Emitted when the popup is about to close. Cancelable.
 * @param {function} [props.onAfterHide] - Emitted after the popup closes and animations complete.
 * @param {function} [props.onInvalid] - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 * @param {string} [props.className] - Additional CSS classes
 * @param {React.ReactNode} [props.children] - Slotted content
 * @param {React.Ref} ref - Ref with methods: focus(options), blur(), show(), hide(), formStateRestoreCallback(state), setCustomValidity(message), resetValidity()
 */
export const TimeInput = React.forwardRef(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onFocus,
      onBlur,
      onClear,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const timeinputRef = React.useRef(null);
    const setTimeInputRef = React.useCallback((el) => {
      timeinputRef.current = el;
    }, []);

    React.useImperativeHandle(
      ref,
      () => ({
        focus: (options) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.focus === 'function'
          ) {
            timeinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.blur === 'function'
          ) {
            timeinputRef.current.blur();
          }
        },
        show: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.show === 'function'
          ) {
            timeinputRef.current.show();
          }
        },
        hide: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.hide === 'function'
          ) {
            timeinputRef.current.hide();
          }
        },
        formStateRestoreCallback: (state) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.formStateRestoreCallback === 'function'
          ) {
            timeinputRef.current.formStateRestoreCallback(state);
          }
        },
        setCustomValidity: (message) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.setCustomValidity === 'function'
          ) {
            timeinputRef.current.setCustomValidity(message);
          }
        },
        resetValidity: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.resetValidity === 'function'
          ) {
            timeinputRef.current.resetValidity();
          }
        },
        get element() {
          return timeinputRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = timeinputRef.current;
      if (!el) return;

      const handleInput = (e) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e) => {
        if (onChange) onChange(e);
      };

      const handleFocus = (e) => {
        if (onFocus) onFocus(e);
      };

      const handleBlur = (e) => {
        if (onBlur) onBlur(e);
      };

      const handleWaClear = (e) => {
        if (onClear) onClear(e);
      };

      const handleWaShow = (e) => {
        if (onShow) onShow(e);
      };

      const handleWaAfterShow = (e) => {
        if (onAfterShow) onAfterShow(e);
      };

      const handleWaHide = (e) => {
        if (onHide) onHide(e);
      };

      const handleWaAfterHide = (e) => {
        if (onAfterHide) onAfterHide(e);
      };

      const handleWaInvalid = (e) => {
        if (onInvalid) onInvalid(e);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('wa-clear', handleWaClear);
      el.addEventListener('wa-show', handleWaShow);
      el.addEventListener('wa-after-show', handleWaAfterShow);
      el.addEventListener('wa-hide', handleWaHide);
      el.addEventListener('wa-after-hide', handleWaAfterHide);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('wa-clear', handleWaClear);
        el.removeEventListener('wa-show', handleWaShow);
        el.removeEventListener('wa-after-show', handleWaAfterShow);
        el.removeEventListener('wa-hide', handleWaHide);
        el.removeEventListener('wa-after-hide', handleWaAfterHide);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [
      onInput,
      onChange,
      onFocus,
      onBlur,
      onClear,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onInvalid,
    ]);

    return (
      <wa-time-input
        ref={setTimeInputRef}
        class={clsx('TimeInput', className)}
        {...{ suppressHydrationWarning: true, ...props }}
      >
        {children}
      </wa-time-input>
    );
  }
);

TimeInput.displayName = 'TimeInput';
