// templates/react/VideoPlaylist/VideoPlaylist.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaVideoPlaylist from '@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js';
import './VideoPlaylist.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js'));
}

/**
 * Groups multiple videos into a playlist with next/previous navigation
 *
 * @example
 * ```tsx
 * // Basic usage
 * <VideoPlaylist />
 *
 * // With event handlers
 * <VideoPlaylist
 *   onVideoChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<VideoPlaylistRef>(null);
 * <button onClick={() => ref.current?.next()}>Call Method</button>
 * <VideoPlaylist ref={ref} />
 * ```
 */
export interface VideoPlaylistProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onVideoChange' | 'dir'
> {
  /** The set of controls forwarded to each child video */
  controls?: 'none' | 'standard' | 'full';

  /** The icon library used for placeholder icons */
  'icon-library'?: string;

  onVideoChange?: (event: CustomEvent) => void;
}

export interface VideoPlaylistRef {
  next: () => void;

  previous: () => void;

  goTo: (index: number) => void;
  /** Reference to the underlying HTML element */
  element: WaVideoPlaylist | null;
}

export const VideoPlaylist = forwardRef<VideoPlaylistRef, VideoPlaylistProps>(
  ({ children, className, onVideoChange, ...props }, ref) => {
    const videoplaylistRef = useRef<WaVideoPlaylist | null>(null);
    const setVideoPlaylistRef = useCallback((el: WaVideoPlaylist | null) => {
      videoplaylistRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        next: () => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.next === 'function'
          ) {
            videoplaylistRef.current.next();
          }
        },
        previous: () => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.previous === 'function'
          ) {
            videoplaylistRef.current.previous();
          }
        },
        goTo: (index: number) => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.goTo === 'function'
          ) {
            videoplaylistRef.current.goTo(index);
          }
        },
        get element() {
          return videoplaylistRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = videoplaylistRef.current;
      if (!el) return;

      const handleWaVideoChange = (e: Event) => {
        if (onVideoChange) onVideoChange(e as CustomEvent);
      };

      el.addEventListener('wa-video-change', handleWaVideoChange);

      return () => {
        el.removeEventListener('wa-video-change', handleWaVideoChange);
      };
    }, [onVideoChange]);

    return (
      <wa-video-playlist
        ref={setVideoPlaylistRef}
        class={clsx('VideoPlaylist', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-video-playlist>
    );
  }
);

VideoPlaylist.displayName = 'VideoPlaylist';

// templates/vue/VideoPlaylist/VideoPlaylist.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './VideoPlaylist.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js'));
}

/**
 * Groups multiple videos into a playlist with next/previous navigation
 */
export interface VideoPlaylistProps {
  controls?: 'none' | 'standard' | 'full';
  'icon-library'?: string;
}

const props = defineProps<VideoPlaylistProps>();

// Strip undefined and false props before forwarding to the web component.
// Vue boolean-prop coercion materializes absent optional Boolean props as
// `false`, but Web Awesome elements read attribute presence as truthy, so
// we must not forward `false` to <wa-*> (would render pill="" / loading="").
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (value !== undefined && value !== false) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-video-change': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaVideoChange = (e: Event) =>
  emit('wa-video-change', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-video-change', handleWaVideoChange);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-video-change', handleWaVideoChange);
});

defineExpose({
  next: () => (elementRef.value as any)?.next?.(),
  previous: () => (elementRef.value as any)?.previous?.(),
  goTo: (index: number) => (elementRef.value as any)?.goTo?.(index),
  element: elementRef,
});
</script>

<template>
  <wa-video-playlist
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-video-playlist>
</template>
