// templates/react/FileInput/FileInput.jsx
import React from 'react';
import clsx from 'clsx';
import './FileInput.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/file-input/file-input.js'));
}

/**
 * File inputs allow users to select and upload files from their device
 *
 * @example
 * ```jsx
 * // Basic usage
 * <FileInput label="Upload document" accept=".pdf,.doc" />
 * <FileInput multiple />
 * <FileInput hint="Select up to 5 files" required />
 *
 * // With event handlers
 * <FileInput
 *   label="Upload files"
 *   onChange={(e) => console.log('Files changed')}
 * />
 *
 * // With ref methods
 * const fileInputRef = React.useRef(null);
 * <button onClick={() => fileInputRef.current?.focus()}>Focus</button>
 * <FileInput ref={fileInputRef} label="Upload" />
 * ```
 *
 * @typedef {Object} FileInputProps
 * @property {string} [label] - Accessible label
 * @property {string} [hint] - Descriptive hint text
 * @property {string} [accept] - Accepted file types (MIME types or extensions)
 * @property {string} [capture] - Mobile capture device: user (front) | environment (rear)
 * @property {boolean} [multiple] - Allow multiple file selection
 * @property {string} [size] - Input size: small | medium | large
 * @property {boolean} [disabled] - Disables the input
 * @property {boolean} [required] - Makes field mandatory
 * @property {string} [name] - The name of the control, submitted with form data
 * @property {string} [custom-error] - Custom validation message; the control is invalid while it is set
 * @property {function} [onBlur] - Event fired when input loses focus
 * @property {function} [onFocus] - Event fired when input gains focus
 * @property {function} [onInput] - Event fired when file selection changes
 * @property {function} [onChange] - Event fired when files are added or removed
 */

export const FileInput = React.forwardRef(
  (
    { children, className, onBlur, onFocus, onInput, onChange, ...props },
    ref
  ) => {
    const fileInputRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        focus: () => {
          if (
            fileInputRef.current &&
            typeof fileInputRef.current.focus === 'function'
          ) {
            fileInputRef.current.focus();
          }
        },
        blur: () => {
          if (
            fileInputRef.current &&
            typeof fileInputRef.current.blur === 'function'
          ) {
            fileInputRef.current.blur();
          }
        },
        get element() {
          return fileInputRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = fileInputRef.current;
      if (!el) return;

      const handleBlur = (e) => {
        if (onBlur) onBlur(e);
      };

      const handleFocus = (e) => {
        if (onFocus) onFocus(e);
      };

      const handleInput = (e) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e) => {
        if (onChange) onChange(e);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
      };
    }, [onBlur, onFocus, onInput, onChange]);

    return (
      <wa-file-input
        ref={fileInputRef}
        class={clsx('FileInput', className)}
        {...props}
      >
        {children}
      </wa-file-input>
    );
  }
);

FileInput.displayName = 'FileInput';

// templates/angular/FileInput/file-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/file-input/file-input.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/file-input/file-input.js'));
}

/**
 * File inputs allow users to select and upload files from their device
 *
 * @see https://webawesome.com/docs/components/file-input
 */
@Component({
  selector: 'k-file-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-file-input
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.accept]="accept"
      [attr.capture]="capture"
      [attr.multiple]="multiple || null"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.size]="size"
      [attr.name]="name"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-file-input>
  `,
  styleUrl: './file-input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FileInputComponent),
      multi: true,
    },
  ],
})
export class FileInputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible label for the input */
  @Input() label?: string;
  /** Descriptive hint text */
  @Input() hint?: string;
  /** Accepted file types (MIME types or extensions) */
  @Input() accept?: string;
  /** Camera or mic to open directly on phones and tablets: user (front) or environment (rear) */
  @Input() capture?: 'user' | 'environment';
  /** Allow multiple file selection */
  @Input() multiple?: boolean;
  /** Disables the input */
  @Input() disabled?: boolean;
  /** Makes field mandatory */
  @Input() required?: boolean;
  /** Input size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<CustomEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as CustomEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
