// docs/src/components/ui/FileInput/FileInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/file-input/file-input.js';
import './FileInput.css';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * File inputs allow users to select and upload files from their device
 *
 * @example
 * ```tsx
 * // Basic usage
 * <FileInput />
 *
 * // With event handlers
 * <FileInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<FileInputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <FileInput ref={ref} />
 * ```
 */
export interface FileInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onInput' | 'onChange' | 'onFocus' | 'onBlur' | 'onInvalid' | 'dir'
> {
  /** Accessible label for the input */
  label?: string;

  /** Descriptive hint text */
  hint?: string;

  /** Accepted file types (MIME types or extensions) */
  accept?: string;

  /** Camera or mic to open directly on phones and tablets: user (front) or environment (rear) */
  capture?: 'user' | 'environment';

  /** Allow multiple file selection */
  multiple?: boolean;

  /** Disables the input */
  disabled?: boolean;

  /** Makes field mandatory */
  required?: boolean;

  /** Input size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** The name of the control, submitted with form data */
  name?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when file selection changes. */
  onInput?: (event: Event) => void;

  /** Emitted when files are added or removed. */
  onChange?: (event: Event) => void;

  /** Emitted when the dropzone gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the dropzone loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface FileInputRef {
  /** Sets focus on the file input. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the file input. */
  blur: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const FileInput = forwardRef<FileInputRef, FileInputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onFocus,
      onBlur,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const fileinputRef = useRef<
      HTMLElement & {
        focus?: (options: FocusOptions) => void;
        blur?: () => void;
      }
    >(null);

    const setFileinputRef = useCallback((el: typeof fileinputRef.current) => {
      fileinputRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            fileinputRef.current &&
            typeof fileinputRef.current.focus === 'function'
          ) {
            fileinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            fileinputRef.current &&
            typeof fileinputRef.current.blur === 'function'
          ) {
            fileinputRef.current.blur();
          }
        },
        get element() {
          return fileinputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = fileinputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onInput, onChange, onFocus, onBlur, onInvalid]);

    return (
      <wa-file-input
        ref={setFileinputRef}
        class={clsx('FileInput', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-file-input>
    );
  }
);

FileInput.displayName = 'FileInput';

// templates/angular/FileInput/file-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/file-input/file-input.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/file-input/file-input.js'));
}

/**
 * File inputs allow users to select and upload files from their device
 *
 * @see https://webawesome.com/docs/components/file-input
 */
@Component({
  selector: 'k-file-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-file-input
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.accept]="accept"
      [attr.capture]="capture"
      [attr.multiple]="multiple || null"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.size]="size"
      [attr.name]="name"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-file-input>
  `,
  styleUrl: './file-input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => FileInputComponent),
      multi: true,
    },
  ],
})
export class FileInputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible label for the input */
  @Input() label?: string;
  /** Descriptive hint text */
  @Input() hint?: string;
  /** Accepted file types (MIME types or extensions) */
  @Input() accept?: string;
  /** Camera or mic to open directly on phones and tablets: user (front) or environment (rear) */
  @Input() capture?: 'user' | 'environment';
  /** Allow multiple file selection */
  @Input() multiple?: boolean;
  /** Disables the input */
  @Input() disabled?: boolean;
  /** Makes field mandatory */
  @Input() required?: boolean;
  /** Input size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<Event>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) => this.inputEvent.emit(e);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
