// docs/src/components/ui/Popover/Popover.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/popover/popover.js';
import './Popover.css';
import type { WaAfterHideEvent } from '@awesome.me/webawesome-pro/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome-pro/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome-pro/dist/events/hide.js';
import type { WaShowEvent } from '@awesome.me/webawesome-pro/dist/events/show.js';

/**
 * Popovers display additional content when users interact with a trigger element
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Popover />
 *
 * // With event handlers
 * <Popover
 *   onShow={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<PopoverRef>(null);
 * <button onClick={() => ref.current?.show()}>Call Method</button>
 * <Popover ref={ref} />
 * ```
 */
export interface PopoverProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'dir'
> {
  /** ID of the target element the popover is attached to */
  for?: string;

  /** Indicates whether the popover is open */
  open?: boolean;

  /** Disables the popover */
  disabled?: boolean;

  /** Preferred placement */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';

  /** Activation events (click, hover, focus) */
  trigger?: string;

  /** Distance from trigger */
  distance?: number;

  /** Offset along trigger */
  skidding?: number;

  /** Shows an arrow */
  'with-arrow'?: boolean;

  /** Hides the arrow (alias: sets with-arrow to false) */
  'without-arrow'?: boolean;

  /** Emitted when the popover begins to show. Canceling this event will stop the popover from showing. */
  onShow?: (event: WaShowEvent) => void;

  /** Emitted after the popover has shown and all animations are complete. */
  onAfterShow?: (event: WaAfterShowEvent) => void;

  /** Emitted when the popover begins to hide. Canceling this event will stop the popover from hiding. */
  onHide?: (event: WaHideEvent) => void;

  /** Emitted after the popover has hidden and all animations are complete. */
  onAfterHide?: (event: WaAfterHideEvent) => void;
}

export interface PopoverRef {
  /** Shows the popover. */
  show: () => void;

  /** Hides the popover. */
  hide: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Popover = forwardRef<PopoverRef, PopoverProps>(
  (
    {
      children,
      className,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      'without-arrow': withoutArrow,
      ...props
    },
    ref
  ) => {
    const passThrough = {
      ...props,
      ...(withoutArrow !== undefined && { 'with-arrow': !withoutArrow }),
    };
    const popoverRef = useRef<
      HTMLElement & {
        show?: () => void;
        hide?: () => void;
      }
    >(null);

    const setPopoverRef = useCallback((el: typeof popoverRef.current) => {
      popoverRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (
            popoverRef.current &&
            typeof popoverRef.current.show === 'function'
          ) {
            popoverRef.current.show();
          }
        },
        hide: () => {
          if (
            popoverRef.current &&
            typeof popoverRef.current.hide === 'function'
          ) {
            popoverRef.current.hide();
          }
        },
        get element() {
          return popoverRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = popoverRef.current;
      if (!el) return;

      const handleShow = (e: Event) => {
        if (onShow) onShow(e as WaShowEvent);
      };

      const handleAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as WaAfterShowEvent);
      };

      const handleHide = (e: Event) => {
        if (onHide) onHide(e as WaHideEvent);
      };

      const handleAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as WaAfterHideEvent);
      };

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return (
      <wa-popover
        ref={setPopoverRef}
        class={clsx('Popover', className)}
        {...(passThrough as Record<string, unknown>)}
      >
        {children}
      </wa-popover>
    );
  }
);

Popover.displayName = 'Popover';

// templates/angular/Popover/popover.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/popover/popover.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/popover/popover.js'));
}

/**
 * Popovers display additional content when users interact with a trigger element
 *
 * @see https://webawesome.com/docs/components/popover
 */
@Component({
  selector: 'k-popover',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-popover
      #element
      [attr.open]="open || null"
      [attr.disabled]="disabled || null"
      [attr.placement]="placement"
      [attr.trigger]="trigger"
      [attr.distance]="distance"
      [attr.skidding]="skidding"
      [attr.with-arrow]="withArrow || null"
      [attr.without-arrow]="withoutArrow || null"
      [attr.for]="for"
    >
      <ng-content />
    </wa-popover>
  `,
  styleUrl: './popover.component.css',
})
export class PopoverComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Indicates whether the popover is open */
  @Input() open?: boolean;
  /** Disables the popover */
  @Input() disabled?: boolean;
  /** Preferred placement */
  @Input() placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** Activation events (click, hover, focus) */
  @Input() trigger?: string;
  /** Distance from trigger */
  @Input() distance?: number;
  /** Offset along trigger */
  @Input() skidding?: number;
  /** Shows an arrow */
  @Input() withArrow?: boolean;
  /** Hides the arrow */
  @Input() withoutArrow?: boolean;
  /** The ID of the element the popover is anchored to */
  @Input() for?: string;

  @Output() showEvent = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hideEvent = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShowEvent = (e: Event) => this.showEvent.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-show', handleShowEvent)
    );
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-hide', handleHideEvent)
    );
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
}
