// templates/vue/FormatDate/FormatDate.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatDate.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-date/format-date.js'));
}

/**
 * Formats a date/time using the Intl.DateTimeFormat API
 */
export interface FormatDateProps {
  date?: string;
  weekday?: 'narrow' | 'short' | 'long';
  era?: 'narrow' | 'short' | 'long';
  year?: 'numeric' | '2-digit';
  month?: 'numeric' | '2-digit' | 'narrow' | 'short' | 'long';
  day?: 'numeric' | '2-digit';
  hour?: 'numeric' | '2-digit';
  minute?: 'numeric' | '2-digit';
  second?: 'numeric' | '2-digit';
  'hour-format'?: 'auto' | '12' | '24';
  'time-zone-name'?: 'short' | 'long';
  'time-zone'?: string;
  lang?: string;
}

const props = defineProps<FormatDateProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-date
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-date>
</template>

// docs/src/components/ui/FormatDate/FormatDate.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/format-date/format-date.js';
import './FormatDate.css';

export interface FormatDateProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** The date/time to format */
  date?: Date | string;
  /** Format for displaying the weekday */
  weekday?: 'narrow' | 'short' | 'long';
  /** Format for displaying the era */
  era?: 'narrow' | 'short' | 'long';
  /** Format for displaying the year */
  year?: 'numeric' | '2-digit';
  /** Format for displaying the month */
  month?: 'numeric' | '2-digit' | 'narrow' | 'short' | 'long';
  /** Format for displaying the day */
  day?: 'numeric' | '2-digit';
  /** Format for displaying the hour */
  hour?: 'numeric' | '2-digit';
  /** Format for displaying the minute */
  minute?: 'numeric' | '2-digit';
  /** Format for displaying the second */
  second?: 'numeric' | '2-digit';
  /** Format for 12 or 24-hour time */
  'hour-format'?: 'auto' | '12' | '24';
  /** Time zone to express the time in */
  'time-zone'?: string;
  /** Format for displaying the time zone */
  'time-zone-name'?: 'short' | 'long';
}

export const FormatDate = forwardRef<HTMLElement, FormatDateProps>(
  ({ className, ...props }, ref) => {
    return (
      <wa-format-date
        ref={ref}
        class={clsx('FormatDate', className)}
        {...(props as Record<string, unknown>)}
      />
    );
  }
);

FormatDate.displayName = 'FormatDate';
