// templates/vue/Rating/Rating.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import './Rating.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/rating/rating.js'));
}

/**
 * Ratings give users a way to quickly view and provide feedback
 */
export interface RatingProps {
  label?: string;
  max?: number;
  precision?: number;
  readonly?: boolean;
  disabled?: boolean;
  name?: string;
  required?: boolean;
  size?: 'small' | 'medium' | 'large';
}

const props = defineProps<RatingProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'change': [event: CustomEvent];
  'wa-hover': [event: CustomEvent];
  'wa-invalid': [event: CustomEvent];
}>();

const model = defineModel<number>();

const elementRef = ref<HTMLElement | null>(null);

watch(model, (val) => {
  const el = elementRef.value as any;
  if (el && el.value !== val) el.value = val ?? '';
});

onMounted(() => {
  ensureLoaded();
});

const handleChange = (e: Event) => { model.value = (e.target as any).value; emit('change', e as CustomEvent); };
const handleWaHover = (e: Event) => emit('wa-hover', e as CustomEvent);
const handleWaInvalid = (e: Event) => emit('wa-invalid', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('change', handleChange);
  el.addEventListener('wa-hover', handleWaHover);
  el.addEventListener('wa-invalid', handleWaInvalid);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('change', handleChange);
  el.removeEventListener('wa-hover', handleWaHover);
  el.removeEventListener('wa-invalid', handleWaInvalid);
});

defineExpose({
  setCustomValidity: (message: string) => (elementRef.value as any)?.setCustomValidity?.(message),
  formStateRestoreCallback: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => (elementRef.value as any)?.formStateRestoreCallback?.(state, reason),
  resetValidity: () => (elementRef.value as any)?.resetValidity?.(),
  element: elementRef,
});
</script>

<template>
  <wa-rating
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
    :value="model"
  >
    <slot />
  </wa-rating>
</template>

// docs/.kigumi/snapshots/Rating/Rating.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/rating/rating.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/rating/rating.js';
import './Rating.css';

/**
 * Ratings give users a way to quickly view and provide feedback
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Rating />
 *
 * // With event handlers
 * <Rating
 *   onChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<RatingRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <Rating ref={ref} />
 * ```
 */
export interface RatingProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onChange' | 'onHover' | 'dir'
> {
  /** Accessible label */
  label?: string;

  /** Current rating value */
  value?: number;

  /** Maximum rating value */
  max?: number;

  /** Rating precision (e.g., 0.5) */
  precision?: number;

  /** Rating size */
  size?: 'small' | 'medium' | 'large';

  /** Makes the rating readonly */
  readonly?: boolean;

  /** Disables the rating */
  disabled?: boolean;

  /** Emitted when the rating's value changes. */
  onChange?: (event: CustomEvent) => void;

  /** Emitted when the user hovers over a value. The `phase` property indicates when hovering starts, moves to a new value, or ends. The `value` property tells what the rating's value would be if the user were to commit to the hovered value. */
  onHover?: (event: CustomEvent) => void;
}

export interface RatingRef {
  /** Sets focus on the rating. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the rating. */
  blur: () => void;
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Rating = forwardRef<RatingRef, RatingProps>(
  ({ children, className, onChange, onHover, ...props }, ref) => {
    const ratingRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            ratingRef.current &&
            typeof ratingRef.current.focus === 'function'
          ) {
            ratingRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            ratingRef.current &&
            typeof ratingRef.current.blur === 'function'
          ) {
            ratingRef.current.blur();
          }
        },
        get element() {
          return ratingRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = ratingRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as CustomEvent);
      };

      const handleHover = (e: Event) => {
        if (onHover) onHover(e as CustomEvent);
      };

      el.addEventListener('change', handleChange);
      el.addEventListener('wa-hover', handleHover);

      return () => {
        el.removeEventListener('change', handleChange);
        el.removeEventListener('wa-hover', handleHover);
      };
    }, [onChange, onHover]);

    return (
      <wa-rating
        ref={(el: WaElement | null) => {
          ratingRef.current = el;
        }}
        class={clsx('Rating', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-rating>
    );
  }
);

Rating.displayName = 'Rating';
