// templates/angular/Pagination/pagination.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/pagination/pagination.js';
import type { WaBeforePageChangeEvent } from '@awesome.me/webawesome/dist/events/before-page-change.js';
import type { WaPageChangeEvent } from '@awesome.me/webawesome/dist/events/page-change.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/pagination/pagination.js'));
}

/**
 * Pagination splits long lists of content into pages, letting users navigate between them
 *
 * @see https://webawesome.com/docs/components/pagination
 */
@Component({
  selector: 'k-pagination',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-pagination
      #element
      [attr.total]="total"
      [attr.page-size]="pageSize"
      [attr.page]="page"
      [attr.sibling-count]="siblingCount"
      [attr.boundary-count]="boundaryCount"
      [attr.without-nav]="withoutNav || null"
      [attr.with-edges]="withEdges || null"
      [attr.with-summary]="withSummary || null"
      [attr.format]="format"
      [attr.href-template]="hrefTemplate"
      [attr.hide-single-page]="hideSinglePage || null"
      [attr.label]="label"
      [attr.appearance]="appearance"
      [attr.disabled]="disabled || null"
    >
      <ng-content />
    </wa-pagination>
  `,
  styleUrl: './pagination.component.css',
})
export class PaginationComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The total number of items to paginate */
  @Input() total?: number;
  /** The number of items shown per page */
  @Input() pageSize?: number;
  /** The current page, starting at 1 */
  @Input() page?: number;
  /** The number of pages to show on each side of the current page */
  @Input() siblingCount?: number;
  /** The number of pages to always show at the start and end */
  @Input() boundaryCount?: number;
  /** Hides the previous and next buttons */
  @Input() withoutNav?: boolean;
  /** Shows buttons that jump to the first and last pages */
  @Input() withEdges?: boolean;
  /** Shows a summary of the items on the current page */
  @Input() withSummary?: boolean;
  /** The pagination layout */
  @Input() format?: 'standard' | 'compact';
  /** URL template with {page} placeholder to render page items as links */
  @Input() hrefTemplate?: string;
  /** Renders nothing when there is only one page */
  @Input() hideSinglePage?: boolean;
  /** Accessible name announced by screen readers */
  @Input() label?: string;
  /** Visual appearance */
  @Input() appearance?: 'outlined' | 'filled' | 'plain';
  /** Disables the pagination */
  @Input() disabled?: boolean;

  @Output() beforePageChange = new EventEmitter<WaBeforePageChangeEvent>();
  @Output() pageChange = new EventEmitter<WaPageChangeEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBeforePageChange = (e: Event) =>
      this.beforePageChange.emit(e as WaBeforePageChangeEvent);
    el.addEventListener('wa-before-page-change', handleBeforePageChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-before-page-change', handleBeforePageChange)
    );
    const handlePageChange = (e: Event) =>
      this.pageChange.emit(e as WaPageChangeEvent);
    el.addEventListener('wa-page-change', handlePageChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-page-change', handlePageChange)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }
}

// docs/src/components/ui/Pagination/Pagination.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaPagination from '@awesome.me/webawesome-pro/dist/components/pagination/pagination.js';
import '@awesome.me/webawesome-pro/dist/components/pagination/pagination.js';
import './Pagination.css';
import type { WaBeforePageChangeEvent } from '@awesome.me/webawesome-pro/dist/events/before-page-change.js';
import type { WaPageChangeEvent } from '@awesome.me/webawesome-pro/dist/events/page-change.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome-pro/dist/components/pagination/pagination.js'));
}

/**
 * Pagination splits long lists of content into pages, letting users navigate between them
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Pagination />
 *
 * // With event handlers
 * <Pagination
 *   onBeforePageChange={(e) => console.log(e)} />
 *
 * ```
 */
export interface PaginationProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onBeforePageChange' | 'onPageChange' | 'dir'
> {
  /** The total number of items to paginate */
  total?: number;

  /** The number of items shown per page */
  'page-size'?: number;

  /** The current page, starting at 1 */
  page?: number;

  /** The number of pages to show on each side of the current page */
  'sibling-count'?: number;

  /** The number of pages to always show at the start and end */
  'boundary-count'?: number;

  /** Hides the previous and next buttons */
  'without-nav'?: boolean;

  /** Shows buttons that jump to the first and last pages */
  'with-edges'?: boolean;

  /** Shows a summary of the items on the current page */
  'with-summary'?: boolean;

  /** The pagination layout */
  format?: 'standard' | 'compact';

  /** URL template with {page} placeholder to render page items as links */
  'href-template'?: string;

  /** Renders nothing when there is only one page */
  'hide-single-page'?: boolean;

  /** Accessible name announced by screen readers */
  label?: string;

  /** Visual appearance */
  appearance?: 'outlined' | 'filled' | 'plain';

  /** Disables the pagination */
  disabled?: boolean;

  /** Emitted when the page is about to change but before it does. Canceling this event with `event.preventDefault()` prevents the page from changing. */
  onBeforePageChange?: (event: WaBeforePageChangeEvent) => void;

  /** Emitted after the page changes. */
  onPageChange?: (event: WaPageChangeEvent) => void;
}

export interface PaginationRef {
  /** Reference to the underlying HTML element */
  element: WaPagination | null;
}

export const Pagination = forwardRef<PaginationRef, PaginationProps>(
  (
    { children, className, onBeforePageChange, onPageChange, ...props },
    ref
  ) => {
    const paginationRef = useRef<WaPagination | null>(null);
    const setPaginationRef = useCallback((el: WaPagination | null) => {
      paginationRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return paginationRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = paginationRef.current;
      if (!el) return;

      const handleWaBeforePageChange = (e: Event) => {
        if (onBeforePageChange)
          onBeforePageChange(e as WaBeforePageChangeEvent);
      };

      const handleWaPageChange = (e: Event) => {
        if (onPageChange) onPageChange(e as WaPageChangeEvent);
      };

      el.addEventListener('wa-before-page-change', handleWaBeforePageChange);
      el.addEventListener('wa-page-change', handleWaPageChange);

      return () => {
        el.removeEventListener(
          'wa-before-page-change',
          handleWaBeforePageChange
        );
        el.removeEventListener('wa-page-change', handleWaPageChange);
      };
    }, [onBeforePageChange, onPageChange]);

    return (
      <wa-pagination
        ref={setPaginationRef}
        class={clsx('Pagination', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-pagination>
    );
  }
);

Pagination.displayName = 'Pagination';
