// templates/angular/Card/card.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/card/card.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/card/card.js'));
}

/**
 * Cards can be used to group related subjects in a container
 *
 * @see https://webawesome.com/docs/components/card
 */
@Component({
  selector: 'k-card',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-card
      #element
      [attr.appearance]="appearance"
      [attr.orientation]="orientation"
      [attr.with-header]="withHeader || null"
      [attr.with-footer]="withFooter || null"
      [attr.with-media]="withMedia || null"
    >
      <ng-content />
    </wa-card>
  `,
  styleUrl: './card.component.css',
})
export class CardComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Visual appearance style */
  @Input() appearance?:
    'outlined' | 'filled-outlined' | 'plain' | 'filled' | 'accent';
  /** Card layout orientation */
  @Input() orientation?: 'vertical' | 'horizontal';
  /** Adds header section (for SSR) */
  @Input() withHeader?: boolean;
  /** Adds footer section (for SSR) */
  @Input() withFooter?: boolean;
  /** Adds media section (for SSR) */
  @Input() withMedia?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// templates/react/Card/Card.jsx
import React from 'react';
import clsx from 'clsx';
import './Card.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/card/card.js'));
}

/**
 * Cards can be used to group related subjects in a container
 *
 * @example
 * <Card>
 *   <div slot="header">Card Header</div>
 *   <p>Card content goes here</p>
 *   <div slot="footer">Card Footer</div>
 * </Card>
 *
 * @param {Object} props
 * @param {'outlined' | 'filled-outlined' | 'plain' | 'filled' | 'accent'} [props.appearance] - Visual appearance style
 * @param {'vertical' | 'horizontal'} [props.orientation] - Card layout orientation
 * @param {boolean} [props['with-header']] - Adds header section (for SSR)
 * @param {boolean} [props['with-footer']] - Adds footer section (for SSR)
 * @param {boolean} [props['with-media']] - Adds media section (for SSR)
 * @param {string} [props.className] - Additional CSS classes
 * @param {React.ReactNode} [props.children] - Card content
 */
export const Card = React.forwardRef(
  ({ children, className, ...props }, ref) => {
    React.useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-card ref={ref} class={clsx('Card', className)} {...props}>
        {children}
      </wa-card>
    );
  }
);

Card.displayName = 'Card';
