// templates/vue/ZoomableFrame/ZoomableFrame.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './ZoomableFrame.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js'));
}

/**
 * Zoomable frames display iframe content with zoom controls
 */
export interface ZoomableFrameProps {
  src?: string;
  srcdoc?: string;
  zoom?: number;
  'zoom-levels'?: string;
  allowfullscreen?: boolean;
  loading?: 'eager' | 'lazy';
  'without-controls'?: boolean;
  'without-interaction'?: boolean;
  sandbox?: string;
  referrerpolicy?: string;
}

const props = defineProps<ZoomableFrameProps>();

// Strip undefined and false props before forwarding to the web component.
// Vue boolean-prop coercion materializes absent optional Boolean props as
// `false`, but Web Awesome elements read attribute presence as truthy, so
// we must not forward `false` to <wa-*> (would render pill="" / loading="").
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (value !== undefined && value !== false) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'load': [event: CustomEvent];
  'error': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleLoad = (e: Event) => emit('load', e as CustomEvent);
const handleError = (e: Event) => emit('error', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('load', handleLoad);
  el.addEventListener('error', handleError);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('load', handleLoad);
  el.removeEventListener('error', handleError);
});

defineExpose({
  zoomIn: () => (elementRef.value as any)?.zoomIn?.(),
  zoomOut: () => (elementRef.value as any)?.zoomOut?.(),
  element: elementRef,
});
</script>

<template>
  <wa-zoomable-frame
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-zoomable-frame>
</template>

// templates/react/ZoomableFrame/ZoomableFrame.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './ZoomableFrame.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js'));
}

/**
 * Zoomable frames display iframe content with zoom controls
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ZoomableFrame />
 *
 * // With event handlers
 * <ZoomableFrame
 *   onLoad={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<ZoomableFrameRef>(null);
 * <button onClick={() => ref.current?.zoomIn()}>Call Method</button>
 * <ZoomableFrame ref={ref} />
 * ```
 */
export interface ZoomableFrameProps extends Omit<HTMLAttributes<HTMLElement>, 'onLoad' | 'onError' | 'dir'> {

  /** URL of content to display */
  src?: string;

  /** Inline HTML to render */
  srcdoc?: string;

  /** Current zoom level */
  zoom?: number;

  /** Available zoom levels */
  'zoom-levels'?: string;

  /** Enables fullscreen */
  allowfullscreen?: boolean;

  /** Loading behavior */
  loading?: 'eager' | 'lazy';

  /** Hides zoom controls */
  'without-controls'?: boolean;

  /** Disables interaction */
  'without-interaction'?: boolean;

  /** Security restrictions */
  sandbox?: string;

  /** Referrer policy */
  referrerpolicy?: string;

  /** Emitted when the internal iframe when it finishes loading. */
  onLoad?: (event: CustomEvent) => void;

  /** Emitted from the internal iframe when it fails to load. */
  onError?: (event: CustomEvent) => void;
}

export interface ZoomableFrameRef {

  /** Zooms in to the next available zoom level. */
  zoomIn: () => void;

  /** Zooms out to the previous available zoom level. */
  zoomOut: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const ZoomableFrame = forwardRef<ZoomableFrameRef, ZoomableFrameProps>(
  ({ children, className, onLoad, onError, ...props }, ref) => {
    const zoomableframeRef = useRef<HTMLElement & {
      zoomIn?: () => void;
      zoomOut?: () => void;
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        zoomIn: () => {
          if (zoomableframeRef.current && typeof zoomableframeRef.current.zoomIn === 'function') {
            zoomableframeRef.current.zoomIn();
          }
        },
        zoomOut: () => {
          if (zoomableframeRef.current && typeof zoomableframeRef.current.zoomOut === 'function') {
            zoomableframeRef.current.zoomOut();
          }
        },
        get element() {
          return zoomableframeRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = zoomableframeRef.current;
      if (!el) return;

      const handleLoad = (e: Event) => {
        if (onLoad) onLoad(e as CustomEvent);
      };

      const handleError = (e: Event) => {
        if (onError) onError(e as CustomEvent);
      };

      el.addEventListener('load', handleLoad);
      el.addEventListener('error', handleError);

      return () => {
        el.removeEventListener('load', handleLoad);
        el.removeEventListener('error', handleError);
      };
    }, [onLoad, onError]);

    return (
      <wa-zoomable-frame
        ref={zoomableframeRef}
        class={clsx('ZoomableFrame', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-zoomable-frame>
    );
  }
);

ZoomableFrame.displayName = 'ZoomableFrame';
