// templates/angular/ZoomableFrame/zoomable-frame.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js'));
}

/**
 * Zoomable frames display iframe content with zoom controls
 *
 * @see https://webawesome.com/docs/components/zoomable-frame
 */
@Component({
  selector: 'k-zoomable-frame',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-zoomable-frame
      #element
      [attr.src]="src"
      [attr.srcdoc]="srcdoc"
      [attr.zoom]="zoom"
      [attr.zoom-levels]="zoomLevels"
      [attr.allowfullscreen]="allowfullscreen || null"
      [attr.loading]="loading"
      [attr.without-controls]="withoutControls || null"
      [attr.without-interaction]="withoutInteraction || null"
      [attr.sandbox]="sandbox"
      [attr.referrerpolicy]="referrerpolicy"
      [attr.allow]="allow"
      [attr.name]="name"
      [attr.label]="label"
    >
      <ng-content />
    </wa-zoomable-frame>
  `,
  styleUrl: './zoomable-frame.component.css',
})
export class ZoomableFrameComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** URL of content to display */
  @Input() src?: string;
  /** Inline HTML to render */
  @Input() srcdoc?: string;
  /** Current zoom level */
  @Input() zoom?: number;
  /** Available zoom levels */
  @Input() zoomLevels?: string;
  /** Enables fullscreen */
  @Input() allowfullscreen?: boolean;
  /** Loading behavior */
  @Input() loading?: 'eager' | 'lazy';
  /** Hides zoom controls */
  @Input() withoutControls?: boolean;
  /** Disables interaction */
  @Input() withoutInteraction?: boolean;
  /** Security restrictions */
  @Input() sandbox?: string;
  /** Referrer policy */
  @Input() referrerpolicy?: string;
  /** Permissions Policy for the embedded page; read when the frame loads */
  @Input() allow?: string;
  /** Frame name that links and forms can target */
  @Input() name?: string;
  /** Accessible name describing the framed content */
  @Input() label?: string;

  @Output() load = new EventEmitter<Event>();
  @Output() error = new EventEmitter<Event>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleLoad = (e: Event) => this.load.emit(e);
    el.addEventListener('load', handleLoad);
    this.cleanups.push(() => el.removeEventListener('load', handleLoad));
    const handleError = (e: Event) => this.error.emit(e);
    el.addEventListener('error', handleError);
    this.cleanups.push(() => el.removeEventListener('error', handleError));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  zoomIn(): void {
    (
      this.elementRef.nativeElement as unknown as { zoomIn: () => void }
    ).zoomIn();
  }
  zoomOut(): void {
    (
      this.elementRef.nativeElement as unknown as { zoomOut: () => void }
    ).zoomOut();
  }
}

// templates/react/ZoomableFrame/ZoomableFrame.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaZoomableFrame from '@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js';
import './ZoomableFrame.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/zoomable-frame/zoomable-frame.js'));
}

/**
 * Zoomable frames display iframe content with zoom controls
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ZoomableFrame />
 *
 * // With event handlers
 * <ZoomableFrame
 *   onLoad={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<ZoomableFrameRef>(null);
 * <button onClick={() => ref.current?.zoomIn()}>Call Method</button>
 * <ZoomableFrame ref={ref} />
 * ```
 */
export interface ZoomableFrameProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onLoad' | 'onError' | 'dir'
> {
  /** URL of content to display */
  src?: string;

  /** Inline HTML to render */
  srcdoc?: string;

  /** Current zoom level */
  zoom?: number;

  /** Available zoom levels */
  'zoom-levels'?: string;

  /** Enables fullscreen */
  allowfullscreen?: boolean;

  /** Loading behavior */
  loading?: 'eager' | 'lazy';

  /** Hides zoom controls */
  'without-controls'?: boolean;

  /** Disables interaction */
  'without-interaction'?: boolean;

  /** Security restrictions */
  sandbox?: string;

  /** Referrer policy */
  referrerpolicy?: string;

  /** Permissions Policy for the embedded page; read when the frame loads */
  allow?: string;

  /** Frame name that links and forms can target */
  name?: string;

  /** Accessible name describing the framed content */
  label?: string;

  /** Emitted from the internal iframe when it finishes loading. */
  onLoad?: (event: Event) => void;

  /** Emitted from the internal iframe when it fails to load. */
  onError?: (event: Event) => void;
}

export interface ZoomableFrameRef {
  /** Zooms in to the next available zoom level. */
  zoomIn: () => void;

  /** Zooms out to the previous available zoom level. */
  zoomOut: () => void;
  /** Reference to the underlying HTML element */
  element: WaZoomableFrame | null;
}

export const ZoomableFrame = forwardRef<ZoomableFrameRef, ZoomableFrameProps>(
  ({ children, className, onLoad, onError, ...props }, ref) => {
    const zoomableframeRef = useRef<WaZoomableFrame | null>(null);
    const setZoomableFrameRef = useCallback((el: WaZoomableFrame | null) => {
      zoomableframeRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        zoomIn: () => {
          if (
            zoomableframeRef.current &&
            typeof zoomableframeRef.current.zoomIn === 'function'
          ) {
            zoomableframeRef.current.zoomIn();
          }
        },
        zoomOut: () => {
          if (
            zoomableframeRef.current &&
            typeof zoomableframeRef.current.zoomOut === 'function'
          ) {
            zoomableframeRef.current.zoomOut();
          }
        },
        get element() {
          return zoomableframeRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = zoomableframeRef.current;
      if (!el) return;

      const handleLoad = (e: Event) => {
        if (onLoad) onLoad(e);
      };

      const handleError = (e: Event) => {
        if (onError) onError(e);
      };

      el.addEventListener('load', handleLoad);
      el.addEventListener('error', handleError);

      return () => {
        el.removeEventListener('load', handleLoad);
        el.removeEventListener('error', handleError);
      };
    }, [onLoad, onError]);

    return (
      <wa-zoomable-frame
        ref={setZoomableFrameRef}
        class={clsx('ZoomableFrame', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-zoomable-frame>
    );
  }
);

ZoomableFrame.displayName = 'ZoomableFrame';
