// docs/src/components/ui/ProgressBar/ProgressBar.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/progress-bar/progress-bar.js';
import './ProgressBar.css';

/**
 * Progress bars are used to show the completion of a task or operation
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ProgressBar />
 *
 * // With event handlers
 * <ProgressBar />
 *
 * ```
 */
export interface ProgressBarProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** Current progress (0-100) */
  value?: number;

  /** Shows indeterminate state */
  indeterminate?: boolean;

  /** Accessible label */
  label?: string;
}

export interface ProgressBarRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const ProgressBar = forwardRef<ProgressBarRef, ProgressBarProps>(
  ({ children, className, ...props }, ref) => {
    const progressbarRef = useRef<HTMLElement & {}>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return progressbarRef.current;
        },
      }),
      []
    );

    return (
      <wa-progress-bar
        ref={progressbarRef}
        class={clsx('ProgressBar', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-progress-bar>
    );
  }
);

ProgressBar.displayName = 'ProgressBar';

// templates/vue/ProgressBar/ProgressBar.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './ProgressBar.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/progress-bar/progress-bar.js'));
}

/**
 * Progress bars are used to show the completion of a task or operation
 */
export interface ProgressBarProps {
  value?: number;
  indeterminate?: boolean;
  label?: string;
}

const props = defineProps<ProgressBarProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-progress-bar
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-progress-bar>
</template>
