// templates/react/Badge/Badge.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Badge.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/badge/badge.js'));
}

/**
 * Badges are used to draw attention and display statuses or counts
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Badge />
 *
 * // With event handlers
 * <Badge />
 *
 * ```
 */
export interface BadgeProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The badge's theme variant */
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';

  /** The badge's visual appearance */
  appearance?: 'accent' | 'filled' | 'outlined' | 'filled-outlined';

  /** Draws a pill-style badge with rounded edges */
  pill?: boolean;

  /** Adds an animation to draw attention to the badge */
  attention?: 'none' | 'pulse' | 'bounce';
}

export interface BadgeRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Badge = forwardRef<BadgeRef, BadgeProps>(
  ({ children, className, ...props }, ref) => {
    const badgeRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return badgeRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-badge
        ref={badgeRef}
        class={clsx('Badge', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-badge>
    );
  }
);

Badge.displayName = 'Badge';

// templates/vue/Badge/Badge.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Badge.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/badge/badge.js'));
}

/**
 * Badges are used to draw attention and display statuses or counts
 */
export interface BadgeProps {
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';
  appearance?: 'accent' | 'filled' | 'outlined' | 'filled-outlined';
  pill?: boolean;
  attention?: 'none' | 'pulse' | 'bounce';
}

const props = defineProps<BadgeProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-badge
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-badge>
</template>
