// docs/src/components/ui/Chart/Chart.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/chart/chart.js';
import './Chart.css';

/**
 * Renders interactive data visualisations including bars, lines, pies, and more via Chart.js
 *
 * @example
 * ```tsx
 * // Basic bar chart with JSON config
 * <Chart type="bar" label="Sales">
 *   <script type="application/json">{JSON.stringify({
 *     data: {
 *       labels: ['Jan', 'Feb', 'Mar'],
 *       datasets: [{ label: 'Sales', data: [10, 20, 30] }]
 *     }
 *   })}</script>
 * </Chart>
 *
 * // Line chart with options
 * <Chart type="line" label="Revenue" stacked without-legend />
 * ```
 */
export interface ChartProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** Accessible name read by screen readers */
  label?: string;

  /** Supplementary accessible description for the chart */
  description?: string;

  /** Visualisation style to use for the datasets */
  type?:
    | 'bar'
    | 'line'
    | 'pie'
    | 'doughnut'
    | 'polarArea'
    | 'radar'
    | 'scatter'
    | 'bubble';

  /** Text label shown along the horizontal axis */
  'x-label'?: string;

  /** Text label shown along the vertical axis */
  'y-label'?: string;

  /** Where the dataset legend appears around the chart area */
  'legend-position'?: 'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';

  /** Layers multiple datasets on a single axis */
  stacked?: boolean;

  /** Primary axis for categories (swap to create horizontal charts) */
  'index-axis'?: 'x' | 'y';

  /** Controls which background grid lines are visible */
  grid?: 'x' | 'y' | 'both' | 'none';

  /** Lower bound for the value axis scale */
  min?: number;

  /** Upper bound for the value axis scale */
  max?: number;

  /** Turns off entrance and update transitions */
  'without-animation'?: boolean;

  /** Removes the dataset legend from view */
  'without-legend'?: boolean;

  /** Suppresses hover tooltips on data points */
  'without-tooltip'?: boolean;
}

export interface ChartRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Chart = forwardRef<ChartRef, ChartProps>(
  ({ children, className, ...props }, ref) => {
    const chartRef = useRef<HTMLElement>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return chartRef.current;
        },
      }),
      []
    );

    return (
      <wa-chart
        ref={chartRef}
        class={clsx('Chart', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-chart>
    );
  }
);

Chart.displayName = 'Chart';

// templates/angular/Chart/chart.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/chart/chart.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/chart/chart.js'));
}

/**
 * Renders interactive data visualisations including bars, lines, pies, and more via Chart.js
 *
 * @see https://webawesome.com/docs/components/chart
 */
@Component({
  selector: 'k-chart',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-chart
      #element
      [attr.label]="label"
      [attr.description]="description"
      [attr.type]="type"
      [attr.x-label]="xLabel"
      [attr.y-label]="yLabel"
      [attr.legend-position]="legendPosition"
      [attr.stacked]="stacked || null"
      [attr.index-axis]="indexAxis"
      [attr.grid]="grid"
      [attr.min]="min"
      [attr.max]="max"
      [attr.without-animation]="withoutAnimation || null"
      [attr.without-legend]="withoutLegend || null"
      [attr.without-tooltip]="withoutTooltip || null"
    >
      <ng-content />
    </wa-chart>
  `,
  styleUrl: './chart.component.css',
})
export class ChartComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible name read by screen readers */
  @Input() label?: string;
  /** Supplementary accessible description for the chart */
  @Input() description?: string;
  /** Visualisation style to use for the datasets */
  @Input() type?:
    | 'bar'
    | 'line'
    | 'pie'
    | 'doughnut'
    | 'polarArea'
    | 'radar'
    | 'scatter'
    | 'bubble';
  /** Text label shown along the horizontal axis */
  @Input() xLabel?: string;
  /** Text label shown along the vertical axis */
  @Input() yLabel?: string;
  /** Where the dataset legend appears around the chart area */
  @Input() legendPosition?:
    'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';
  /** Layers multiple datasets on a single axis */
  @Input() stacked?: boolean;
  /** Primary axis for categories (swap to create horizontal charts) */
  @Input() indexAxis?: 'x' | 'y';
  /** Controls which background grid lines are visible */
  @Input() grid?: 'x' | 'y' | 'both' | 'none';
  /** Lower bound for the value axis scale */
  @Input() min?: number;
  /** Upper bound for the value axis scale */
  @Input() max?: number;
  /** Turns off entrance and update transitions */
  @Input() withoutAnimation?: boolean;
  /** Removes the dataset legend from view */
  @Input() withoutLegend?: boolean;
  /** Suppresses hover tooltips on data points */
  @Input() withoutTooltip?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}
