// templates/react/VideoPlaylist/VideoPlaylist.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaVideoPlaylist from '@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js';
import type { WaVideoChangeEvent } from '@awesome.me/webawesome/dist/events/video-change.js';
import './VideoPlaylist.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js'));
}

/**
 * Groups multiple videos into a playlist with next/previous navigation
 *
 * @example
 * ```tsx
 * // Basic usage
 * <VideoPlaylist />
 *
 * // With event handlers
 * <VideoPlaylist
 *   onVideoChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<VideoPlaylistRef>(null);
 * <button onClick={() => ref.current?.next()}>Call Method</button>
 * <VideoPlaylist ref={ref} />
 * ```
 */
export interface VideoPlaylistProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onVideoChange' | 'dir'
> {
  /** The set of controls forwarded to each child video */
  controls?: 'none' | 'standard' | 'full';

  /** The icon library used for placeholder icons */
  'icon-library'?: string;

  onVideoChange?: (event: WaVideoChangeEvent) => void;
}

export interface VideoPlaylistRef {
  next: () => void;

  previous: () => void;

  goTo: (index: number) => void;
  /** Reference to the underlying HTML element */
  element: WaVideoPlaylist | null;
}

export const VideoPlaylist = forwardRef<VideoPlaylistRef, VideoPlaylistProps>(
  ({ children, className, onVideoChange, ...props }, ref) => {
    const videoplaylistRef = useRef<WaVideoPlaylist | null>(null);
    const setVideoPlaylistRef = useCallback((el: WaVideoPlaylist | null) => {
      videoplaylistRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        next: () => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.next === 'function'
          ) {
            videoplaylistRef.current.next();
          }
        },
        previous: () => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.previous === 'function'
          ) {
            videoplaylistRef.current.previous();
          }
        },
        goTo: (index: number) => {
          if (
            videoplaylistRef.current &&
            typeof videoplaylistRef.current.goTo === 'function'
          ) {
            videoplaylistRef.current.goTo(index);
          }
        },
        get element() {
          return videoplaylistRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = videoplaylistRef.current;
      if (!el) return;

      const handleWaVideoChange = (e: Event) => {
        if (onVideoChange) onVideoChange(e as WaVideoChangeEvent);
      };

      el.addEventListener('wa-video-change', handleWaVideoChange);

      return () => {
        el.removeEventListener('wa-video-change', handleWaVideoChange);
      };
    }, [onVideoChange]);

    return (
      <wa-video-playlist
        ref={setVideoPlaylistRef}
        class={clsx('VideoPlaylist', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-video-playlist>
    );
  }
);

VideoPlaylist.displayName = 'VideoPlaylist';

// templates/angular/VideoPlaylist/video-playlist.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js';
import type { WaVideoChangeEvent } from '@awesome.me/webawesome/dist/events/video-change.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video-playlist/video-playlist.js'));
}

/**
 * Groups multiple videos into a playlist with next/previous navigation
 *
 * @see https://webawesome.com/docs/components/video-playlist
 */
@Component({
  selector: 'k-video-playlist',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-video-playlist
      #element
      [attr.controls]="controls"
      [attr.icon-library]="iconLibrary"
    >
      <ng-content />
    </wa-video-playlist>
  `,
  styleUrl: './video-playlist.component.css',
})
export class VideoPlaylistComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The set of controls forwarded to each child video */
  @Input() controls?: 'none' | 'standard' | 'full';
  /** The icon library used for placeholder icons */
  @Input() iconLibrary?: string;

  @Output() videoChange = new EventEmitter<WaVideoChangeEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleVideoChange = (e: Event) =>
      this.videoChange.emit(e as WaVideoChangeEvent);
    el.addEventListener('wa-video-change', handleVideoChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-video-change', handleVideoChange)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  next(): void {
    (this.elementRef.nativeElement as unknown as { next: () => void }).next();
  }
  previous(): void {
    (
      this.elementRef.nativeElement as unknown as { previous: () => void }
    ).previous();
  }
  goTo(index?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        goTo: (index?: number) => void;
      }
    ).goTo(index);
  }
}
