// templates/vue/TabPanel/TabPanel.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './TabPanel.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab-panel/tab-panel.js'));
}

/**
 * Tab panels are used inside tab groups to display content for each tab
 */
export interface TabPanelProps {
  name?: string;
  active?: boolean;
}

const props = defineProps<TabPanelProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-tab-panel
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tab-panel>
</template>

// docs/src/components/ui/TabPanel/TabPanel.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/tab-panel/tab-panel.js';
import './TabPanel.css';

/**
 * Tab panels are used inside tab groups to display content for each tab
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TabPanel />
 *
 * // With event handlers
 * <TabPanel />
 *
 * ```
 */
export interface TabPanelProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** The panel name */
  name?: string;

  /** Whether the panel is shown */
  active?: boolean;
}

export interface TabPanelRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const TabPanel = forwardRef<TabPanelRef, TabPanelProps>(
  ({ children, className, ...props }, ref) => {
    const tabpanelRef = useRef<HTMLElement & {}>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return tabpanelRef.current;
        },
      }),
      []
    );

    return (
      <wa-tab-panel
        ref={tabpanelRef}
        class={clsx('TabPanel', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tab-panel>
    );
  }
);

TabPanel.displayName = 'TabPanel';
