// docs/src/components/ui/Divider/Divider.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/divider/divider.js';
import './Divider.css';

/**
 * Dividers are used to visually separate content
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Divider />
 *
 * // With event handlers
 * <Divider />
 *
 * ```
 */
export interface DividerProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** Divider orientation */
  orientation?: 'horizontal' | 'vertical';
}

export interface DividerRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Divider = forwardRef<DividerRef, DividerProps>(
  ({ children, className, ...props }, ref) => {
    const dividerRef = useRef<HTMLElement & {}>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return dividerRef.current;
        },
      }),
      []
    );

    return (
      <wa-divider
        ref={dividerRef}
        class={clsx('Divider', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-divider>
    );
  }
);

Divider.displayName = 'Divider';

// templates/vue/Divider/Divider.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Divider.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/divider/divider.js'));
}

/**
 * Dividers are used to visually separate content
 */
export interface DividerProps {
  orientation?: 'horizontal' | 'vertical';
}

const props = defineProps<DividerProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-divider
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-divider>
</template>
