// docs/src/components/ui/CarouselItem/CarouselItem.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/carousel-item/carousel-item.js';
import './CarouselItem.css';

/**
 * Represents an individual slide within a carousel component
 *
 * @example
 * ```tsx
 * <Carousel>
 *   <CarouselItem>
 *     <img src="slide1.jpg" alt="Slide 1" />
 *   </CarouselItem>
 *   <CarouselItem>
 *     <img src="slide2.jpg" alt="Slide 2" />
 *   </CarouselItem>
 * </Carousel>
 * ```
 */
export type CarouselItemProps = Omit<HTMLAttributes<HTMLElement>, 'dir'>;

export const CarouselItem = forwardRef<HTMLElement, CarouselItemProps>(
  ({ children, className, ...props }, ref) => {
    return (
      <wa-carousel-item
        ref={ref}
        class={clsx('CarouselItem', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-carousel-item>
    );
  }
);

CarouselItem.displayName = 'CarouselItem';

// templates/vue/CarouselItem/CarouselItem.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './CarouselItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/carousel-item/carousel-item.js'));
}

/**
 * Represents an individual slide within a carousel component
 */
export interface CarouselItemProps {

}

const props = defineProps<CarouselItemProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-carousel-item
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-carousel-item>
</template>
