// templates/vue/TabGroup/TabGroup.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './TabGroup.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab-group/tab-group.js'));
}

/**
 * Tab groups organize content into a container that shows one section at a time
 */
export interface TabGroupProps {
  placement?: 'top' | 'bottom' | 'start' | 'end';
  activation?: 'auto' | 'manual';
  'without-scroll-controls'?: boolean;
  active?: string;
}

const props = defineProps<TabGroupProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-tab-show': [event: CustomEvent];
  'wa-tab-hide': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaTabShow = (e: Event) => emit('wa-tab-show', e as CustomEvent);
const handleWaTabHide = (e: Event) => emit('wa-tab-hide', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-tab-show', handleWaTabShow);
  el.addEventListener('wa-tab-hide', handleWaTabHide);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-tab-show', handleWaTabShow);
  el.removeEventListener('wa-tab-hide', handleWaTabHide);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-tab-group
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tab-group>
</template>

// docs/src/components/ui/TabGroup/TabGroup.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/tab-group/tab-group.js';
import './TabGroup.css';

/**
 * Tab groups organize content into a container that shows one section at a time
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TabGroup />
 *
 * // With event handlers
 * <TabGroup
 *   onTabShow={(e) => console.log(e)} />
 *
 * ```
 */
export interface TabGroupProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onTabShow' | 'onTabHide' | 'dir'
> {
  /** Tab position */
  placement?: 'top' | 'bottom' | 'start' | 'end';

  /** Panel activation method */
  activation?: 'auto' | 'manual';

  /** Disables scroll buttons */
  'without-scroll-controls'?: boolean;

  /** Active tab value (controlled) */
  active?: string;

  /** Emitted when a tab is shown. */
  onTabShow?: (event: CustomEvent) => void;

  /** Emitted when a tab is hidden. */
  onTabHide?: (event: CustomEvent) => void;
}

export interface TabGroupRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const TabGroup = forwardRef<TabGroupRef, TabGroupProps>(
  ({ children, className, onTabShow, onTabHide, ...props }, ref) => {
    const tabgroupRef = useRef<HTMLElement & {}>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return tabgroupRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = tabgroupRef.current;
      if (!el) return;

      const handleTabShow = (e: Event) => {
        if (onTabShow) onTabShow(e as CustomEvent);
      };

      const handleTabHide = (e: Event) => {
        if (onTabHide) onTabHide(e as CustomEvent);
      };

      el.addEventListener('wa-tab-show', handleTabShow);
      el.addEventListener('wa-tab-hide', handleTabHide);

      return () => {
        el.removeEventListener('wa-tab-show', handleTabShow);
        el.removeEventListener('wa-tab-hide', handleTabHide);
      };
    }, [onTabShow, onTabHide]);

    return (
      <wa-tab-group
        ref={tabgroupRef}
        class={clsx('TabGroup', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tab-group>
    );
  }
);

TabGroup.displayName = 'TabGroup';
