// templates/angular/RadioGroup/radio-group.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/radio-group/radio-group.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/radio-group/radio-group.js'));
}

/**
 * Radio groups are used to group multiple radios so only one can be selected
 *
 * @see https://webawesome.com/docs/components/radio-group
 */
@Component({
  selector: 'k-radio-group',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-radio-group
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.name]="name"
      [attr.value]="value"
      [attr.size]="size"
      [attr.required]="required || null"
      [attr.orientation]="orientation"
      [attr.disabled]="disabled || null"
      [attr.invalid]="invalid || null"
      [attr.help-text]="helpText"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-radio-group>
  `,
  styleUrl: './radio-group.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => RadioGroupComponent),
      multi: true,
    },
  ],
})
export class RadioGroupComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Group label */
  @Input() label?: string;
  /** Hint text */
  @Input() hint?: string;
  /** Form field name */
  @Input() name?: string;
  /** Selected value */
  @Input() value?: string;
  /** Radio size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Makes selection required */
  @Input() required?: boolean;
  /** Layout direction */
  @Input() orientation?: 'horizontal' | 'vertical';
  /** Disables the group */
  @Input() disabled?: boolean;
  /** Shows invalid/error state */
  @Input() invalid?: boolean;
  /** Help text below the group */
  @Input() helpText?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() invalidEvent = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleInvalidEvent = (e: Event) =>
      this.invalidEvent.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalidEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalidEvent)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// docs/src/components/ui/RadioGroup/RadioGroup.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/radio-group/radio-group.js';
import './RadioGroup.css';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Radio groups are used to group multiple radios so only one can be selected
 *
 * @example
 * ```tsx
 * // Basic usage
 * <RadioGroup />
 *
 * // With event handlers
 * <RadioGroup
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<RadioGroupRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <RadioGroup ref={ref} />
 * ```
 */
export interface RadioGroupProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onInput' | 'onChange' | 'onInvalid' | 'dir'
> {
  /** Group label */
  label?: string;

  /** Hint text */
  hint?: string;

  /** Form field name */
  name?: string;

  /** Selected value */
  value?: string;

  /** Radio size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Layout direction */
  orientation?: 'horizontal' | 'vertical';

  /** Disables the group */
  disabled?: boolean;

  /** Shows invalid/error state */
  invalid?: boolean;

  /** Help text below the group */
  'help-text'?: string;

  /** Makes selection required */
  required?: boolean;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the radio group receives user input. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the radio group's selected value changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface RadioGroupRef {
  /** Sets focus on the radio group. */
  focus: (options: FocusOptions) => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const RadioGroup = forwardRef<RadioGroupRef, RadioGroupProps>(
  ({ children, className, onInput, onChange, onInvalid, ...props }, ref) => {
    const radiogroupRef = useRef<
      HTMLElement & {
        focus?: (options: FocusOptions) => void;
      }
    >(null);

    const setRadiogroupRef = useCallback((el: typeof radiogroupRef.current) => {
      radiogroupRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            radiogroupRef.current &&
            typeof radiogroupRef.current.focus === 'function'
          ) {
            radiogroupRef.current.focus(options);
          }
        },
        get element() {
          return radiogroupRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = radiogroupRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onInput, onChange, onInvalid]);

    return (
      <wa-radio-group
        ref={setRadiogroupRef}
        class={clsx('RadioGroup', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-radio-group>
    );
  }
);

RadioGroup.displayName = 'RadioGroup';
