// templates/vue/Comparison/Comparison.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Comparison.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/comparison/comparison.js'));
}

/**
 * Compare visual differences between similar content with a sliding panel
 */
export interface ComparisonProps {
  position?: number;
}

const props = defineProps<ComparisonProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'change': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleChange = (e: Event) => emit('change', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('change', handleChange);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('change', handleChange);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-comparison
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-comparison>
</template>

// docs/.kigumi/snapshots/Comparison/Comparison.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/comparison/comparison.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/comparison/comparison.js';
import './Comparison.css';

/**
 * Compare visual differences between similar content with a sliding panel
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Comparison />
 *
 * // With event handlers
 * <Comparison
 *   onChange={(e) => console.log(e)} />
 *
 * ```
 */
export interface ComparisonProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onChange' | 'dir'
> {
  /** Divider location as percentage (0-100) */
  position?: number;

  /** Emitted when the position changes. */
  onChange?: (event: CustomEvent) => void;
}

export interface ComparisonRef {
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Comparison = forwardRef<ComparisonRef, ComparisonProps>(
  ({ children, className, onChange, ...props }, ref) => {
    const comparisonRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return comparisonRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = comparisonRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as CustomEvent);
      };

      el.addEventListener('change', handleChange);

      return () => {
        el.removeEventListener('change', handleChange);
      };
    }, [onChange]);

    return (
      <wa-comparison
        ref={(el: WaElement | null) => {
          comparisonRef.current = el;
        }}
        class={clsx('Comparison', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-comparison>
    );
  }
);

Comparison.displayName = 'Comparison';
