// templates/angular/Page/page.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/page/page.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/page/page.js'));
}

/**
 * Pages offer an easy way to scaffold entire page layouts using minimal markup
 *
 * @see https://webawesome.com/docs/components/page
 */
@Component({
  selector: 'k-page',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-page
      #element
      [attr.disable-navigation-toggle]="disableNavigationToggle || null"
      [attr.mobile-breakpoint]="mobileBreakpoint"
      [attr.navigation-placement]="navigationPlacement"
      [attr.nav-open]="navOpen || null"
      [attr.view]="view"
      [attr.nonce]="nonce"
    >
      <ng-content />
    </wa-page>
  `,
  styleUrl: './page.component.css',
})
export class PageComponent implements AfterViewInit {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Hide default hamburger button; auto-sets true if custom toggle element present */
  @Input() disableNavigationToggle?: boolean;
  /** Viewport width threshold for navigation collapse; accepts numbers (px) or CSS lengths */
  @Input() mobileBreakpoint?: string;
  /** Navigation drawer position on mobile */
  @Input() navigationPlacement?: 'start' | 'end';
  /** Mobile navigation drawer open state */
  @Input() navOpen?: boolean;
  /** Current viewport classification relative to breakpoint */
  @Input() view?: 'mobile' | 'desktop';
  /** CSP nonce for the injected media-query style tag; falls back to window.litNonce */
  @Input() nonce?: string;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }

  visiblePixelsInViewport(element?: HTMLElement | null): void {
    (
      this.elementRef.nativeElement as unknown as {
        visiblePixelsInViewport: (element?: HTMLElement | null) => void;
      }
    ).visiblePixelsInViewport(element);
  }
  showNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as { showNavigation: () => void }
    ).showNavigation();
  }
  hideNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as { hideNavigation: () => void }
    ).hideNavigation();
  }
  toggleNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as {
        toggleNavigation: () => void;
      }
    ).toggleNavigation();
  }
}

// templates/react/Page/Page.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaPage from '@awesome.me/webawesome/dist/components/page/page.js';
import './Page.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/page/page.js'));
}

/**
 * Pages offer an easy way to scaffold entire page layouts using minimal markup
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Page />
 *
 * // With event handlers
 * <Page />
 *
 * // With ref methods
 * const ref = useRef<PageRef>(null);
 * <button onClick={() => ref.current?.visiblePixelsInViewport()}>Call Method</button>
 * <Page ref={ref} />
 * ```
 */
export interface PageProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** Hide default hamburger button; auto-sets true if custom toggle element present */
  'disable-navigation-toggle'?: boolean;

  /** Viewport width threshold for navigation collapse; accepts numbers (px) or CSS lengths */
  'mobile-breakpoint'?: string;

  /** Navigation drawer position on mobile */
  'navigation-placement'?: 'start' | 'end';

  /** Mobile navigation drawer open state */
  'nav-open'?: boolean;

  /** Current viewport classification relative to breakpoint */
  view?: 'mobile' | 'desktop';

  /** CSP nonce for the injected media-query style tag; falls back to window.litNonce */
  nonce?: string;
}

export interface PageRef {
  /** https://stackoverflow.com/a/26831113
This prevents awkward gaps when scrolling the page and the aside / menu don't "fill" the gaps. */
  visiblePixelsInViewport: (element: HTMLElement | null) => void;

  /** Shows the mobile navigation drawer */
  showNavigation: () => void;

  /** Hides the mobile navigation drawer */
  hideNavigation: () => void;

  /** Toggles the mobile navigation drawer */
  toggleNavigation: () => void;
  /** Reference to the underlying HTML element */
  element: WaPage | null;
}

export const Page = forwardRef<PageRef, PageProps>(
  ({ children, className, ...props }, ref) => {
    const pageRef = useRef<WaPage | null>(null);
    const setPageRef = useCallback((el: WaPage | null) => {
      pageRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        visiblePixelsInViewport: (element: HTMLElement | null) => {
          if (
            pageRef.current &&
            typeof pageRef.current.visiblePixelsInViewport === 'function'
          ) {
            pageRef.current.visiblePixelsInViewport(element);
          }
        },
        showNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.showNavigation === 'function'
          ) {
            pageRef.current.showNavigation();
          }
        },
        hideNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.hideNavigation === 'function'
          ) {
            pageRef.current.hideNavigation();
          }
        },
        toggleNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.toggleNavigation === 'function'
          ) {
            pageRef.current.toggleNavigation();
          }
        },
        get element() {
          return pageRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-page
        ref={setPageRef}
        class={clsx('Page', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-page>
    );
  }
);

Page.displayName = 'Page';
