// templates/angular/Page/page.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/page/page.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/page/page.js'));
}

/**
 * Pages offer an easy way to scaffold entire page layouts using minimal markup
 *
 * @see https://webawesome.com/docs/components/page
 */
@Component({
  selector: 'k-page',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-page
      #element
      [attr.disable-navigation-toggle]="disableNavigationToggle || null"
      [attr.mobile-breakpoint]="mobileBreakpoint"
      [attr.navigation-placement]="navigationPlacement"
      [attr.nav-open]="navOpen || null"
      [attr.view]="view"
      [attr.nonce]="nonce"
    >
      <ng-content />
    </wa-page>
  `,
  styleUrl: './page.component.css',
})
export class PageComponent implements AfterViewInit {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Hide default hamburger button; auto-sets true if custom toggle element present */
  @Input() disableNavigationToggle?: boolean;
  /** Viewport width threshold for navigation collapse; accepts numbers (px) or CSS lengths */
  @Input() mobileBreakpoint?: string;
  /** Navigation drawer position on mobile */
  @Input() navigationPlacement?: 'start' | 'end';
  /** Mobile navigation drawer open state */
  @Input() navOpen?: boolean;
  /** Current viewport classification relative to breakpoint */
  @Input() view?: 'mobile' | 'desktop';
  /** CSP nonce for the injected media-query style tag; falls back to window.litNonce */
  @Input() nonce?: string;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }

  visiblePixelsInViewport(element?: HTMLElement | null): void {
    (
      this.elementRef.nativeElement as unknown as {
        visiblePixelsInViewport: (element?: HTMLElement | null) => void;
      }
    ).visiblePixelsInViewport(element);
  }
  showNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as { showNavigation: () => void }
    ).showNavigation();
  }
  hideNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as { hideNavigation: () => void }
    ).hideNavigation();
  }
  toggleNavigation(): void {
    (
      this.elementRef.nativeElement as unknown as {
        toggleNavigation: () => void;
      }
    ).toggleNavigation();
  }
}

// templates/react/Page/Page.jsx
import React from 'react';
import clsx from 'clsx';
import './Page.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/page/page.js'));
}

/**
 * Pages offer an easy way to scaffold entire page layouts using minimal markup
 *
 * @example
 * ```jsx
 * import { Page } from './components/ui';
 *
 * function App() {
 *   return (
 *     <Page>
 *       <div slot="header">
 *         <h1>My Application</h1>
 *       </div>
 *       <nav slot="navigation">
 *         <a href="/">Home</a>
 *         <a href="/about">About</a>
 *       </nav>
 *       <div>
 *         <h2>Main Content</h2>
 *         <p>Your page content goes here</p>
 *       </div>
 *       <div slot="footer">
 *         <p>&copy; 2026 My Company</p>
 *       </div>
 *     </Page>
 *   );
 * }
 * ```
 */

/**
 * @typedef {Object} PageProps
 * @property {boolean} [disableNavigationToggle] - Controls visibility of default hamburger button
 * @property {string} [mobileBreakpoint] - Viewport width threshold for hiding navigation
 * @property {'start' | 'end'} [navigationPlacement] - Drawer placement location when in mobile viewport
 * @property {boolean} [navOpen] - Controls mobile navigation drawer open/closed state
 * @property {'mobile' | 'desktop'} [view] - Reflects viewport relative to mobile-breakpoint
 * @property {React.ReactNode} [children] - Content of the page
 * @property {string} [className] - Additional CSS classes
 * @property {boolean} [disable-navigation-toggle] - Hide default hamburger button; auto-sets true if custom toggle element present
 * @property {string} [mobile-breakpoint] - Viewport width threshold for navigation collapse; accepts numbers (px) or CSS lengths
 * @property {string} [navigation-placement] - Navigation drawer position on mobile: start | end
 * @property {boolean} [nav-open] - Mobile navigation drawer open state
 * @property {string} [nonce] - CSP nonce for the injected media-query style tag; falls back to window.litNonce
 */

/**
 * @typedef {Object} PageRef
 * @property {() => void} hideNavigation - Hides the mobile navigation drawer
 * @property {() => void} showNavigation - Shows the mobile navigation drawer
 * @property {() => void} toggleNavigation - Toggles the mobile navigation drawer
 * @property {(element: HTMLElement | null) => number | void} visiblePixelsInViewport - Calculates visible area
 * @property {HTMLElement | null} element - The underlying HTML element
 */

/**
 * @type {React.ForwardRefExoticComponent<PageProps & React.RefAttributes<PageRef>>}
 */
export const Page = React.forwardRef(
  ({ children, className, navOpen, ...props }, ref) => {
    const pageRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        hideNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.hideNavigation === 'function'
          ) {
            pageRef.current.hideNavigation();
          }
        },
        showNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.showNavigation === 'function'
          ) {
            pageRef.current.showNavigation();
          }
        },
        toggleNavigation: () => {
          if (
            pageRef.current &&
            typeof pageRef.current.toggleNavigation === 'function'
          ) {
            pageRef.current.toggleNavigation();
          }
        },
        visiblePixelsInViewport: (element) => {
          if (
            pageRef.current &&
            typeof pageRef.current.visiblePixelsInViewport === 'function'
          ) {
            return pageRef.current.visiblePixelsInViewport(element);
          }
        },
        get element() {
          return pageRef.current;
        },
      }),
      []
    );

    // Sync navOpen prop with page element
    React.useEffect(() => {
      ensureLoaded();
      const el = pageRef.current;
      if (!el || navOpen === undefined) return;

      // Sync navOpen prop with element state
      const isNavOpen = el.navOpen ?? false;
      if (navOpen && !isNavOpen) {
        el.showNavigation?.();
      } else if (!navOpen && isNavOpen) {
        el.hideNavigation?.();
      }
    }, [navOpen]);

    return (
      <wa-page ref={pageRef} class={clsx('Page', className)} {...props}>
        {children}
      </wa-page>
    );
  }
);

Page.displayName = 'Page';
