// templates/react/DropdownItem/DropdownItem.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaDropdownItem from '@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js';
import './DropdownItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js'));
}

/**
 * Dropdown items are used inside dropdowns to represent individual menu items
 *
 * @example
 * ```tsx
 * // Basic usage
 * <DropdownItem />
 *
 * // With event handlers
 * <DropdownItem
 *   onBlur={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<DropdownItemRef>(null);
 * <button onClick={() => ref.current?.openSubmenu()}>Call Method</button>
 * <DropdownItem ref={ref} />
 * ```
 */
export interface DropdownItemProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onBlur' | 'onFocus' | 'dir'
> {
  /** The type of menu item */
  type?: 'normal' | 'checkbox';

  /** Draws the item in a checked state (checkbox type) */
  checked?: boolean;

  /** A unique value for the menu item */
  value?: string;

  /** Disables the menu item */
  disabled?: boolean;

  /** Draws the item in a loading state */
  loading?: boolean;

  /** The dropdown item variant */
  variant?: 'default' | 'danger';

  /** When set, selecting the item navigates to this URL */
  href?: string;

  /** Tells the browser where to open the link (when href is set) */
  target?: '_blank' | '_parent' | '_self' | '_top';

  /** The rel attribute on the underlying link (when href is set) */
  rel?: string;

  /** Download filename (when href is set) */
  download?: string;

  /** Emitted when the dropdown item loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the dropdown item gains focus. */
  onFocus?: (event: FocusEvent) => void;
}

export interface DropdownItemRef {
  /** Opens the submenu. */
  openSubmenu: () => void;

  /** Closes the submenu. */
  closeSubmenu: () => void;
  /** Reference to the underlying HTML element */
  element: WaDropdownItem | null;
}

export const DropdownItem = forwardRef<DropdownItemRef, DropdownItemProps>(
  ({ children, className, onBlur, onFocus, ...props }, ref) => {
    const dropdownitemRef = useRef<WaDropdownItem | null>(null);
    const setDropdownItemRef = useCallback((el: WaDropdownItem | null) => {
      dropdownitemRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        openSubmenu: () => {
          if (
            dropdownitemRef.current &&
            typeof dropdownitemRef.current.openSubmenu === 'function'
          ) {
            dropdownitemRef.current.openSubmenu();
          }
        },
        closeSubmenu: () => {
          if (
            dropdownitemRef.current &&
            typeof dropdownitemRef.current.closeSubmenu === 'function'
          ) {
            dropdownitemRef.current.closeSubmenu();
          }
        },
        get element() {
          return dropdownitemRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = dropdownitemRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
      };
    }, [onBlur, onFocus]);

    return (
      <wa-dropdown-item
        ref={setDropdownItemRef}
        class={clsx('DropdownItem', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-dropdown-item>
    );
  }
);

DropdownItem.displayName = 'DropdownItem';

// templates/angular/DropdownItem/dropdown-item.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js'));
}

/**
 * Dropdown items are used inside dropdowns to represent individual menu items
 *
 * @see https://webawesome.com/docs/components/dropdown-item
 */
@Component({
  selector: 'k-dropdown-item',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-dropdown-item
      #element
      [attr.type]="type"
      [attr.checked]="checked || null"
      [attr.value]="value"
      [attr.disabled]="disabled || null"
      [attr.loading]="loading || null"
      [attr.variant]="variant"
      [attr.href]="href"
      [attr.target]="target"
      [attr.rel]="rel"
      [attr.download]="download"
    >
      <ng-content />
    </wa-dropdown-item>
  `,
  styleUrl: './dropdown-item.component.css',
})
export class DropdownItemComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The type of menu item */
  @Input() type?: 'normal' | 'checkbox';
  /** Draws the item in a checked state (checkbox type) */
  @Input() checked?: boolean;
  /** A unique value for the menu item */
  @Input() value?: string;
  /** Disables the menu item */
  @Input() disabled?: boolean;
  /** Draws the item in a loading state */
  @Input() loading?: boolean;
  /** The dropdown item variant */
  @Input() variant?: 'default' | 'danger';
  /** When set, selecting the item navigates to this URL */
  @Input() href?: string;
  /** Tells the browser where to open the link (when href is set) */
  @Input() target?: '_blank' | '_parent' | '_self' | '_top';
  /** The rel attribute on the underlying link (when href is set) */
  @Input() rel?: string;
  /** Download filename (when href is set) */
  @Input() download?: string;

  @Output() blur = new EventEmitter<FocusEvent>();
  @Output() focus = new EventEmitter<FocusEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBlur = (e: Event) => this.blur.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlur);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlur));
    const handleFocus = (e: Event) => this.focus.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocus);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocus));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  openSubmenu(): void {
    (
      this.elementRef.nativeElement as unknown as { openSubmenu: () => void }
    ).openSubmenu();
  }
  closeSubmenu(): void {
    (
      this.elementRef.nativeElement as unknown as { closeSubmenu: () => void }
    ).closeSubmenu();
  }
}
