// templates/react/SplitPanel/SplitPanel.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './SplitPanel.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/split-panel/split-panel.js'));
}

/**
 * Split panels display two adjacent panels with a divider for resizing
 *
 * @example
 * ```tsx
 * // Basic usage
 * <SplitPanel />
 *
 * // With event handlers
 * <SplitPanel
 *   onReposition={(e) => console.log(e)} />
 *
 * ```
 */
export interface SplitPanelProps extends Omit<HTMLAttributes<HTMLElement>, 'onReposition' | 'dir'> {

  /** Divider position (%) */
  position?: number;

  /** Divider position (px) */
  'position-in-pixels'?: number;

  /** Panel orientation */
  orientation?: 'horizontal' | 'vertical';

  /** Primary panel */
  primary?: 'start' | 'end';

  /** Disables resizing */
  disabled?: boolean;

  /** Snap points */
  snap?: string;

  /** Snap threshold (px) */
  'snap-threshold'?: number;

  /** Emitted when the divider's position changes. */
  onReposition?: (event: CustomEvent) => void;
}

export interface SplitPanelRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const SplitPanel = forwardRef<SplitPanelRef, SplitPanelProps>(
  ({ children, className, onReposition, ...props }, ref) => {
    const splitpanelRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return splitpanelRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = splitpanelRef.current;
      if (!el) return;

      const handleWaReposition = (e: Event) => {
        if (onReposition) onReposition(e as CustomEvent);
      };

      el.addEventListener('wa-reposition', handleWaReposition);

      return () => {
        el.removeEventListener('wa-reposition', handleWaReposition);
      };
    }, [onReposition]);

    return (
      <wa-split-panel
        ref={splitpanelRef}
        class={clsx('SplitPanel', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-split-panel>
    );
  }
);

SplitPanel.displayName = 'SplitPanel';

// templates/vue/SplitPanel/SplitPanel.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './SplitPanel.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/split-panel/split-panel.js'));
}

/**
 * Split panels display two adjacent panels with a divider for resizing
 */
export interface SplitPanelProps {
  position?: number;
  'position-in-pixels'?: number;
  orientation?: 'horizontal' | 'vertical';
  primary?: 'start' | 'end';
  disabled?: boolean;
  snap?: string;
  'snap-threshold'?: number;
}

const props = defineProps<SplitPanelProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-reposition': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaReposition = (e: Event) => emit('wa-reposition', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-reposition', handleWaReposition);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-reposition', handleWaReposition);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-split-panel
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-split-panel>
</template>
