// templates/angular/Rating/rating.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/rating/rating.js';
import type { WaHoverEvent } from '@awesome.me/webawesome/dist/events/hover.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/rating/rating.js'));
}

/**
 * Ratings give users a way to quickly view and provide feedback
 *
 * @see https://webawesome.com/docs/components/rating
 */
@Component({
  selector: 'k-rating',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-rating
      #element
      [attr.label]="label"
      [attr.value]="value"
      [attr.default-value]="defaultValue"
      [attr.max]="max"
      [attr.precision]="precision"
      [attr.readonly]="readonly || null"
      [attr.disabled]="disabled || null"
      [attr.name]="name"
      [attr.required]="required || null"
      [attr.size]="size"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-rating>
  `,
  styleUrl: './rating.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => RatingComponent),
      multi: true,
    },
  ],
})
export class RatingComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible label */
  @Input() label?: string;
  /** Current rating value */
  @Input() value?: number;
  /** Value the rating returns to when its form is reset */
  @Input() defaultValue?: number;
  /** Maximum rating value */
  @Input() max?: number;
  /** Rating precision (e.g., 0.5) */
  @Input() precision?: number;
  /** Makes the rating readonly */
  @Input() readonly?: boolean;
  /** Disables the rating */
  @Input() disabled?: boolean;
  /** Form field name for submission */
  @Input() name?: string;
  /** Makes the rating required for form submission */
  @Input() required?: boolean;
  /** Rating size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() change = new EventEmitter<Event>();
  @Output() hover = new EventEmitter<WaHoverEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleHover = (e: Event) => this.hover.emit(e as WaHoverEvent);
    el.addEventListener('wa-hover', handleHover);
    this.cleanups.push(() => el.removeEventListener('wa-hover', handleHover));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('change', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('change', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// templates/react/Rating/Rating.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaRating from '@awesome.me/webawesome/dist/components/rating/rating.js';
import type { WaHoverEvent } from '@awesome.me/webawesome/dist/events/hover.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import './Rating.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/rating/rating.js'));
}

/**
 * Ratings give users a way to quickly view and provide feedback
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Rating />
 *
 * // With event handlers
 * <Rating
 *   onChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<RatingRef>(null);
 * <button onClick={() => ref.current?.resetValidity()}>Call Method</button>
 * <Rating ref={ref} />
 * ```
 */
export interface RatingProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onChange' | 'onHover' | 'onInvalid' | 'dir'
> {
  /** Accessible label */
  label?: string;

  /** Current rating value */
  value?: number;

  /** Value the rating returns to when its form is reset */
  'default-value'?: number;

  /** Maximum rating value */
  max?: number;

  /** Rating precision (e.g., 0.5) */
  precision?: number;

  /** Makes the rating readonly */
  readonly?: boolean;

  /** Disables the rating */
  disabled?: boolean;

  /** Form field name for submission */
  name?: string;

  /** Makes the rating required for form submission */
  required?: boolean;

  /** Rating size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the rating's value changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the user hovers over a value. The `phase` property indicates when hovering starts, moves to a new value, or ends. The `value` property tells what the rating's value would be if the user were to commit to the hovered value. */
  onHover?: (event: WaHoverEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface RatingRef {
  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaRating | null;
}

export const Rating = forwardRef<RatingRef, RatingProps>(
  ({ children, className, onChange, onHover, onInvalid, ...props }, ref) => {
    const ratingRef = useRef<WaRating | null>(null);
    const setRatingRef = useCallback((el: WaRating | null) => {
      ratingRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        setCustomValidity: (message: string) => {
          if (
            ratingRef.current &&
            typeof ratingRef.current.setCustomValidity === 'function'
          ) {
            ratingRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            ratingRef.current &&
            typeof ratingRef.current.formStateRestoreCallback === 'function'
          ) {
            ratingRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            ratingRef.current &&
            typeof ratingRef.current.resetValidity === 'function'
          ) {
            ratingRef.current.resetValidity();
          }
        },
        get element() {
          return ratingRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = ratingRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleWaHover = (e: Event) => {
        if (onHover) onHover(e as WaHoverEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('change', handleChange);
      el.addEventListener('wa-hover', handleWaHover);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('change', handleChange);
        el.removeEventListener('wa-hover', handleWaHover);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onChange, onHover, onInvalid]);

    return (
      <wa-rating
        ref={setRatingRef}
        class={clsx('Rating', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-rating>
    );
  }
);

Rating.displayName = 'Rating';
