// templates/angular/TagInput/tag-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/tag-input/tag-input.js';
import type { WaClearEvent } from '@awesome.me/webawesome/dist/events/clear.js';
import type { WaCreateEvent } from '@awesome.me/webawesome/dist/events/create.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/tag-input/tag-input.js'));
}

/**
 * Tag inputs collect a list of short values, such as keywords or labels, as removable tags
 *
 * @see https://webawesome.com/docs/components/tag-input
 */
@Component({
  selector: 'k-tag-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-tag-input
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.value]="value"
      [attr.placeholder]="placeholder"
      [attr.delimiter]="delimiter"
      [attr.max-tags]="maxTags"
      [attr.min-tags]="minTags"
      [attr.allow-duplicates]="allowDuplicates || null"
      [attr.with-clear]="withClear || null"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.pill]="pill || null"
      [attr.required]="required || null"
      [attr.readonly]="readonly || null"
      [attr.disabled]="disabled || null"
      [attr.name]="name"
      [attr.autocomplete]="autocomplete"
      [attr.autocapitalize]="autocapitalize"
      [attr.enterkeyhint]="enterkeyhint"
      [attr.inputmode]="inputmode"
      [attr.autocorrect]="
        autocorrect == null ? null : autocorrect ? 'on' : 'off'
      "
      [attr.spellcheck]="
        spellcheck == null ? null : spellcheck ? 'true' : 'false'
      "
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-tag-input>
  `,
  styleUrl: './tag-input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TagInputComponent),
      multi: true,
    },
  ],
})
export class TagInputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The tag input's label */
  @Input() label?: string;
  /** The tag input's hint */
  @Input() hint?: string;
  /** Default value as a delimiter-separated string */
  @Input() value?: string;
  /** Placeholder text shown in the text box */
  @Input() placeholder?: string;
  /** Characters that turn typed text into a tag */
  @Input() delimiter?: string;
  /** The maximum number of tags that can be added */
  @Input() maxTags?: number;
  /** The minimum number of tags required for the control to be valid */
  @Input() minTags?: number;
  /** Allows the same tag to be added more than once */
  @Input() allowDuplicates?: boolean;
  /** Adds a clear button that removes all tags */
  @Input() withClear?: boolean;
  /** Visual appearance */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** The tag input's size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Draws a pill-style tag input with rounded edges */
  @Input() pill?: boolean;
  /** Requires at least one tag */
  @Input() required?: boolean;
  /** Makes the tag input readonly */
  @Input() readonly?: boolean;
  /** Disables the form control */
  @Input() disabled?: boolean;
  /** The name of the input, submitted with form data */
  @Input() name?: string;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Controls automatic capitalization */
  @Input() autocapitalize?:
    'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';
  /** Hint for Enter key label on virtual keyboards */
  @Input() enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';
  /** Hint for virtual keyboard type */
  @Input() inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';
  /** Turns autocorrect on or off; the browser decides when unset */
  @Input() autocorrect?: boolean;
  /** Turns spell checking on or off; on when unset */
  @Input() spellcheck?: boolean;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() create = new EventEmitter<WaCreateEvent>();
  @Output() clear = new EventEmitter<WaClearEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleCreate = (e: Event) => this.create.emit(e as WaCreateEvent);
    el.addEventListener('wa-create', handleCreate);
    this.cleanups.push(() => el.removeEventListener('wa-create', handleCreate));
    const handleClear = (e: Event) => this.clear.emit(e as WaClearEvent);
    el.addEventListener('wa-clear', handleClear);
    this.cleanups.push(() => el.removeEventListener('wa-clear', handleClear));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// docs/src/components/ui/TagInput/TagInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaTagInput from '@awesome.me/webawesome-pro/dist/components/tag-input/tag-input.js';
import '@awesome.me/webawesome-pro/dist/components/tag-input/tag-input.js';
import './TagInput.css';
import type { WaClearEvent } from '@awesome.me/webawesome-pro/dist/events/clear.js';
import type { WaCreateEvent } from '@awesome.me/webawesome-pro/dist/events/create.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Write a boolean as the keyword an enumerated attribute expects ("on"/"off",
 * "true"/"false"), or remove the attribute when the prop is unset so the
 * element keeps its own default. Web Awesome reads these by value, not
 * presence, and React would write a DOM property or a bare attribute.
 */
function setEnumeratedAttribute(
  el: Pick<Element, 'setAttribute' | 'removeAttribute'>,
  name: string,
  value: boolean | undefined,
  keywords: { true: string; false: string }
): void {
  if (value === undefined) el.removeAttribute(name);
  else el.setAttribute(name, value ? keywords.true : keywords.false);
}

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome-pro/dist/components/tag-input/tag-input.js'));
}

/**
 * Tag inputs collect a list of short values, such as keywords or labels, as removable tags
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TagInput />
 *
 * // With event handlers
 * <TagInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TagInputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <TagInput ref={ref} />
 * ```
 */
export interface TagInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onBlur'
  | 'onFocus'
  | 'onCreate'
  | 'onClear'
  | 'onInvalid'
  | 'dir'
> {
  /** The tag input's label */
  label?: string;

  /** The tag input's hint */
  hint?: string;

  /** Default value as a delimiter-separated string */
  value?: string;

  /** Placeholder text shown in the text box */
  placeholder?: string;

  /** Characters that turn typed text into a tag */
  delimiter?: string;

  /** The maximum number of tags that can be added */
  'max-tags'?: number;

  /** The minimum number of tags required for the control to be valid */
  'min-tags'?: number;

  /** Allows the same tag to be added more than once */
  'allow-duplicates'?: boolean;

  /** Adds a clear button that removes all tags */
  'with-clear'?: boolean;

  /** Visual appearance */
  appearance?: 'filled' | 'outlined' | 'filled-outlined';

  /** The tag input's size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Draws a pill-style tag input with rounded edges */
  pill?: boolean;

  /** Requires at least one tag */
  required?: boolean;

  /** Makes the tag input readonly */
  readonly?: boolean;

  /** Disables the form control */
  disabled?: boolean;

  /** The name of the input, submitted with form data */
  name?: string;

  /** Turns autocorrect on or off; the browser decides when unset */
  autocorrect?: boolean;

  /** Turns spell checking on or off; on when unset */
  spellcheck?: boolean;

  /** Hint for browser autofill */
  autocomplete?: string;

  /** Controls automatic capitalization */
  autocapitalize?: 'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';

  /** Hint for Enter key label on virtual keyboards */
  enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';

  /** Hint for virtual keyboard type */
  inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the user types in the text box or when a tag is added or removed. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when a tag is added, removed, or all tags are cleared by the user. */
  onChange?: (event: Event) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted before typed text becomes a tag. Call `event.preventDefault()` to reject it. The event `detail` contains `{ inputValue: string }`, the text that would become the tag. */
  onCreate?: (event: WaCreateEvent) => void;

  /** Emitted when the clear button is activated. */
  onClear?: (event: WaClearEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface TagInputRef {
  /** Sets focus on the text box. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the text box. */
  blur: () => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaTagInput | null;
}

export const TagInput = forwardRef<TagInputRef, TagInputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onBlur,
      onFocus,
      onCreate,
      onClear,
      onInvalid,
      autocorrect,
      spellcheck,
      ...props
    },
    ref
  ) => {
    const taginputRef = useRef<WaTagInput | null>(null);
    const setTagInputRef = useCallback((el: WaTagInput | null) => {
      taginputRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            taginputRef.current &&
            typeof taginputRef.current.focus === 'function'
          ) {
            taginputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            taginputRef.current &&
            typeof taginputRef.current.blur === 'function'
          ) {
            taginputRef.current.blur();
          }
        },
        setCustomValidity: (message: string) => {
          if (
            taginputRef.current &&
            typeof taginputRef.current.setCustomValidity === 'function'
          ) {
            taginputRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            taginputRef.current &&
            typeof taginputRef.current.formStateRestoreCallback === 'function'
          ) {
            taginputRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            taginputRef.current &&
            typeof taginputRef.current.resetValidity === 'function'
          ) {
            taginputRef.current.resetValidity();
          }
        },
        get element() {
          return taginputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = taginputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as Event);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleWaCreate = (e: Event) => {
        if (onCreate) onCreate(e as WaCreateEvent);
      };

      const handleWaClear = (e: Event) => {
        if (onClear) onClear(e as WaClearEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-create', handleWaCreate);
      el.addEventListener('wa-clear', handleWaClear);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-create', handleWaCreate);
        el.removeEventListener('wa-clear', handleWaClear);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onInput, onChange, onBlur, onFocus, onCreate, onClear, onInvalid]);

    useEffect(() => {
      const el = taginputRef.current;
      if (!el) return;
      setEnumeratedAttribute(el, 'autocorrect', autocorrect, {
        true: 'on',
        false: 'off',
      });
      setEnumeratedAttribute(el, 'spellcheck', spellcheck, {
        true: 'true',
        false: 'false',
      });
    }, [autocorrect, spellcheck]);

    return (
      <wa-tag-input
        ref={setTagInputRef}
        class={clsx('TagInput', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-tag-input>
    );
  }
);

TagInput.displayName = 'TagInput';
