// templates/vue/Spinner/Spinner.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Spinner.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/spinner/spinner.js'));
}

/**
 * Spinners are used to show the progress of an indeterminate operation
 */
export interface SpinnerProps {

}

const props = defineProps<SpinnerProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-spinner
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-spinner>
</template>

// docs/.kigumi/snapshots/Spinner/Spinner.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/spinner/spinner.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/spinner/spinner.js';
import './Spinner.css';

/**
 * Spinners are used to show the progress of an indeterminate operation
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Spinner />
 *
 * // With event handlers
 * <Spinner />
 *
 * ```
 */
export type SpinnerProps = Omit<HTMLAttributes<HTMLElement>, 'dir'>;

export interface SpinnerRef {
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Spinner = forwardRef<SpinnerRef, SpinnerProps>(
  ({ children, className, ...props }, ref) => {
    const spinnerRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return spinnerRef.current;
        },
      }),
      []
    );

    return (
      <wa-spinner
        ref={(el: WaElement | null) => {
          spinnerRef.current = el;
        }}
        class={clsx('Spinner', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-spinner>
    );
  }
);

Spinner.displayName = 'Spinner';
