// docs/src/components/ui/ResizeObserver/ResizeObserver.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/resize-observer/resize-observer.js';
import './ResizeObserver.css';

/**
 * Reports changes to the dimensions of an element
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ResizeObserver />
 *
 * // With event handlers
 * <ResizeObserver
 *   onResize={(e) => console.log(e)} />
 *
 * ```
 */
export interface ResizeObserverProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onResize' | 'dir'
> {
  /** Disables the observer */
  disabled?: boolean;

  /** Emitted when the element is resized. */
  onResize?: (event: CustomEvent) => void;
}

export interface ResizeObserverRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const ResizeObserver = forwardRef<
  ResizeObserverRef,
  ResizeObserverProps
>(({ children, className, onResize, ...props }, ref) => {
  const resizeobserverRef = useRef<HTMLElement & {}>(null);

  useImperativeHandle(
    ref,
    () => ({
      get element() {
        return resizeobserverRef.current;
      },
    }),
    []
  );

  useEffect(() => {
    const el = resizeobserverRef.current;
    if (!el) return;

    const handleResize = (e: Event) => {
      if (onResize) onResize(e as CustomEvent);
    };

    el.addEventListener('wa-resize', handleResize);

    return () => {
      el.removeEventListener('wa-resize', handleResize);
    };
  }, [onResize]);

  return (
    <wa-resize-observer
      ref={resizeobserverRef}
      class={clsx('ResizeObserver', className)}
      {...(props as Record<string, unknown>)}
    >
      {children}
    </wa-resize-observer>
  );
});

ResizeObserver.displayName = 'ResizeObserver';

// templates/vue/ResizeObserver/ResizeObserver.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './ResizeObserver.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/resize-observer/resize-observer.js'));
}

/**
 * Reports changes to the dimensions of an element
 */
export interface ResizeObserverProps {
  disabled?: boolean;
}

const props = defineProps<ResizeObserverProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-resize': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaResize = (e: Event) => emit('wa-resize', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-resize', handleWaResize);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-resize', handleWaResize);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-resize-observer
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-resize-observer>
</template>
