// templates/react/RelativeTime/RelativeTime.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './RelativeTime.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/relative-time/relative-time.js'));
}

/**
 * Outputs a localized time phrase relative to the current date and time
 *
 * @example
 * ```tsx
 * // Basic usage
 * <RelativeTime />
 *
 * // With event handlers
 * <RelativeTime />
 *
 * ```
 */
export interface RelativeTimeProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The date/time to calculate from */
  date?: string;

  /** The formatting style */
  format?: 'long' | 'short' | 'narrow';

  /** When to use numeric values */
  numeric?: 'always' | 'auto';

  /** Keeps time in sync */
  sync?: boolean;

  /** The locale to use */
  lang?: string;
}

export interface RelativeTimeRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const RelativeTime = forwardRef<RelativeTimeRef, RelativeTimeProps>(
  ({ children, className, ...props }, ref) => {
    const relativetimeRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return relativetimeRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-relative-time
        ref={relativetimeRef}
        class={clsx('RelativeTime', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-relative-time>
    );
  }
);

RelativeTime.displayName = 'RelativeTime';

// templates/vue/RelativeTime/RelativeTime.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './RelativeTime.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/relative-time/relative-time.js'));
}

/**
 * Outputs a localized time phrase relative to the current date and time
 */
export interface RelativeTimeProps {
  date?: string;
  format?: 'long' | 'short' | 'narrow';
  numeric?: 'always' | 'auto';
  sync?: boolean;
  lang?: string;
}

const props = defineProps<RelativeTimeProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-relative-time
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-relative-time>
</template>
