// templates/react/Textarea/Textarea.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaTextarea from '@awesome.me/webawesome/dist/components/textarea/textarea.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import './Textarea.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/textarea/textarea.js'));
}

/**
 * Write a boolean as the keyword an enumerated attribute expects ("on"/"off",
 * "true"/"false"), or remove the attribute when the prop is unset so the
 * element keeps its own default.
 */
function setEnumeratedAttribute(
  el: Pick<Element, 'setAttribute' | 'removeAttribute'>,
  name: string,
  value: boolean | undefined,
  keywords: { true: string; false: string }
): void {
  if (value === undefined) el.removeAttribute(name);
  else el.setAttribute(name, value ? keywords.true : keywords.false);
}

/**
 * Textareas collect multi-line text data from the user
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Textarea />
 *
 * // With event handlers
 * <Textarea
 *   onBlur={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TextareaRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <Textarea ref={ref} />
 * ```
 */
export interface TextareaProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onBlur' | 'onChange' | 'onFocus' | 'onInput' | 'onInvalid' | 'dir'
> {
  /** Form field name */
  name?: string;

  /** Current value */
  value?: string;

  /** Visual appearance */
  appearance?: 'filled' | 'outlined' | 'filled-outlined';

  /** Textarea size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Label text */
  label?: string;

  /** Hint text */
  hint?: string;

  /** Placeholder text */
  placeholder?: string;

  /** Visible rows */
  rows?: number;

  /** Resize behavior */
  resize?: 'none' | 'vertical' | 'horizontal' | 'both' | 'auto';

  /** Disables the textarea */
  disabled?: boolean;

  /** Makes it readonly */
  readonly?: boolean;

  /** Makes it required */
  required?: boolean;

  /** Minimum length */
  minlength?: number;

  /** Maximum length */
  maxlength?: number;

  /** Turns spell checking on or off; on when unset */
  spellcheck?: boolean;

  /** Shows a character count when maxlength is set */
  'with-count'?: boolean;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** Hint for browser autofill */
  autocomplete?: string;

  /** Controls automatic capitalization */
  autocapitalize?: 'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';

  /** Focuses the control on page load */
  autofocus?: boolean;

  /** Hint for Enter key label on virtual keyboards */
  enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';

  /** Hint for virtual keyboard type */
  inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';

  /** Turns autocorrect on or off; the browser decides when unset */
  autocorrect?: boolean;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when an alteration to the control's value is committed by the user. */
  onChange?: (event: Event) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the control receives input. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface TextareaRef {
  /** Sets focus on the textarea. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the textarea. */
  blur: () => void;

  /** Selects all the text in the textarea. */
  select: () => void;

  /** Gets or sets the textarea's scroll position. */
  scrollPosition: (position: { top?: number; left?: number }) => void;

  /** Sets the start and end positions of the text selection (0-based). */
  setSelectionRange: (
    selectionStart: number,
    selectionEnd: number,
    selectionDirection: 'forward' | 'backward' | 'none'
  ) => void;

  /** Replaces a range of text with a new string. */
  setRangeText: (
    replacement: string,
    start: number,
    end: number,
    selectMode: 'select' | 'start' | 'end' | 'preserve'
  ) => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaTextarea | null;
}

export const Textarea = forwardRef<TextareaRef, TextareaProps>(
  (
    {
      children,
      className,
      onBlur,
      onChange,
      onFocus,
      onInput,
      onInvalid,
      spellcheck,
      autocorrect,
      ...props
    },
    ref
  ) => {
    const textareaRef = useRef<WaTextarea | null>(null);
    const setTextareaRef = useCallback((el: WaTextarea | null) => {
      textareaRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.focus === 'function'
          ) {
            textareaRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.blur === 'function'
          ) {
            textareaRef.current.blur();
          }
        },
        select: () => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.select === 'function'
          ) {
            textareaRef.current.select();
          }
        },
        scrollPosition: (position: { top?: number; left?: number }) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.scrollPosition === 'function'
          ) {
            textareaRef.current.scrollPosition(position);
          }
        },
        setSelectionRange: (
          selectionStart: number,
          selectionEnd: number,
          selectionDirection: 'forward' | 'backward' | 'none'
        ) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.setSelectionRange === 'function'
          ) {
            textareaRef.current.setSelectionRange(
              selectionStart,
              selectionEnd,
              selectionDirection
            );
          }
        },
        setRangeText: (
          replacement: string,
          start: number,
          end: number,
          selectMode: 'select' | 'start' | 'end' | 'preserve'
        ) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.setRangeText === 'function'
          ) {
            textareaRef.current.setRangeText(
              replacement,
              start,
              end,
              selectMode
            );
          }
        },
        setCustomValidity: (message: string) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.setCustomValidity === 'function'
          ) {
            textareaRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.formStateRestoreCallback === 'function'
          ) {
            textareaRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            textareaRef.current &&
            typeof textareaRef.current.resetValidity === 'function'
          ) {
            textareaRef.current.resetValidity();
          }
        },
        get element() {
          return textareaRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = textareaRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('change', handleChange);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('input', handleInput);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('input', handleInput);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onBlur, onChange, onFocus, onInput, onInvalid]);

    useEffect(() => {
      const el = textareaRef.current;
      if (!el) return;
      setEnumeratedAttribute(el, 'spellcheck', spellcheck, {
        true: 'true',
        false: 'false',
      });
      setEnumeratedAttribute(el, 'autocorrect', autocorrect, {
        true: 'on',
        false: 'off',
      });
    }, [spellcheck, autocorrect]);

    return (
      <wa-textarea
        ref={setTextareaRef}
        class={clsx('Textarea', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-textarea>
    );
  }
);

Textarea.displayName = 'Textarea';

// templates/angular/Textarea/textarea.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/textarea/textarea.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/textarea/textarea.js'));
}

/**
 * Textareas collect multi-line text data from the user
 *
 * @see https://webawesome.com/docs/components/textarea
 */
@Component({
  selector: 'k-textarea',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-textarea
      #element
      [attr.name]="name"
      [attr.value]="value"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.placeholder]="placeholder"
      [attr.rows]="rows"
      [attr.resize]="resize"
      [attr.disabled]="disabled || null"
      [attr.readonly]="readonly || null"
      [attr.required]="required || null"
      [attr.minlength]="minlength"
      [attr.maxlength]="maxlength"
      [attr.spellcheck]="
        spellcheck == null ? null : spellcheck ? 'true' : 'false'
      "
      [attr.with-count]="withCount || null"
      [attr.title]="title"
      [attr.autocomplete]="autocomplete"
      [attr.autocapitalize]="autocapitalize"
      [attr.autofocus]="autofocus || null"
      [attr.enterkeyhint]="enterkeyhint"
      [attr.inputmode]="inputmode"
      [attr.autocorrect]="
        autocorrect == null ? null : autocorrect ? 'on' : 'off'
      "
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-textarea>
  `,
  styleUrl: './textarea.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TextareaComponent),
      multi: true,
    },
  ],
})
export class TextareaComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Form field name */
  @Input() name?: string;
  /** Current value */
  @Input() value?: string;
  /** Visual appearance */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** Textarea size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Label text */
  @Input() label?: string;
  /** Hint text */
  @Input() hint?: string;
  /** Placeholder text */
  @Input() placeholder?: string;
  /** Visible rows */
  @Input() rows?: number;
  /** Resize behavior */
  @Input() resize?: 'none' | 'vertical' | 'horizontal' | 'both' | 'auto';
  /** Disables the textarea */
  @Input() disabled?: boolean;
  /** Makes it readonly */
  @Input() readonly?: boolean;
  /** Makes it required */
  @Input() required?: boolean;
  /** Minimum length */
  @Input() minlength?: number;
  /** Maximum length */
  @Input() maxlength?: number;
  /** Turns spell checking on or off; on when unset */
  @Input() spellcheck?: boolean;
  /** Shows a character count when maxlength is set */
  @Input() withCount?: boolean;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Controls automatic capitalization */
  @Input() autocapitalize?:
    'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters';
  /** Focuses the control on page load */
  @Input() autofocus?: boolean;
  /** Hint for Enter key label on virtual keyboards */
  @Input() enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';
  /** Hint for virtual keyboard type */
  @Input() inputmode?:
    | 'none'
    | 'text'
    | 'decimal'
    | 'numeric'
    | 'tel'
    | 'search'
    | 'email'
    | 'url';
  /** Turns autocorrect on or off; the browser decides when unset */
  @Input() autocorrect?: boolean;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  select(): void {
    (
      this.elementRef.nativeElement as unknown as { select: () => void }
    ).select();
  }
  scrollPosition(position?: { top?: number; left?: number }): void {
    (
      this.elementRef.nativeElement as unknown as {
        scrollPosition: (position?: { top?: number; left?: number }) => void;
      }
    ).scrollPosition(position);
  }
  setSelectionRange(
    selectionStart: number,
    selectionEnd: number,
    selectionDirection?: 'forward' | 'backward' | 'none'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        setSelectionRange: (
          selectionStart: number,
          selectionEnd: number,
          selectionDirection?: 'forward' | 'backward' | 'none'
        ) => void;
      }
    ).setSelectionRange(selectionStart, selectionEnd, selectionDirection);
  }
  setRangeText(
    replacement: string,
    start?: number,
    end?: number,
    selectMode?: 'select' | 'start' | 'end' | 'preserve'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        setRangeText: (
          replacement: string,
          start?: number,
          end?: number,
          selectMode?: 'select' | 'start' | 'end' | 'preserve'
        ) => void;
      }
    ).setRangeText(replacement, start, end, selectMode);
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
