// templates/vue/Radio/Radio.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Radio.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/radio/radio.js'));
}

/**
 * Radios allow the user to select a single option from a group
 */
export interface RadioProps {
  value?: string;
  disabled?: boolean;
  size?: 'small' | 'medium' | 'large';
  appearance?: 'default' | 'button';
}

const props = defineProps<RadioProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'blur': [event: CustomEvent];
  'focus': [event: FocusEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleBlur = (e: Event) => emit('blur', e as CustomEvent);
const handleFocus = (e: Event) => emit('focus', e as FocusEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('blur', handleBlur);
  el.addEventListener('focus', handleFocus);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('blur', handleBlur);
  el.removeEventListener('focus', handleFocus);
});

defineExpose({
  setCustomValidity: (message: string) => (elementRef.value as any)?.setCustomValidity?.(message),
  formStateRestoreCallback: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => (elementRef.value as any)?.formStateRestoreCallback?.(state, reason),
  resetValidity: () => (elementRef.value as any)?.resetValidity?.(),
  element: elementRef,
});
</script>

<template>
  <wa-radio
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-radio>
</template>

// templates/react/Radio/Radio.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Radio.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/radio/radio.js'));
}

/**
 * Radios allow the user to select a single option from a group
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Radio />
 *
 * // With event handlers
 * <Radio
 *   onBlur={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<RadioRef>(null);
 * <button onClick={() => ref.current?.setCustomValidity()}>Call Method</button>
 * <Radio ref={ref} />
 * ```
 */
export interface RadioProps extends Omit<HTMLAttributes<HTMLElement>, 'onBlur' | 'onFocus' | 'dir'> {

  /** The radio value */
  value?: string;

  /** Disables the radio */
  disabled?: boolean;

  /** Radio size */
  size?: 'small' | 'medium' | 'large';

  /** Radio appearance style */
  appearance?: 'default' | 'button';

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;
}

export interface RadioRef {

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Radio = forwardRef<RadioRef, RadioProps>(
  ({ children, className, onBlur, onFocus, ...props }, ref) => {
    const radioRef = useRef<HTMLElement & {
      setCustomValidity?: (message: string) => void;
      formStateRestoreCallback?: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => void;
      resetValidity?: () => void;
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        setCustomValidity: (message: string) => {
          if (radioRef.current && typeof radioRef.current.setCustomValidity === 'function') {
            radioRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => {
          if (radioRef.current && typeof radioRef.current.formStateRestoreCallback === 'function') {
            radioRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (radioRef.current && typeof radioRef.current.resetValidity === 'function') {
            radioRef.current.resetValidity();
          }
        },
        get element() {
          return radioRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = radioRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
      };
    }, [onBlur, onFocus]);

    return (
      <wa-radio
        ref={radioRef}
        class={clsx('Radio', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-radio>
    );
  }
);

Radio.displayName = 'Radio';
