// templates/vue/Tree/Tree.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Tree.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tree/tree.js'));
}

/**
 * Trees allow you to display a hierarchical list of selectable tree items
 */
export interface TreeProps {
  selection?: 'single' | 'multiple' | 'leaf';
}

const props = defineProps<TreeProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-selection-change': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaSelectionChange = (e: Event) => emit('wa-selection-change', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-selection-change', handleWaSelectionChange);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-selection-change', handleWaSelectionChange);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-tree
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tree>
</template>

// templates/react/Tree/Tree.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Tree.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tree/tree.js'));
}

/**
 * Trees allow you to display a hierarchical list of selectable tree items
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Tree />
 *
 * // With event handlers
 * <Tree
 *   onSelectionChange={(e) => console.log(e)} />
 *
 * ```
 */
export interface TreeProps extends Omit<HTMLAttributes<HTMLElement>, 'onSelectionChange' | 'dir'> {

  /** Selection behavior */
  selection?: 'single' | 'multiple' | 'leaf';

  /** Emitted when a tree item is selected or deselected. */
  onSelectionChange?: (event: CustomEvent) => void;
}

export interface TreeRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Tree = forwardRef<TreeRef, TreeProps>(
  ({ children, className, onSelectionChange, ...props }, ref) => {
    const treeRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return treeRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = treeRef.current;
      if (!el) return;

      const handleWaSelectionChange = (e: Event) => {
        if (onSelectionChange) onSelectionChange(e as CustomEvent);
      };

      el.addEventListener('wa-selection-change', handleWaSelectionChange);

      return () => {
        el.removeEventListener('wa-selection-change', handleWaSelectionChange);
      };
    }, [onSelectionChange]);

    return (
      <wa-tree
        ref={treeRef}
        class={clsx('Tree', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tree>
    );
  }
);

Tree.displayName = 'Tree';
