// templates/vue/Avatar/Avatar.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Avatar.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/avatar/avatar.js'));
}

/**
 * Avatars are used to represent a person or object
 */
export interface AvatarProps {
  image?: string;
  label: string;
  initials?: string;
  loading?: 'eager' | 'lazy';
  shape?: 'circle' | 'square' | 'rounded';
}

const props = defineProps<AvatarProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-error': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaError = (e: Event) => emit('wa-error', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-error', handleWaError);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-error', handleWaError);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-avatar
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-avatar>
</template>

// docs/src/components/ui/Avatar/Avatar.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/avatar/avatar.js';
import './Avatar.css';

/**
 * Avatars are used to represent a person or object
 *
 * @example
 * ```tsx
 * // With image
 * <Avatar image="https://example.com/avatar.jpg" label="User avatar" />
 *
 * // With initials
 * <Avatar initials="JD" label="John Doe" />
 *
 * // With custom icon
 * <Avatar label="Settings">
 *   <wa-icon slot="icon" name="gear" />
 * </Avatar>
 * ```
 */
export interface AvatarProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onError' | 'dir'
> {
  /** The image source to use for the avatar */
  image?: string;
  /** A label to use to describe the avatar to assistive devices */
  label: string;
  /** Initials to use as a fallback when no image is available */
  initials?: string;
  /** Indicates how the browser should load the image */
  loading?: 'eager' | 'lazy';
  /** The shape of the avatar */
  shape?: 'circle' | 'square' | 'rounded';
  /** Event fired when the image could not be loaded */
  onError?: (event: CustomEvent) => void;
}

export const Avatar = forwardRef<HTMLElement, AvatarProps>(
  ({ children, className, onError, ...props }, ref) => {
    const elementRef = useRef<HTMLElement>(null);

    useImperativeHandle(ref, () => elementRef.current as HTMLElement, []);

    useEffect(() => {
      const el = elementRef.current;
      if (!el || !onError) return;

      const handleError = (e: Event) => {
        onError(e as CustomEvent);
      };

      el.addEventListener('wa-error', handleError);

      return () => {
        el.removeEventListener('wa-error', handleError);
      };
    }, [onError]);

    return (
      <wa-avatar
        ref={elementRef}
        class={clsx('Avatar', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-avatar>
    );
  }
);

Avatar.displayName = 'Avatar';
