// templates/react/MutationObserver/MutationObserver.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './MutationObserver.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/mutation-observer/mutation-observer.js'));
}

/**
 * Observes changes to a target element and emits events when they occur
 *
 * @example
 * ```tsx
 * // Basic usage
 * <MutationObserver />
 *
 * // With event handlers
 * <MutationObserver
 *   onMutation={(e) => console.log(e)} />
 *
 * ```
 */
export interface MutationObserverProps extends Omit<HTMLAttributes<HTMLElement>, 'onMutation' | 'dir'> {

  /** Space-separated list of attributes to observe */
  attr?: string;

  /** Records previous attribute values */
  'attr-old-value'?: boolean;

  /** Observes character data changes */
  'char-data'?: boolean;

  /** Records previous character data */
  'char-data-old-value'?: boolean;

  /** Observes child node changes */
  'child-list'?: boolean;

  /** Disables the observer */
  disabled?: boolean;

  /** Observes changes in subtree */
  subtree?: boolean;

  /** Emitted when a mutation occurs. */
  onMutation?: (event: CustomEvent) => void;
}

export interface MutationObserverRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const MutationObserver = forwardRef<MutationObserverRef, MutationObserverProps>(
  ({ children, className, onMutation, ...props }, ref) => {
    const mutationobserverRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return mutationobserverRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = mutationobserverRef.current;
      if (!el) return;

      const handleWaMutation = (e: Event) => {
        if (onMutation) onMutation(e as CustomEvent);
      };

      el.addEventListener('wa-mutation', handleWaMutation);

      return () => {
        el.removeEventListener('wa-mutation', handleWaMutation);
      };
    }, [onMutation]);

    return (
      <wa-mutation-observer
        ref={mutationobserverRef}
        class={clsx('MutationObserver', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-mutation-observer>
    );
  }
);

MutationObserver.displayName = 'MutationObserver';

// templates/vue/MutationObserver/MutationObserver.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './MutationObserver.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/mutation-observer/mutation-observer.js'));
}

/**
 * Observes changes to a target element and emits events when they occur
 */
export interface MutationObserverProps {
  attr?: string;
  'attr-old-value'?: boolean;
  'char-data'?: boolean;
  'char-data-old-value'?: boolean;
  'child-list'?: boolean;
  disabled?: boolean;
  subtree?: boolean;
}

const props = defineProps<MutationObserverProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-mutation': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaMutation = (e: Event) => emit('wa-mutation', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-mutation', handleWaMutation);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-mutation', handleWaMutation);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-mutation-observer
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-mutation-observer>
</template>
