// templates/angular/KnownDate/known-date.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/known-date/known-date.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/known-date/known-date.js'));
}

/**
 * Known dates collect a calendar date the user already knows, such as a birthday
 *
 * @see https://webawesome.com/docs/components/known-date
 */
@Component({
  selector: 'k-known-date',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-known-date
      #element
      [attr.name]="name"
      [attr.value]="value"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.readonly]="readonly || null"
      [attr.size]="size"
      [attr.appearance]="appearance"
      [attr.pill]="pill || null"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.min]="min"
      [attr.max]="max"
      [attr.locale]="locale"
      [attr.autocomplete]="autocomplete"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-known-date>
  `,
  styleUrl: './known-date.component.css',
})
export class KnownDateComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** The current value as a `YYYY-MM-DD` string */
  @Input() value?: string;
  /** Whether the control is disabled */
  @Input() disabled?: boolean;
  /** Whether a value is required before form submission */
  @Input() required?: boolean;
  /** Whether the control is read-only */
  @Input() readonly?: boolean;
  /** Controls the overall dimensions of the control */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** The visual style of the control */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** Draws the control with rounded edges */
  @Input() pill?: boolean;
  /** The control label. Use the `label` slot for rich labels. */
  @Input() label?: string;
  /** Help text shown below the control. Use the `hint` slot for rich hints. */
  @Input() hint?: string;
  /** The earliest acceptable date */
  @Input() min?: string;
  /** The latest acceptable date */
  @Input() max?: string;
  /** The locale used to format and parse the date */
  @Input() locale?: string;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as CustomEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  formStateRestoreCallback(state?: string | File | FormData | null): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null
        ) => void;
      }
    ).formStateRestoreCallback(state);
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// templates/react/KnownDate/KnownDate.jsx
import React from 'react';
import clsx from 'clsx';
import './KnownDate.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/known-date/known-date.js'));
}

/**
 * Known dates collect a calendar date the user already knows, such as a birthday
 *
 * @example
 * ```jsx
 * // Basic usage
 * <KnownDate />
 *
 * // With event handlers
 * <KnownDate onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = React.useRef(null);
 * <button onClick={() => ref.current?.focus()}>Focus</button>
 * <KnownDate ref={ref} />
 * ```
 *
 * @param {Object} props
 * @param {string} [props.name] - The name of the control, submitted with form data
 * @param {string} [props.value] - The current value as a `YYYY-MM-DD` string
 * @param {boolean} [props.disabled] - Whether the control is disabled
 * @param {boolean} [props.required] - Whether a value is required before form submission
 * @param {boolean} [props.readonly] - Whether the control is read-only
 * @param {'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl'} [props.size] - Controls the overall dimensions of the control
 * @param {'filled' | 'outlined' | 'filled-outlined'} [props.appearance] - The visual style of the control
 * @param {boolean} [props.pill] - Draws the control with rounded edges
 * @param {string} [props.label] - The control label. Use the `label` slot for rich labels.
 * @param {string} [props.hint] - Help text shown below the control. Use the `hint` slot for rich hints.
 * @param {string} [props.min] - The earliest acceptable date
 * @param {string} [props.max] - The latest acceptable date
 * @param {string} [props.locale] - The locale used to format and parse the date
 * @param {string} [props.autocomplete] - Hint for browser autofill
 * @param {string} [props['custom-error']] - Custom validation message; the control is invalid while it is set
 * @param {function} [props.onInput] - Emitted as the user types in any field.
 * @param {function} [props.onChange] - Emitted when the committed value transitions to a new ISO date.
 * @param {function} [props.onBlur] - Emitted when the control loses focus.
 * @param {function} [props.onFocus] - Emitted when the control gains focus.
 * @param {function} [props.onInvalid] - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
 * @param {string} [props.className] - Additional CSS classes
 * @param {React.ReactNode} [props.children] - Slotted content
 * @param {React.Ref} ref - Ref with methods: focus(options), blur(), formStateRestoreCallback(state), setCustomValidity(message), resetValidity()
 */
export const KnownDate = React.forwardRef(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onBlur,
      onFocus,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const knowndateRef = React.useRef(null);
    const setKnownDateRef = React.useCallback((el) => {
      knowndateRef.current = el;
    }, []);

    React.useImperativeHandle(
      ref,
      () => ({
        focus: (options) => {
          if (
            knowndateRef.current &&
            typeof knowndateRef.current.focus === 'function'
          ) {
            knowndateRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            knowndateRef.current &&
            typeof knowndateRef.current.blur === 'function'
          ) {
            knowndateRef.current.blur();
          }
        },
        formStateRestoreCallback: (state) => {
          if (
            knowndateRef.current &&
            typeof knowndateRef.current.formStateRestoreCallback === 'function'
          ) {
            knowndateRef.current.formStateRestoreCallback(state);
          }
        },
        setCustomValidity: (message) => {
          if (
            knowndateRef.current &&
            typeof knowndateRef.current.setCustomValidity === 'function'
          ) {
            knowndateRef.current.setCustomValidity(message);
          }
        },
        resetValidity: () => {
          if (
            knowndateRef.current &&
            typeof knowndateRef.current.resetValidity === 'function'
          ) {
            knowndateRef.current.resetValidity();
          }
        },
        get element() {
          return knowndateRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = knowndateRef.current;
      if (!el) return;

      const handleInput = (e) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e) => {
        if (onChange) onChange(e);
      };

      const handleBlur = (e) => {
        if (onBlur) onBlur(e);
      };

      const handleFocus = (e) => {
        if (onFocus) onFocus(e);
      };

      const handleWaInvalid = (e) => {
        if (onInvalid) onInvalid(e);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onInput, onChange, onBlur, onFocus, onInvalid]);

    return (
      <wa-known-date
        ref={setKnownDateRef}
        class={clsx('KnownDate', className)}
        {...{ suppressHydrationWarning: true, ...props }}
      >
        {children}
      </wa-known-date>
    );
  }
);

KnownDate.displayName = 'KnownDate';
