// templates/angular/Button/button.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/button/button.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/button/button.js'));
}

/**
 * Buttons represent actions that are available to the user
 *
 * @see https://webawesome.com/docs/components/button
 */
@Component({
  selector: 'k-button',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-button
      #element
      [attr.variant]="variant"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.pill]="pill || null"
      [attr.disabled]="disabled || null"
      [attr.loading]="loading || null"
      [attr.with-caret]="withCaret || null"
      [attr.href]="href"
      [attr.target]="target"
      [attr.download]="download"
      [attr.rel]="rel"
      [attr.type]="type"
      [attr.name]="name"
      [attr.value]="value"
      [attr.formaction]="formaction"
      [attr.formenctype]="formenctype"
      [attr.formmethod]="formmethod"
      [attr.formnovalidate]="formnovalidate || null"
      [attr.formtarget]="formtarget"
      [attr.title]="title"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-button>
  `,
  styleUrl: './button.component.css',
})
export class ButtonComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Semantic variant of the button */
  @Input() variant?: 'neutral' | 'brand' | 'success' | 'warning' | 'danger';
  /** Visual appearance style */
  @Input() appearance?:
    'accent' | 'filled-outlined' | 'filled' | 'outlined' | 'plain';
  /** Button size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Gives the button rounded edges */
  @Input() pill?: boolean;
  /** Disables the button */
  @Input() disabled?: boolean;
  /** Shows a loading indicator */
  @Input() loading?: boolean;
  /** Adds a dropdown indicator caret */
  @Input() withCaret?: boolean;
  /** Makes the button work like a link */
  @Input() href?: string;
  /** Link target (when href is set) */
  @Input() target?: '_blank' | '_self' | '_parent' | '_top';
  /** Download filename (when href is set) */
  @Input() download?: string;
  /** Link relationship (when href is set) */
  @Input() rel?: string;
  /** The button's type for form submission */
  @Input() type?: 'button' | 'submit' | 'reset';
  /** The name of the button for form submission */
  @Input() name?: string;
  /** The value of the button for form submission */
  @Input() value?: string;
  /** Override the form's action attribute */
  @Input() formaction?: string;
  /** Override the form's enctype attribute */
  @Input() formenctype?: string;
  /** Override the form's method attribute */
  @Input() formmethod?: string;
  /** Bypass form validation when this button submits */
  @Input() formnovalidate?: boolean;
  /** Override the form's target attribute */
  @Input() formtarget?: string;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as CustomEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  click(): void {
    (this.elementRef.nativeElement as unknown as { click: () => void }).click();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// templates/react/Button/Button.jsx
import React from 'react';
import clsx from 'clsx';
import './Button.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/button/button.js'));
}

/**
 * Buttons represent actions that are available to the user
 *
 * @example
 * ```jsx
 * <Button variant="brand">Click me</Button>
 * <Button appearance="outlined" size="large">Large Button</Button>
 * <Button loading>Loading...</Button>
 * <Button type="submit" form="myForm">Submit</Button>
 *
 * // With event handlers
 * <Button onBlur={() => console.log('Lost focus')}>
 *   Button
 * </Button>
 *
 * // With ref methods
 * const buttonRef = React.useRef(null);
 * <button onClick={() => buttonRef.current?.focus()}>Focus Button</button>
 * <Button ref={buttonRef}>Focusable</Button>
 * ```
 *
 * @typedef {Object} ButtonProps
 * @property {string} [variant] - Semantic variant: neutral | brand | success | warning | danger
 * @property {string} [appearance] - Visual appearance: accent | filled | outlined | filled-outlined | plain
 * @property {string} [size] - Button size: small | medium | large
 * @property {boolean} [pill] - Rounded edges
 * @property {boolean} [disabled] - Disables button
 * @property {boolean} [loading] - Shows loading indicator
 * @property {boolean} [with-caret] - Adds dropdown caret
 * @property {string} [href] - Makes button work like link
 * @property {string} [target] - Link target: _blank | _self | _parent | _top
 * @property {string} [download] - Download filename
 * @property {string} [rel] - Link relationship
 * @property {string} [type] - Button type for form submission: button | submit | reset
 * @property {string} [name] - Name for form submission
 * @property {string} [value] - Value for form submission
 * @property {string} [formaction] - Override form action
 * @property {string} [formenctype] - Override form enctype
 * @property {string} [formmethod] - Override form method
 * @property {boolean} [formnovalidate] - Bypass form validation
 * @property {string} [formtarget] - Override form target
 * @property {string} [title] - Native tooltip text, shown on hover
 * @property {string} [custom-error] - Custom validation message; the control is invalid while it is set
 * @property {function} [onBlur] - Event fired when button loses focus
 * @property {function} [onFocus] - Event fired when button gains focus
 */

export const Button = React.forwardRef(
  ({ children, className, onBlur, onFocus, ...props }, ref) => {
    const buttonRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        focus: () => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.focus === 'function'
          ) {
            buttonRef.current.focus();
          }
        },
        blur: () => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.blur === 'function'
          ) {
            buttonRef.current.blur();
          }
        },
        click: () => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.click === 'function'
          ) {
            buttonRef.current.click();
          }
        },
        get element() {
          return buttonRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = buttonRef.current;
      if (!el) return;

      const handleBlur = (e) => {
        if (onBlur) onBlur(e);
      };

      const handleFocus = (e) => {
        if (onFocus) onFocus(e);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
      };
    }, [onBlur, onFocus]);

    return (
      <wa-button ref={buttonRef} class={clsx('Button', className)} {...props}>
        {children}
      </wa-button>
    );
  }
);

Button.displayName = 'Button';
