// templates/vue/FormatBytes/FormatBytes.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatBytes.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-bytes/format-bytes.js'));
}

/**
 * Formats a number as a human-readable byte value
 */
export interface FormatBytesProps {
  value?: number;
  unit?: 'byte' | 'bit';
  display?: 'long' | 'short' | 'narrow';
  lang?: string;
}

const props = defineProps<FormatBytesProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-bytes
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-bytes>
</template>

// docs/src/components/ui/FormatBytes/FormatBytes.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/format-bytes/format-bytes.js';
import './FormatBytes.css';

export interface FormatBytesProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** The number to format in bytes */
  value: number;
  /** The type of unit to display */
  unit?: 'byte' | 'bit';
  /** Determines how to display the result */
  display?: 'long' | 'short' | 'narrow';
}

export const FormatBytes = forwardRef<HTMLElement, FormatBytesProps>(
  ({ className, ...props }, ref) => {
    return (
      <wa-format-bytes
        ref={ref}
        class={clsx('FormatBytes', className)}
        {...(props as Record<string, unknown>)}
      />
    );
  }
);

FormatBytes.displayName = 'FormatBytes';
