// templates/react/NumberInput/NumberInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaNumberInput from '@awesome.me/webawesome/dist/components/number-input/number-input.js';
import './NumberInput.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/number-input/number-input.js'));
}

/**
 * Number inputs allow users to enter numeric values with optional step controls
 *
 * @example
 * ```tsx
 * // Basic usage
 * <NumberInput />
 *
 * // With event handlers
 * <NumberInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<NumberInputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <NumberInput ref={ref} />
 * ```
 */
export interface NumberInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onBlur'
  | 'onFocus'
  | 'onBeforeinput'
  | 'onInvalid'
  | 'dir'
> {
  /** Accessible label */
  label?: string;

  /** Descriptive hint text */
  hint?: string;

  /** Current value */
  value?: number;

  /** Minimum value */
  min?: number;

  /** Maximum value */
  max?: number;

  /** Step increment */
  step?: number;

  /** Disables the input */
  disabled?: boolean;

  /** Makes field mandatory */
  required?: boolean;

  /** Placeholder text */
  placeholder?: string;

  /** Input size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Visual appearance */
  appearance?: 'filled' | 'outlined' | 'filled-outlined';

  /** Hides the stepper buttons */
  'without-steppers'?: boolean;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** The name of the control, submitted with form data */
  name?: string;

  /** Makes the input readonly */
  readonly?: boolean;

  /** Hint for browser autofill */
  autocomplete?: string;

  /** Focuses the control on page load */
  autofocus?: boolean;

  /** Hint for Enter key label on virtual keyboards */
  enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';

  /** Hint for virtual keyboard type */
  inputmode?: 'numeric' | 'decimal';

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  onInput?: (event: InputEvent) => void;

  onChange?: (event: Event) => void;

  onBlur?: (event: FocusEvent) => void;

  onFocus?: (event: FocusEvent) => void;

  onBeforeinput?: (event: InputEvent) => void;

  onInvalid?: (event: CustomEvent) => void;
}

export interface NumberInputRef {
  focus: (options: FocusOptions) => void;

  blur: () => void;

  select: () => void;

  stepUp: () => void;

  stepDown: () => void;

  setCustomValidity: (message: string) => void;

  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaNumberInput | null;
}

export const NumberInput = forwardRef<NumberInputRef, NumberInputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onBlur,
      onFocus,
      onBeforeinput,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const numberinputRef = useRef<WaNumberInput | null>(null);
    const setNumberInputRef = useCallback((el: WaNumberInput | null) => {
      numberinputRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.focus === 'function'
          ) {
            numberinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.blur === 'function'
          ) {
            numberinputRef.current.blur();
          }
        },
        select: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.select === 'function'
          ) {
            numberinputRef.current.select();
          }
        },
        stepUp: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.stepUp === 'function'
          ) {
            numberinputRef.current.stepUp();
          }
        },
        stepDown: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.stepDown === 'function'
          ) {
            numberinputRef.current.stepDown();
          }
        },
        setCustomValidity: (message: string) => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.setCustomValidity === 'function'
          ) {
            numberinputRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.formStateRestoreCallback ===
              'function'
          ) {
            numberinputRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.resetValidity === 'function'
          ) {
            numberinputRef.current.resetValidity();
          }
        },
        get element() {
          return numberinputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = numberinputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as Event);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleBeforeinput = (e: Event) => {
        if (onBeforeinput) onBeforeinput(e as InputEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as CustomEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('beforeinput', handleBeforeinput);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('beforeinput', handleBeforeinput);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onInput, onChange, onBlur, onFocus, onBeforeinput, onInvalid]);

    return (
      <wa-number-input
        ref={setNumberInputRef}
        class={clsx('NumberInput', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-number-input>
    );
  }
);

NumberInput.displayName = 'NumberInput';

// templates/vue/NumberInput/NumberInput.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import './NumberInput.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/number-input/number-input.js'));
}

/**
 * Number inputs allow users to enter numeric values with optional step controls
 */
export interface NumberInputProps {
  label?: string;
  hint?: string;
  min?: number;
  max?: number;
  step?: number;
  disabled?: boolean;
  required?: boolean;
  placeholder?: string;
  size?: 'small' | 'medium' | 'large';
  appearance?: 'filled' | 'outlined' | 'filled-outlined';
  'without-steppers'?: boolean;
}

const props = defineProps<NumberInputProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'input': [event: CustomEvent];
  'change': [event: CustomEvent];
  'blur': [event: CustomEvent];
  'focus': [event: FocusEvent];
  'wa-invalid': [event: CustomEvent];
}>();

const model = defineModel<number>();

const elementRef = ref<HTMLElement | null>(null);

watch(model, (val) => {
  const el = elementRef.value as any;
  if (el && el.value !== val) el.value = val ?? '';
});

onMounted(() => {
  ensureLoaded();
});

const handleInput = (e: Event) => { model.value = (e.target as any).value; emit('input', e as CustomEvent); };
const handleChange = (e: Event) => emit('change', e as CustomEvent);
const handleBlur = (e: Event) => emit('blur', e as CustomEvent);
const handleFocus = (e: Event) => emit('focus', e as FocusEvent);
const handleWaInvalid = (e: Event) => emit('wa-invalid', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('input', handleInput);
  el.addEventListener('change', handleChange);
  el.addEventListener('blur', handleBlur);
  el.addEventListener('focus', handleFocus);
  el.addEventListener('wa-invalid', handleWaInvalid);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('input', handleInput);
  el.removeEventListener('change', handleChange);
  el.removeEventListener('blur', handleBlur);
  el.removeEventListener('focus', handleFocus);
  el.removeEventListener('wa-invalid', handleWaInvalid);
});

defineExpose({
  focus: (options: FocusOptions) => (elementRef.value as any)?.focus?.(options),
  blur: () => (elementRef.value as any)?.blur?.(),
  select: () => (elementRef.value as any)?.select?.(),
  stepUp: () => (elementRef.value as any)?.stepUp?.(),
  stepDown: () => (elementRef.value as any)?.stepDown?.(),
  setCustomValidity: (message: string) => (elementRef.value as any)?.setCustomValidity?.(message),
  formStateRestoreCallback: (state: string | File | FormData | null, reason: 'autocomplete' | 'restore') => (elementRef.value as any)?.formStateRestoreCallback?.(state, reason),
  resetValidity: () => (elementRef.value as any)?.resetValidity?.(),
  element: elementRef,
});
</script>

<template>
  <wa-number-input
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
    :value="model"
  >
    <slot />
  </wa-number-input>
</template>
