// templates/vue/Tag/Tag.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Tag.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tag/tag.js'));
}

/**
 * Tags are used as labels to organize things or indicate selections
 */
export interface TagProps {
  appearance?: 'accent' | 'filled' | 'outlined' | 'filled-outlined';
  pill?: boolean;
  size?: 'small' | 'medium' | 'large';
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';
  'with-remove'?: boolean;
}

const props = defineProps<TagProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-remove': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaRemove = (e: Event) => emit('wa-remove', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-remove', handleWaRemove);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-remove', handleWaRemove);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-tag
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tag>
</template>

// templates/react/Tag/Tag.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Tag.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tag/tag.js'));
}

/**
 * Tags are used as labels to organize things or indicate selections
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Tag />
 *
 * // With event handlers
 * <Tag
 *   onRemove={(e) => console.log(e)} />
 *
 * ```
 */
export interface TagProps extends Omit<HTMLAttributes<HTMLElement>, 'onRemove' | 'dir'> {

  /** Visual appearance */
  appearance?: 'accent' | 'filled' | 'outlined' | 'filled-outlined';

  /** Rounded edges */
  pill?: boolean;

  /** Tag size */
  size?: 'small' | 'medium' | 'large';

  /** Theme variant */
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';

  /** Shows remove button */
  'with-remove'?: boolean;

  /** Emitted when the remove button is activated. */
  onRemove?: (event: CustomEvent) => void;
}

export interface TagRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Tag = forwardRef<TagRef, TagProps>(
  ({ children, className, onRemove, ...props }, ref) => {
    const tagRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return tagRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = tagRef.current;
      if (!el) return;

      const handleWaRemove = (e: Event) => {
        if (onRemove) onRemove(e as CustomEvent);
      };

      el.addEventListener('wa-remove', handleWaRemove);

      return () => {
        el.removeEventListener('wa-remove', handleWaRemove);
      };
    }, [onRemove]);

    return (
      <wa-tag
        ref={tagRef}
        class={clsx('Tag', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tag>
    );
  }
);

Tag.displayName = 'Tag';
