// templates/angular/Radio/radio.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/radio/radio.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/radio/radio.js'));
}

/**
 * Radios allow the user to select a single option from a group
 *
 * @see https://webawesome.com/docs/components/radio
 */
@Component({
  selector: 'k-radio',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-radio
      #element
      [attr.value]="value"
      [attr.disabled]="disabled || null"
      [attr.size]="size"
      [attr.appearance]="appearance"
      [attr.name]="name"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-radio>
  `,
  styleUrl: './radio.component.css',
})
export class RadioComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The radio value */
  @Input() value?: string;
  /** Disables the radio */
  @Input() disabled?: boolean;
  /** Radio size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Radio appearance style */
  @Input() appearance?: 'default' | 'button';
  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() blur = new EventEmitter<FocusEvent>();
  @Output() focus = new EventEmitter<FocusEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBlur = (e: Event) => this.blur.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlur);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlur));
    const handleFocus = (e: Event) => this.focus.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocus);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocus));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// docs/src/components/ui/Radio/Radio.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/radio/radio.js';
import './Radio.css';

/**
 * Radios allow the user to select a single option from a group
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Radio />
 *
 * // With event handlers
 * <Radio
 *   onBlur={(e) => console.log(e)} />
 *
 * ```
 */
export interface RadioProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onBlur' | 'onFocus' | 'dir'
> {
  /** The radio value */
  value?: string;

  /** Visual appearance */
  appearance?: string;

  /** Disables the radio */
  disabled?: boolean;

  /** Radio size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** The name of the control, submitted with form data */
  name?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;
}

export interface RadioRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Radio = forwardRef<RadioRef, RadioProps>(
  ({ children, className, onBlur, onFocus, ...props }, ref) => {
    const radioRef = useRef<HTMLElement & {}>(null);

    const setRadioRef = useCallback((el: typeof radioRef.current) => {
      radioRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return radioRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = radioRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
      };
    }, [onBlur, onFocus]);

    return (
      <wa-radio
        ref={setRadioRef}
        class={clsx('Radio', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-radio>
    );
  }
);

Radio.displayName = 'Radio';
