// docs/.kigumi/snapshots/Callout/Callout.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/callout/callout.js';
import type WaElement from '@awesome.me/webawesome-pro/dist/components/callout/callout.js';
import './Callout.css';

/**
 * Callouts are used to display important messages inline
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Callout />
 *
 * // With event handlers
 * <Callout />
 *
 * ```
 */
export interface CalloutProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** The callout's visual appearance */
  appearance?: 'accent' | 'filled' | 'outlined' | 'plain' | 'filled-outlined';

  /** The callout's size */
  size?: 'small' | 'medium' | 'large';

  /** The callout's theme variant */
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';
}

export interface CalloutRef {
  /** Reference to the underlying element */
  element: WaElement | null;
}

export const Callout = forwardRef<CalloutRef, CalloutProps>(
  ({ children, className, ...props }, ref) => {
    const calloutRef = useRef<WaElement | null>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return calloutRef.current;
        },
      }),
      []
    );

    return (
      <wa-callout
        ref={(el: WaElement | null) => {
          calloutRef.current = el;
        }}
        class={clsx('Callout', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-callout>
    );
  }
);

Callout.displayName = 'Callout';

// templates/vue/Callout/Callout.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Callout.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/callout/callout.js'));
}

/**
 * Callouts are used to display important messages inline
 */
export interface CalloutProps {
  appearance?: 'accent' | 'filled' | 'outlined' | 'plain' | 'filled-outlined';
  size?: 'small' | 'medium' | 'large';
  variant?: 'brand' | 'neutral' | 'success' | 'warning' | 'danger';
}

const props = defineProps<CalloutProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-callout
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-callout>
</template>
