// templates/angular/ProgressBar/progress-bar.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/progress-bar/progress-bar.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/progress-bar/progress-bar.js'));
}

/**
 * Progress bars are used to show the completion of a task or operation
 *
 * @see https://webawesome.com/docs/components/progress-bar
 */
@Component({
  selector: 'k-progress-bar',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-progress-bar
      #element
      [attr.value]="value"
      [attr.indeterminate]="indeterminate || null"
      [attr.label]="label"
    >
      <ng-content />
    </wa-progress-bar>
  `,
  styleUrl: './progress-bar.component.css',
})
export class ProgressBarComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Current progress (0-100) */
  @Input() value?: number;
  /** Shows indeterminate state */
  @Input() indeterminate?: boolean;
  /** Accessible label */
  @Input() label?: string;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// templates/react/ProgressBar/ProgressBar.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './ProgressBar.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/progress-bar/progress-bar.js'));
}

/**
 * Progress bars are used to show the completion of a task or operation
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ProgressBar />
 *
 * // With event handlers
 * <ProgressBar />
 *
 * ```
 */
export interface ProgressBarProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** Current progress (0-100) */
  value?: number;

  /** Shows indeterminate state */
  indeterminate?: boolean;

  /** Accessible label */
  label?: string;
}

export interface ProgressBarRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const ProgressBar = forwardRef<ProgressBarRef, ProgressBarProps>(
  ({ children, className, ...props }, ref) => {
    const progressbarRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return progressbarRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-progress-bar
        ref={progressbarRef}
        class={clsx('ProgressBar', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-progress-bar>
    );
  }
);

ProgressBar.displayName = 'ProgressBar';
