// templates/vue/DropdownItem/DropdownItem.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './DropdownItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js'));
}

/**
 * Dropdown items are used inside dropdowns to represent individual menu items
 */
export interface DropdownItemProps {
  type?: 'normal' | 'checkbox';
  checked?: boolean;
  value?: string;
  disabled?: boolean;
  loading?: boolean;
  variant?: 'neutral' | 'danger';
}

const props = defineProps<DropdownItemProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'blur': [event: CustomEvent];
  'focus': [event: FocusEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleBlur = (e: Event) => emit('blur', e as CustomEvent);
const handleFocus = (e: Event) => emit('focus', e as FocusEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('blur', handleBlur);
  el.addEventListener('focus', handleFocus);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('blur', handleBlur);
  el.removeEventListener('focus', handleFocus);
});

defineExpose({
  openSubmenu: () => (elementRef.value as any)?.openSubmenu?.(),
  closeSubmenu: () => (elementRef.value as any)?.closeSubmenu?.(),
  element: elementRef,
});
</script>

<template>
  <wa-dropdown-item
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-dropdown-item>
</template>

// templates/react/DropdownItem/DropdownItem.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './DropdownItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/dropdown-item/dropdown-item.js'));
}

/**
 * Dropdown items are used inside dropdowns to represent individual menu items
 *
 * @example
 * ```tsx
 * // Basic usage
 * <DropdownItem />
 *
 * // With event handlers
 * <DropdownItem
 *   onBlur={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<DropdownItemRef>(null);
 * <button onClick={() => ref.current?.openSubmenu()}>Call Method</button>
 * <DropdownItem ref={ref} />
 * ```
 */
export interface DropdownItemProps extends Omit<HTMLAttributes<HTMLElement>, 'onBlur' | 'onFocus' | 'dir'> {

  /** The type of menu item */
  type?: 'normal' | 'checkbox';

  /** Draws the item in a checked state (checkbox type) */
  checked?: boolean;

  /** A unique value for the menu item */
  value?: string;

  /** Disables the menu item */
  disabled?: boolean;

  /** Draws the item in a loading state */
  loading?: boolean;

  /** The dropdown item variant */
  variant?: 'neutral' | 'danger';

  /** Emitted when the dropdown item loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the dropdown item gains focus. */
  onFocus?: (event: FocusEvent) => void;
}

export interface DropdownItemRef {

  /** Opens the submenu. */
  openSubmenu: () => void;

  /** Closes the submenu. */
  closeSubmenu: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const DropdownItem = forwardRef<DropdownItemRef, DropdownItemProps>(
  ({ children, className, onBlur, onFocus, ...props }, ref) => {
    const dropdownitemRef = useRef<HTMLElement & {
      openSubmenu?: () => void;
      closeSubmenu?: () => void;
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        openSubmenu: () => {
          if (dropdownitemRef.current && typeof dropdownitemRef.current.openSubmenu === 'function') {
            dropdownitemRef.current.openSubmenu();
          }
        },
        closeSubmenu: () => {
          if (dropdownitemRef.current && typeof dropdownitemRef.current.closeSubmenu === 'function') {
            dropdownitemRef.current.closeSubmenu();
          }
        },
        get element() {
          return dropdownitemRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = dropdownitemRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
      };
    }, [onBlur, onFocus]);

    return (
      <wa-dropdown-item
        ref={dropdownitemRef}
        class={clsx('DropdownItem', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-dropdown-item>
    );
  }
);

DropdownItem.displayName = 'DropdownItem';
