// templates/vue/Scroller/Scroller.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Scroller.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/scroller/scroller.js'));
}

/**
 * Adds a scrollable container with optional shadow indicators
 */
export interface ScrollerProps {
  orientation?: 'horizontal' | 'vertical' | 'both';
  'with-scroll-indicator'?: boolean;
  'without-scrollbar'?: boolean;
  'without-shadow'?: boolean;
}

const props = defineProps<ScrollerProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-scroller
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-scroller>
</template>

// templates/react/Scroller/Scroller.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Scroller.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/scroller/scroller.js'));
}

/**
 * Adds a scrollable container with optional shadow indicators
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Scroller />
 *
 * // With event handlers
 * <Scroller />
 *
 * ```
 */
export interface ScrollerProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** Scroll direction */
  orientation?: 'horizontal' | 'vertical' | 'both';

  /** Shows shadow indicators */
  'with-scroll-indicator'?: boolean;

  /** Hides the scrollbar */
  'without-scrollbar'?: boolean;

  /** Hides shadow indicators */
  'without-shadow'?: boolean;
}

export interface ScrollerRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Scroller = forwardRef<ScrollerRef, ScrollerProps>(
  ({ children, className, ...props }, ref) => {
    const scrollerRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return scrollerRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-scroller
        ref={scrollerRef}
        class={clsx('Scroller', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-scroller>
    );
  }
);

Scroller.displayName = 'Scroller';
