// templates/angular/PieChart/pie-chart.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/pie-chart/pie-chart.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/pie-chart/pie-chart.js'));
}

/**
 * Divides a circle into wedges that represent each category's share of the whole
 *
 * @see https://webawesome.com/docs/components/pie-chart
 */
@Component({
  selector: 'k-pie-chart',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-pie-chart
      #element
      [attr.label]="label"
      [attr.description]="description"
      [attr.legend-position]="legendPosition"
      [attr.without-animation]="withoutAnimation || null"
      [attr.without-legend]="withoutLegend || null"
      [attr.without-tooltip]="withoutTooltip || null"
    >
      <ng-content />
    </wa-pie-chart>
  `,
  styleUrl: './pie-chart.component.css',
})
export class PieChartComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible name announced by assistive technology */
  @Input() label?: string;
  /** Extended accessible description for the chart */
  @Input() description?: string;
  /** Placement of the dataset legend relative to the chart */
  @Input() legendPosition?:
    'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';
  /** Disables entrance and update motion effects */
  @Input() withoutAnimation?: boolean;
  /** Hides the dataset legend entirely */
  @Input() withoutLegend?: boolean;
  /** Prevents hover tooltips from appearing on data points */
  @Input() withoutTooltip?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// docs/src/components/ui/PieChart/PieChart.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/pie-chart/pie-chart.js';
import './PieChart.css';

/**
 * Divides a circle into wedges that represent each category's share of the whole
 *
 * @example
 * ```tsx
 * <PieChart label="Device usage">
 *   <script type="application/json">{JSON.stringify({
 *     data: {
 *       labels: ['Mobile', 'Desktop', 'Tablet'],
 *       datasets: [{ data: [55, 35, 10] }]
 *     }
 *   })}</script>
 * </PieChart>
 * ```
 */
export interface PieChartProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** Accessible name announced by assistive technology */
  label?: string;

  /** Extended accessible description for the chart */
  description?: string;

  /** Placement of the dataset legend relative to the chart */
  'legend-position'?: 'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';

  /** Disables entrance and update motion effects */
  'without-animation'?: boolean;

  /** Hides the dataset legend entirely */
  'without-legend'?: boolean;

  /** Prevents hover tooltips from appearing on data points */
  'without-tooltip'?: boolean;
}

export interface PieChartRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const PieChart = forwardRef<PieChartRef, PieChartProps>(
  ({ children, className, ...props }, ref) => {
    const pieChartRef = useRef<HTMLElement>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return pieChartRef.current;
        },
      }),
      []
    );

    return (
      <wa-pie-chart
        ref={pieChartRef}
        class={clsx('PieChart', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-pie-chart>
    );
  }
);

PieChart.displayName = 'PieChart';
