// templates/react/FormatDate/FormatDate.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './FormatDate.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-date/format-date.js'));
}

/**
 * Formats a date/time using the Intl.DateTimeFormat API
 *
 * @example
 * ```tsx
 * // Basic usage
 * <FormatDate />
 *
 * // With event handlers
 * <FormatDate />
 *
 * ```
 */
export interface FormatDateProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The date/time to format */
  date?: string;

  /** How to display the weekday */
  weekday?: 'narrow' | 'short' | 'long';

  /** How to display the era */
  era?: 'narrow' | 'short' | 'long';

  /** How to display the year */
  year?: 'numeric' | '2-digit';

  /** How to display the month */
  month?: 'numeric' | '2-digit' | 'narrow' | 'short' | 'long';

  /** How to display the day */
  day?: 'numeric' | '2-digit';

  /** How to display the hour */
  hour?: 'numeric' | '2-digit';

  /** How to display the minute */
  minute?: 'numeric' | '2-digit';

  /** How to display the second */
  second?: 'numeric' | '2-digit';

  /** 12 or 24 hour format */
  'hour-format'?: 'auto' | '12' | '24';

  /** How to display the time zone */
  'time-zone-name'?: 'short' | 'long';

  /** The time zone to use */
  'time-zone'?: string;

  /** The locale to use when formatting */
  lang?: string;
}

export interface FormatDateRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const FormatDate = forwardRef<FormatDateRef, FormatDateProps>(
  ({ children, className, ...props }, ref) => {
    const formatdateRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return formatdateRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-format-date
        ref={formatdateRef}
        class={clsx('FormatDate', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-format-date>
    );
  }
);

FormatDate.displayName = 'FormatDate';

// templates/vue/FormatDate/FormatDate.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatDate.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-date/format-date.js'));
}

/**
 * Formats a date/time using the Intl.DateTimeFormat API
 */
export interface FormatDateProps {
  date?: string;
  weekday?: 'narrow' | 'short' | 'long';
  era?: 'narrow' | 'short' | 'long';
  year?: 'numeric' | '2-digit';
  month?: 'numeric' | '2-digit' | 'narrow' | 'short' | 'long';
  day?: 'numeric' | '2-digit';
  hour?: 'numeric' | '2-digit';
  minute?: 'numeric' | '2-digit';
  second?: 'numeric' | '2-digit';
  'hour-format'?: 'auto' | '12' | '24';
  'time-zone-name'?: 'short' | 'long';
  'time-zone'?: string;
  lang?: string;
}

const props = defineProps<FormatDateProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-date
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-date>
</template>
