// templates/vue/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Breadcrumb.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/breadcrumb/breadcrumb.js'));
}

/**
 * Breadcrumbs provide a group of links so users can easily navigate a website hierarchy
 */
export interface BreadcrumbProps {
  label?: string;
}

const props = defineProps<BreadcrumbProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-breadcrumb
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-breadcrumb>
</template>

// templates/react/Breadcrumb/Breadcrumb.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Breadcrumb.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/breadcrumb/breadcrumb.js'));
}

/**
 * Breadcrumbs provide a group of links so users can easily navigate a website hierarchy
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Breadcrumb />
 *
 * // With event handlers
 * <Breadcrumb />
 *
 * ```
 */
export interface BreadcrumbProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The label to use for the breadcrumb control for assistive devices */
  label?: string;
}

export interface BreadcrumbRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Breadcrumb = forwardRef<BreadcrumbRef, BreadcrumbProps>(
  ({ children, className, ...props }, ref) => {
    const breadcrumbRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return breadcrumbRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-breadcrumb
        ref={breadcrumbRef}
        class={clsx('Breadcrumb', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-breadcrumb>
    );
  }
);

Breadcrumb.displayName = 'Breadcrumb';
