// docs/src/components/ui/Popup/Popup.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/popup/popup.js';
import './Popup.css';
import type { WaRepositionEvent } from '@awesome.me/webawesome-pro/dist/events/reposition.js';

/**
 * Popup is a utility component for positioning elements relative to an anchor
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Popup />
 *
 * // With event handlers
 * <Popup
 *   onReposition={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<PopupRef>(null);
 * <button onClick={() => ref.current?.reposition()}>Call Method</button>
 * <Popup ref={ref} />
 * ```
 */
export interface PopupProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onReposition' | 'dir'
> {
  /** Activates the positioning logic */
  active?: boolean;

  /** Anchor element ID or reference */
  anchor?: string;

  /** Preferred placement */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';

  /** Positioning strategy */
  strategy?: 'absolute' | 'fixed';

  /** Distance from anchor */
  distance?: number;

  /** Offset along anchor */
  skidding?: number;

  /** Shows an arrow */
  arrow?: boolean;

  /** Arrow position */
  'arrow-placement'?: 'start' | 'end' | 'center' | 'anchor';

  /** Arrow edge padding */
  'arrow-padding'?: number;

  /** Area flip, shift and auto-size keep the popup inside: the viewport, or the anchor's scrolling ancestors */
  boundary?: 'viewport' | 'scroll';

  /** Flips when constrained */
  flip?: boolean;

  /** Fallback placements */
  'flip-fallback-placements'?: string;

  /** Fallback strategy */
  'flip-fallback-strategy'?: 'best-fit' | 'initial';

  /** Flip boundary padding */
  'flip-padding'?: number;

  /** Shifts to stay visible */
  shift?: boolean;

  /** Shift boundary padding */
  'shift-padding'?: number;

  /** Auto-resize behavior */
  'auto-size'?: 'horizontal' | 'vertical' | 'both';

  /** Syncs dimensions with anchor */
  sync?: 'width' | 'height' | 'both';

  /** Auto-size boundary padding */
  'auto-size-padding'?: number;

  /** Covers the gap between anchor and popup with an invisible element, so the pointer can cross it without leaving either */
  'hover-bridge'?: boolean;

  /** Emitted when the popup is repositioned. This event can fire a lot, so avoid putting expensive operations in your listener or consider debouncing it. */
  onReposition?: (event: WaRepositionEvent) => void;
}

export interface PopupRef {
  /** Forces the popup to recalculate and reposition itself. */
  reposition: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Popup = forwardRef<PopupRef, PopupProps>(
  ({ children, className, onReposition, ...props }, ref) => {
    const popupRef = useRef<
      HTMLElement & {
        reposition?: () => void;
      }
    >(null);

    const setPopupRef = useCallback((el: typeof popupRef.current) => {
      popupRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        reposition: () => {
          if (
            popupRef.current &&
            typeof popupRef.current.reposition === 'function'
          ) {
            popupRef.current.reposition();
          }
        },
        get element() {
          return popupRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = popupRef.current;
      if (!el) return;

      const handleReposition = (e: Event) => {
        if (onReposition) onReposition(e as WaRepositionEvent);
      };

      el.addEventListener('wa-reposition', handleReposition);

      return () => {
        el.removeEventListener('wa-reposition', handleReposition);
      };
    }, [onReposition]);

    return (
      <wa-popup
        ref={setPopupRef}
        class={clsx('Popup', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-popup>
    );
  }
);

Popup.displayName = 'Popup';

// templates/angular/Popup/popup.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/popup/popup.js';
import type { WaRepositionEvent } from '@awesome.me/webawesome/dist/events/reposition.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/popup/popup.js'));
}

/**
 * Popup is a utility component for positioning elements relative to an anchor
 *
 * @see https://webawesome.com/docs/components/popup
 */
@Component({
  selector: 'k-popup',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-popup
      #element
      [attr.active]="active || null"
      [attr.anchor]="anchor"
      [attr.placement]="placement"
      [attr.strategy]="strategy"
      [attr.distance]="distance"
      [attr.skidding]="skidding"
      [attr.arrow]="arrow || null"
      [attr.arrow-placement]="arrowPlacement"
      [attr.arrow-padding]="arrowPadding"
      [attr.boundary]="boundary"
      [attr.flip]="flip || null"
      [attr.flip-fallback-placements]="flipFallbackPlacements"
      [attr.flip-fallback-strategy]="flipFallbackStrategy"
      [attr.flip-padding]="flipPadding"
      [attr.shift]="shift || null"
      [attr.shift-padding]="shiftPadding"
      [attr.auto-size]="autoSize"
      [attr.sync]="sync"
      [attr.auto-size-padding]="autoSizePadding"
      [attr.hover-bridge]="hoverBridge || null"
    >
      <ng-content />
    </wa-popup>
  `,
  styleUrl: './popup.component.css',
})
export class PopupComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Activates the positioning logic */
  @Input() active?: boolean;
  /** Anchor element ID or reference */
  @Input() anchor?: string;
  /** Preferred placement */
  @Input() placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** Positioning strategy */
  @Input() strategy?: 'absolute' | 'fixed';
  /** Distance from anchor */
  @Input() distance?: number;
  /** Offset along anchor */
  @Input() skidding?: number;
  /** Shows an arrow */
  @Input() arrow?: boolean;
  /** Arrow position */
  @Input() arrowPlacement?: 'start' | 'end' | 'center' | 'anchor';
  /** Arrow edge padding */
  @Input() arrowPadding?: number;
  /** Area flip, shift and auto-size keep the popup inside: the viewport, or the anchor's scrolling ancestors */
  @Input() boundary?: 'viewport' | 'scroll';
  /** Flips when constrained */
  @Input() flip?: boolean;
  /** Fallback placements */
  @Input() flipFallbackPlacements?: string;
  /** Fallback strategy */
  @Input() flipFallbackStrategy?: 'best-fit' | 'initial';
  /** Flip boundary padding */
  @Input() flipPadding?: number;
  /** Shifts to stay visible */
  @Input() shift?: boolean;
  /** Shift boundary padding */
  @Input() shiftPadding?: number;
  /** Auto-resize behavior */
  @Input() autoSize?: 'horizontal' | 'vertical' | 'both';
  /** Syncs dimensions with anchor */
  @Input() sync?: 'width' | 'height' | 'both';
  /** Auto-size boundary padding */
  @Input() autoSizePadding?: number;
  /** Covers the gap between anchor and popup with an invisible element, so the pointer can cross it without leaving either */
  @Input() hoverBridge?: boolean;

  @Output() repositionEvent = new EventEmitter<WaRepositionEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleRepositionEvent = (e: Event) =>
      this.repositionEvent.emit(e as WaRepositionEvent);
    el.addEventListener('wa-reposition', handleRepositionEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-reposition', handleRepositionEvent)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  reposition(): void {
    (
      this.elementRef.nativeElement as unknown as { reposition: () => void }
    ).reposition();
  }
}
