// templates/react/Tooltip/Tooltip.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Tooltip.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tooltip/tooltip.js'));
}

/**
 * Tooltips display additional information based on a specific action
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Tooltip />
 *
 * // With event handlers
 * <Tooltip
 *   onShow={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TooltipRef>(null);
 * <button onClick={() => ref.current?.show()}>Call Method</button>
 * <Tooltip ref={ref} />
 * ```
 */
export interface TooltipProps extends Omit<HTMLAttributes<HTMLElement>, 'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'dir'> {

  /** Tooltip placement */
  placement?: 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end';

  /** Disables the tooltip */
  disabled?: boolean;

  /** Distance from target */
  distance?: number;

  /** Whether the tooltip is open */
  open?: boolean;

  /** Offset along target */
  skidding?: number;

  /** Activation events */
  trigger?: string;

  /** Hides the arrow */
  'without-arrow'?: boolean;

  /** Show delay (ms) */
  'show-delay'?: number;

  /** Hide delay (ms) */
  'hide-delay'?: number;

  /** The ID of the element the tooltip is anchored to */
  for?: string;

  /** Emitted when the tooltip begins to show. */
  onShow?: (event: CustomEvent) => void;

  /** Emitted after the tooltip has shown and all animations are complete. */
  onAfterShow?: (event: CustomEvent) => void;

  /** Emitted when the tooltip begins to hide. */
  onHide?: (event: CustomEvent) => void;

  /** Emitted after the tooltip has hidden and all animations are complete. */
  onAfterHide?: (event: CustomEvent) => void;
}

export interface TooltipRef {

  /** Shows the tooltip. */
  show: () => void;

  /** Hides the tooltip */
  hide: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Tooltip = forwardRef<TooltipRef, TooltipProps>(
  ({ children, className, onShow, onAfterShow, onHide, onAfterHide, ...props }, ref) => {
    const tooltipRef = useRef<HTMLElement & {
      show?: () => void;
      hide?: () => void;
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (tooltipRef.current && typeof tooltipRef.current.show === 'function') {
            tooltipRef.current.show();
          }
        },
        hide: () => {
          if (tooltipRef.current && typeof tooltipRef.current.hide === 'function') {
            tooltipRef.current.hide();
          }
        },
        get element() {
          return tooltipRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = tooltipRef.current;
      if (!el) return;

      const handleWaShow = (e: Event) => {
        if (onShow) onShow(e as CustomEvent);
      };

      const handleWaAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as CustomEvent);
      };

      const handleWaHide = (e: Event) => {
        if (onHide) onHide(e as CustomEvent);
      };

      const handleWaAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as CustomEvent);
      };

      el.addEventListener('wa-show', handleWaShow);
      el.addEventListener('wa-after-show', handleWaAfterShow);
      el.addEventListener('wa-hide', handleWaHide);
      el.addEventListener('wa-after-hide', handleWaAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleWaShow);
        el.removeEventListener('wa-after-show', handleWaAfterShow);
        el.removeEventListener('wa-hide', handleWaHide);
        el.removeEventListener('wa-after-hide', handleWaAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return (
      <wa-tooltip
        ref={tooltipRef}
        class={clsx('Tooltip', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tooltip>
    );
  }
);

Tooltip.displayName = 'Tooltip';

// templates/vue/Tooltip/Tooltip.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import './Tooltip.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tooltip/tooltip.js'));
}

/**
 * Tooltips display additional information based on a specific action
 */
export interface TooltipProps {
  placement?: 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end';
  disabled?: boolean;
  distance?: number;
  skidding?: number;
  trigger?: string;
  'without-arrow'?: boolean;
  'show-delay'?: number;
  'hide-delay'?: number;
  for?: string;
}

const props = defineProps<TooltipProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-show': [event: CustomEvent];
  'wa-after-show': [event: CustomEvent];
  'wa-hide': [event: CustomEvent];
  'wa-after-hide': [event: CustomEvent];
}>();

const open = defineModel<boolean>('open', { default: false });

const elementRef = ref<HTMLElement | null>(null);

watch(open, (newOpen) => {
  const el = elementRef.value as any;
  if (!el) return;
  const isOpen = el.open ?? false;
  if (newOpen && !isOpen) el.show?.();
  else if (!newOpen && isOpen) el.hide?.();
});

onMounted(() => {
  ensureLoaded();
});

const handleWaShow = (e: Event) => { open.value = true; emit('wa-show', e as CustomEvent); };
const handleWaAfterShow = (e: Event) => emit('wa-after-show', e as CustomEvent);
const handleWaHide = (e: Event) => { open.value = false; emit('wa-hide', e as CustomEvent); };
const handleWaAfterHide = (e: Event) => emit('wa-after-hide', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-show', handleWaShow);
  el.addEventListener('wa-after-show', handleWaAfterShow);
  el.addEventListener('wa-hide', handleWaHide);
  el.addEventListener('wa-after-hide', handleWaAfterHide);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-show', handleWaShow);
  el.removeEventListener('wa-after-show', handleWaAfterShow);
  el.removeEventListener('wa-hide', handleWaHide);
  el.removeEventListener('wa-after-hide', handleWaAfterHide);
});

defineExpose({
  show: () => (elementRef.value as any)?.show?.(),
  hide: () => (elementRef.value as any)?.hide?.(),
  element: elementRef,
});
</script>

<template>
  <wa-tooltip
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
    :open="open"
  >
    <slot />
  </wa-tooltip>
</template>
