// templates/angular/DoughnutChart/doughnut-chart.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/doughnut-chart/doughnut-chart.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/doughnut-chart/doughnut-chart.js'));
}

/**
 * Shows proportional segments in a ring shape with an open center for summary content
 *
 * @see https://webawesome.com/docs/components/doughnut-chart
 */
@Component({
  selector: 'k-doughnut-chart',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-doughnut-chart
        #element
        [attr.label]="label"
        [attr.description]="description"
        [attr.legend-position]="legendPosition"
        [attr.without-animation]="withoutAnimation || null"
        [attr.without-legend]="withoutLegend || null"
        [attr.without-tooltip]="withoutTooltip || null">
      <ng-content />
    </wa-doughnut-chart>
  `,
  styleUrl: './doughnut-chart.component.css',
})
export class DoughnutChartComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible name announced by assistive technology */
  @Input() label?: string;
  /** Extended accessible description for the chart */
  @Input() description?: string;
  /** Placement of the dataset legend relative to the chart */
  @Input() legendPosition?: 'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';
  /** Disables entrance and update motion effects */
  @Input() withoutAnimation?: boolean;
  /** Hides the dataset legend entirely */
  @Input() withoutLegend?: boolean;
  /** Prevents hover tooltips from appearing on data points */
  @Input() withoutTooltip?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// templates/react/DoughnutChart/DoughnutChart.jsx
import React from 'react';
import clsx from 'clsx';
import './DoughnutChart.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/doughnut-chart/doughnut-chart.js'));
}

/**
 * Shows proportional segments in a ring shape with an open center for summary content
 *
 * @example
 * ```jsx
 * <DoughnutChart label="Budget breakdown">
 *   <script type="application/json">{JSON.stringify({
 *     data: {
 *       labels: ['Rent', 'Food', 'Transport', 'Savings'],
 *       datasets: [{ data: [35, 25, 20, 20] }]
 *     }
 *   })}</script>
 * </DoughnutChart>
 * ```
 *
 * @typedef {Object} DoughnutChartProps
 * @property {string} [label] - Accessible name announced by assistive technology
 * @property {string} [description] - Extended accessible description for the chart
 * @property {string} [legend-position] - Placement of the legend: top | right | bottom | left | start | end
 * @property {boolean} [without-animation] - Disables entrance and update motion effects
 * @property {boolean} [without-legend] - Hides the dataset legend entirely
 * @property {boolean} [without-tooltip] - Prevents hover tooltips from appearing on data points
 */

export const DoughnutChart = React.forwardRef(
  ({ children, className, ...props }, ref) => {
    const doughnutChartRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        get element() {
          return doughnutChartRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-doughnut-chart
        ref={doughnutChartRef}
        class={clsx('DoughnutChart', className)}
        {...props}
      >
        {children}
      </wa-doughnut-chart>
    );
  }
);

DoughnutChart.displayName = 'DoughnutChart';
