// templates/angular/Video/video.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/video/video.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 *
 * @see https://webawesome.com/docs/components/video
 */
@Component({
  selector: 'k-video',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-video
      #element
      [attr.controls]="controls"
      [attr.src]="src"
      [attr.poster]="poster"
      [attr.title]="title"
      [attr.thumbnails]="thumbnails"
      [attr.playing]="playing || null"
      [attr.muted]="muted || null"
      [attr.volume]="volume"
      [attr.autoplay]="autoplay || null"
      [attr.loop]="loop || null"
      [attr.autoplay-muted]="autoplayMuted || null"
      [attr.autoplay-on-visible]="autoplayOnVisible || null"
      [attr.preload]="preload"
      [attr.icon-library]="iconLibrary"
    >
      <ng-content />
    </wa-video>
  `,
  styleUrl: './video.component.css',
})
export class VideoComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The set of controls to display */
  @Input() controls?: 'none' | 'standard' | 'full';
  /** The video source URL */
  @Input() src?: string;
  /** The poster image URL shown before playback */
  @Input() poster?: string;
  /** The video title */
  @Input() title?: string;
  /** URL to a WebVTT file for timeline thumbnail previews */
  @Input() thumbnails?: string;
  /** Whether the video is currently playing */
  @Input() playing?: boolean;
  /** Whether the video is muted */
  @Input() muted?: boolean;
  /** The volume level from 0 to 1 */
  @Input() volume?: number;
  /** Automatically start playback when connected */
  @Input() autoplay?: boolean;
  /** Restart playback when the video ends */
  @Input() loop?: boolean;
  /** Autoplay in a muted state */
  @Input() autoplayMuted?: boolean;
  /** Resume playback when scrolled back into view */
  @Input() autoplayOnVisible?: boolean;
  /** The browser preload strategy */
  @Input() preload?: 'auto' | 'metadata' | 'none';
  /** The icon library used for built-in control icons */
  @Input() iconLibrary?: string;

  @Output() timeupdate = new EventEmitter<CustomEvent>();
  @Output() playEvent = new EventEmitter<CustomEvent>();
  @Output() pauseEvent = new EventEmitter<CustomEvent>();
  @Output() volumechange = new EventEmitter<CustomEvent>();
  @Output() error = new EventEmitter<Event>();
  @Output() ended = new EventEmitter<CustomEvent>();
  @Output() loadedmetadata = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleTimeupdate = (e: Event) =>
      this.timeupdate.emit(e as CustomEvent);
    el.addEventListener('timeupdate', handleTimeupdate);
    this.cleanups.push(() =>
      el.removeEventListener('timeupdate', handleTimeupdate)
    );
    const handlePlayEvent = (e: Event) => this.playEvent.emit(e as CustomEvent);
    el.addEventListener('play', handlePlayEvent);
    this.cleanups.push(() => el.removeEventListener('play', handlePlayEvent));
    const handlePauseEvent = (e: Event) =>
      this.pauseEvent.emit(e as CustomEvent);
    el.addEventListener('pause', handlePauseEvent);
    this.cleanups.push(() => el.removeEventListener('pause', handlePauseEvent));
    const handleVolumechange = (e: Event) =>
      this.volumechange.emit(e as CustomEvent);
    el.addEventListener('volumechange', handleVolumechange);
    this.cleanups.push(() =>
      el.removeEventListener('volumechange', handleVolumechange)
    );
    const handleError = (e: Event) => this.error.emit(e as Event);
    el.addEventListener('error', handleError);
    this.cleanups.push(() => el.removeEventListener('error', handleError));
    const handleEnded = (e: Event) => this.ended.emit(e as CustomEvent);
    el.addEventListener('ended', handleEnded);
    this.cleanups.push(() => el.removeEventListener('ended', handleEnded));
    const handleLoadedmetadata = (e: Event) =>
      this.loadedmetadata.emit(e as CustomEvent);
    el.addEventListener('loadedmetadata', handleLoadedmetadata);
    this.cleanups.push(() =>
      el.removeEventListener('loadedmetadata', handleLoadedmetadata)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  play(): void {
    (this.elementRef.nativeElement as unknown as { play: () => void }).play();
  }
  pause(): void {
    (this.elementRef.nativeElement as unknown as { pause: () => void }).pause();
  }
  togglePlay(): void {
    (
      this.elementRef.nativeElement as unknown as { togglePlay: () => void }
    ).togglePlay();
  }
  toggleMute(): void {
    (
      this.elementRef.nativeElement as unknown as { toggleMute: () => void }
    ).toggleMute();
  }
  seek(time?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        seek: (time?: number) => void;
      }
    ).seek(time);
  }
  setVolume(volume?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        setVolume: (volume?: number) => void;
      }
    ).setVolume(volume);
  }
  setPlaybackRate(rate?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        setPlaybackRate: (rate?: number) => void;
      }
    ).setPlaybackRate(rate);
  }
  requestFullscreen(): void {
    (
      this.elementRef.nativeElement as unknown as {
        requestFullscreen: () => void;
      }
    ).requestFullscreen();
  }
  exitFullscreen(): void {
    (
      this.elementRef.nativeElement as unknown as { exitFullscreen: () => void }
    ).exitFullscreen();
  }
  getVideoElement(): void {
    (
      this.elementRef.nativeElement as unknown as {
        getVideoElement: () => void;
      }
    ).getVideoElement();
  }
  getState(): void {
    (
      this.elementRef.nativeElement as unknown as { getState: () => void }
    ).getState();
  }
}

// templates/react/Video/Video.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaVideo from '@awesome.me/webawesome/dist/components/video/video.js';
import './Video.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Video />
 *
 * // With event handlers
 * <Video
 *   onTimeupdate={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<VideoRef>(null);
 * <button onClick={() => ref.current?.play()}>Call Method</button>
 * <Video ref={ref} />
 * ```
 */
export interface VideoProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onTimeupdate'
  | 'onPlay'
  | 'onPause'
  | 'onVolumechange'
  | 'onError'
  | 'onEnded'
  | 'onLoadedmetadata'
  | 'dir'
> {
  /** The set of controls to display */
  controls?: 'none' | 'standard' | 'full';

  /** The video source URL */
  src?: string;

  /** The poster image URL shown before playback */
  poster?: string;

  /** The video title */
  title?: string;

  /** URL to a WebVTT file for timeline thumbnail previews */
  thumbnails?: string;

  /** Whether the video is currently playing */
  playing?: boolean;

  /** Whether the video is muted */
  muted?: boolean;

  /** The volume level from 0 to 1 */
  volume?: number;

  /** Automatically start playback when connected */
  autoplay?: boolean;

  /** Restart playback when the video ends */
  loop?: boolean;

  /** Autoplay in a muted state */
  'autoplay-muted'?: boolean;

  /** Resume playback when scrolled back into view */
  'autoplay-on-visible'?: boolean;

  /** The browser preload strategy */
  preload?: 'auto' | 'metadata' | 'none';

  /** The icon library used for built-in control icons */
  'icon-library'?: string;

  onTimeupdate?: (event: CustomEvent) => void;

  onPlay?: (event: CustomEvent) => void;

  onPause?: (event: CustomEvent) => void;

  onVolumechange?: (event: CustomEvent) => void;

  onError?: (event: Event) => void;

  onEnded?: (event: CustomEvent) => void;

  onLoadedmetadata?: (event: CustomEvent) => void;
}

export interface VideoRef {
  play: () => void;

  pause: () => void;

  togglePlay: () => void;

  toggleMute: () => void;

  seek: (time: number) => void;

  setVolume: (volume: number) => void;

  setPlaybackRate: (rate: number) => void;

  requestFullscreen: () => void;

  exitFullscreen: () => void;

  getVideoElement: () => void;

  getState: () => void;
  /** Reference to the underlying HTML element */
  element: WaVideo | null;
}

export const Video = forwardRef<VideoRef, VideoProps>(
  (
    {
      children,
      className,
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
      ...props
    },
    ref
  ) => {
    const videoRef = useRef<WaVideo | null>(null);
    const setVideoRef = useCallback((el: WaVideo | null) => {
      videoRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        play: () => {
          if (videoRef.current && typeof videoRef.current.play === 'function') {
            videoRef.current.play();
          }
        },
        pause: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.pause === 'function'
          ) {
            videoRef.current.pause();
          }
        },
        togglePlay: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.togglePlay === 'function'
          ) {
            videoRef.current.togglePlay();
          }
        },
        toggleMute: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.toggleMute === 'function'
          ) {
            videoRef.current.toggleMute();
          }
        },
        seek: (time: number) => {
          if (videoRef.current && typeof videoRef.current.seek === 'function') {
            videoRef.current.seek(time);
          }
        },
        setVolume: (volume: number) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setVolume === 'function'
          ) {
            videoRef.current.setVolume(volume);
          }
        },
        setPlaybackRate: (rate: number) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setPlaybackRate === 'function'
          ) {
            videoRef.current.setPlaybackRate(rate);
          }
        },
        requestFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.requestFullscreen === 'function'
          ) {
            videoRef.current.requestFullscreen();
          }
        },
        exitFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.exitFullscreen === 'function'
          ) {
            videoRef.current.exitFullscreen();
          }
        },
        getVideoElement: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getVideoElement === 'function'
          ) {
            videoRef.current.getVideoElement();
          }
        },
        getState: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getState === 'function'
          ) {
            videoRef.current.getState();
          }
        },
        get element() {
          return videoRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = videoRef.current;
      if (!el) return;

      const handleTimeupdate = (e: Event) => {
        if (onTimeupdate) onTimeupdate(e as CustomEvent);
      };

      const handlePlay = (e: Event) => {
        if (onPlay) onPlay(e as CustomEvent);
      };

      const handlePause = (e: Event) => {
        if (onPause) onPause(e as CustomEvent);
      };

      const handleVolumechange = (e: Event) => {
        if (onVolumechange) onVolumechange(e as CustomEvent);
      };

      const handleError = (e: Event) => {
        if (onError) onError(e as Event);
      };

      const handleEnded = (e: Event) => {
        if (onEnded) onEnded(e as CustomEvent);
      };

      const handleLoadedmetadata = (e: Event) => {
        if (onLoadedmetadata) onLoadedmetadata(e as CustomEvent);
      };

      el.addEventListener('timeupdate', handleTimeupdate);
      el.addEventListener('play', handlePlay);
      el.addEventListener('pause', handlePause);
      el.addEventListener('volumechange', handleVolumechange);
      el.addEventListener('error', handleError);
      el.addEventListener('ended', handleEnded);
      el.addEventListener('loadedmetadata', handleLoadedmetadata);

      return () => {
        el.removeEventListener('timeupdate', handleTimeupdate);
        el.removeEventListener('play', handlePlay);
        el.removeEventListener('pause', handlePause);
        el.removeEventListener('volumechange', handleVolumechange);
        el.removeEventListener('error', handleError);
        el.removeEventListener('ended', handleEnded);
        el.removeEventListener('loadedmetadata', handleLoadedmetadata);
      };
    }, [
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
    ]);

    return (
      <wa-video
        ref={setVideoRef}
        class={clsx('Video', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-video>
    );
  }
);

Video.displayName = 'Video';
