// templates/angular/Video/video.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/video/video.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 *
 * @see https://webawesome.com/docs/components/video
 */
@Component({
  selector: 'k-video',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-video
      #element
      [attr.controls]="controls"
      [attr.src]="src"
      [attr.poster]="poster"
      [attr.title]="title"
      [attr.thumbnails]="thumbnails"
      [attr.playing]="playing || null"
      [attr.muted]="muted || null"
      [attr.volume]="volume"
      [attr.autoplay]="autoplay || null"
      [attr.loop]="loop || null"
      [attr.autoplay-muted]="autoplayMuted || null"
      [attr.autoplay-on-visible]="autoplayOnVisible || null"
      [attr.preload]="preload"
      [attr.icon-library]="iconLibrary"
    >
      <ng-content />
    </wa-video>
  `,
  styleUrl: './video.component.css',
})
export class VideoComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The set of controls to display */
  @Input() controls?: 'none' | 'standard' | 'full';
  /** The video source URL */
  @Input() src?: string;
  /** The poster image URL shown before playback */
  @Input() poster?: string;
  /** The video title */
  @Input() title?: string;
  /** URL to a WebVTT file for timeline thumbnail previews */
  @Input() thumbnails?: string;
  /** Whether the video is currently playing */
  @Input() playing?: boolean;
  /** Whether the video is muted */
  @Input() muted?: boolean;
  /** The volume level from 0 to 1 */
  @Input() volume?: number;
  /** Automatically start playback when connected */
  @Input() autoplay?: boolean;
  /** Restart playback when the video ends */
  @Input() loop?: boolean;
  /** Autoplay in a muted state */
  @Input() autoplayMuted?: boolean;
  /** Resume playback when scrolled back into view */
  @Input() autoplayOnVisible?: boolean;
  /** The browser preload strategy */
  @Input() preload?: 'auto' | 'metadata' | 'none';
  /** The icon library used for built-in control icons */
  @Input() iconLibrary?: string;

  @Output() timeupdate = new EventEmitter<Event>();
  @Output() playEvent = new EventEmitter<Event>();
  @Output() pauseEvent = new EventEmitter<Event>();
  @Output() volumechange = new EventEmitter<Event>();
  @Output() error = new EventEmitter<Event>();
  @Output() ended = new EventEmitter<Event>();
  @Output() loadedmetadata = new EventEmitter<Event>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleTimeupdate = (e: Event) => this.timeupdate.emit(e);
    el.addEventListener('timeupdate', handleTimeupdate);
    this.cleanups.push(() =>
      el.removeEventListener('timeupdate', handleTimeupdate)
    );
    const handlePlayEvent = (e: Event) => this.playEvent.emit(e);
    el.addEventListener('play', handlePlayEvent);
    this.cleanups.push(() => el.removeEventListener('play', handlePlayEvent));
    const handlePauseEvent = (e: Event) => this.pauseEvent.emit(e);
    el.addEventListener('pause', handlePauseEvent);
    this.cleanups.push(() => el.removeEventListener('pause', handlePauseEvent));
    const handleVolumechange = (e: Event) => this.volumechange.emit(e);
    el.addEventListener('volumechange', handleVolumechange);
    this.cleanups.push(() =>
      el.removeEventListener('volumechange', handleVolumechange)
    );
    const handleError = (e: Event) => this.error.emit(e);
    el.addEventListener('error', handleError);
    this.cleanups.push(() => el.removeEventListener('error', handleError));
    const handleEnded = (e: Event) => this.ended.emit(e);
    el.addEventListener('ended', handleEnded);
    this.cleanups.push(() => el.removeEventListener('ended', handleEnded));
    const handleLoadedmetadata = (e: Event) => this.loadedmetadata.emit(e);
    el.addEventListener('loadedmetadata', handleLoadedmetadata);
    this.cleanups.push(() =>
      el.removeEventListener('loadedmetadata', handleLoadedmetadata)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  play(): void {
    (this.elementRef.nativeElement as unknown as { play: () => void }).play();
  }
  pause(): void {
    (this.elementRef.nativeElement as unknown as { pause: () => void }).pause();
  }
  togglePlay(): void {
    (
      this.elementRef.nativeElement as unknown as { togglePlay: () => void }
    ).togglePlay();
  }
  toggleMute(): void {
    (
      this.elementRef.nativeElement as unknown as { toggleMute: () => void }
    ).toggleMute();
  }
  seek(time?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        seek: (time?: number) => void;
      }
    ).seek(time);
  }
  setVolume(volume?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        setVolume: (volume?: number) => void;
      }
    ).setVolume(volume);
  }
  setPlaybackRate(rate?: number): void {
    (
      this.elementRef.nativeElement as unknown as {
        setPlaybackRate: (rate?: number) => void;
      }
    ).setPlaybackRate(rate);
  }
  requestFullscreen(): void {
    (
      this.elementRef.nativeElement as unknown as {
        requestFullscreen: () => void;
      }
    ).requestFullscreen();
  }
  exitFullscreen(): void {
    (
      this.elementRef.nativeElement as unknown as { exitFullscreen: () => void }
    ).exitFullscreen();
  }
  getVideoElement(): void {
    (
      this.elementRef.nativeElement as unknown as {
        getVideoElement: () => void;
      }
    ).getVideoElement();
  }
  getState(): void {
    (
      this.elementRef.nativeElement as unknown as { getState: () => void }
    ).getState();
  }
}

// templates/react/Video/Video.jsx
import React from 'react';
import clsx from 'clsx';
import './Video.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 *
 * @example
 * ```jsx
 * // Basic usage
 * <Video src="/demo.mp4" poster="/demo.jpg" title="Demo" controls="full" />
 *
 * // Using ref methods
 * const videoRef = React.useRef(null);
 * <button onClick={() => videoRef.current?.play()}>Play</button>
 * <Video ref={videoRef} src="/demo.mp4" />
 * ```
 *
 * @typedef {Object} VideoProps
 * @property {string} [controls] - The set of controls to display: none | standard | full
 * @property {string} [src] - The video source URL
 * @property {string} [poster] - The poster image URL shown before playback
 * @property {string} [title] - The video title
 * @property {string} [thumbnails] - URL to a WebVTT file for timeline thumbnail previews
 * @property {boolean} [playing] - Whether the video is currently playing
 * @property {boolean} [muted] - Whether the video is muted
 * @property {number} [volume] - The volume level from 0 to 1
 * @property {boolean} [autoplay] - Automatically start playback when connected
 * @property {boolean} [loop] - Restart playback when the video ends
 * @property {boolean} [autoplay-muted] - Autoplay in a muted state
 * @property {boolean} [autoplay-on-visible] - Resume playback when scrolled back into view
 * @property {string} [preload] - The browser preload strategy: auto | metadata | none
 * @property {string} [icon-library] - The icon library used for built-in control icons
 * @property {function} [onTimeupdate] - Event fired when the time changes
 * @property {function} [onPlay] - Event fired when playback begins
 * @property {function} [onPause] - Event fired when playback stops
 * @property {function} [onVolumechange] - Event fired when the volume changes
 * @property {function} [onError] - Event fired when an error occurs
 * @property {function} [onEnded] - Event fired when playback ends
 * @property {function} [onLoadedmetadata] - Event fired when metadata has been loaded
 */

export const Video = React.forwardRef(
  (
    {
      children,
      className,
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
      ...props
    },
    ref
  ) => {
    const videoRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        play: () => {
          if (videoRef.current && typeof videoRef.current.play === 'function') {
            videoRef.current.play();
          }
        },
        pause: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.pause === 'function'
          ) {
            videoRef.current.pause();
          }
        },
        togglePlay: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.togglePlay === 'function'
          ) {
            videoRef.current.togglePlay();
          }
        },
        toggleMute: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.toggleMute === 'function'
          ) {
            videoRef.current.toggleMute();
          }
        },
        seek: (time) => {
          if (videoRef.current && typeof videoRef.current.seek === 'function') {
            videoRef.current.seek(time);
          }
        },
        setVolume: (volume) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setVolume === 'function'
          ) {
            videoRef.current.setVolume(volume);
          }
        },
        setPlaybackRate: (rate) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setPlaybackRate === 'function'
          ) {
            videoRef.current.setPlaybackRate(rate);
          }
        },
        requestFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.requestFullscreen === 'function'
          ) {
            videoRef.current.requestFullscreen();
          }
        },
        exitFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.exitFullscreen === 'function'
          ) {
            videoRef.current.exitFullscreen();
          }
        },
        getVideoElement: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getVideoElement === 'function'
          ) {
            videoRef.current.getVideoElement();
          }
        },
        getState: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getState === 'function'
          ) {
            videoRef.current.getState();
          }
        },
        get element() {
          return videoRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = videoRef.current;
      if (!el) return;

      const handleTimeupdate = (e) => {
        if (onTimeupdate) onTimeupdate(e);
      };

      const handlePlay = (e) => {
        if (onPlay) onPlay(e);
      };

      const handlePause = (e) => {
        if (onPause) onPause(e);
      };

      const handleVolumechange = (e) => {
        if (onVolumechange) onVolumechange(e);
      };

      const handleError = (e) => {
        if (onError) onError(e);
      };

      const handleEnded = (e) => {
        if (onEnded) onEnded(e);
      };

      const handleLoadedmetadata = (e) => {
        if (onLoadedmetadata) onLoadedmetadata(e);
      };

      el.addEventListener('timeupdate', handleTimeupdate);
      el.addEventListener('play', handlePlay);
      el.addEventListener('pause', handlePause);
      el.addEventListener('volumechange', handleVolumechange);
      el.addEventListener('error', handleError);
      el.addEventListener('ended', handleEnded);
      el.addEventListener('loadedmetadata', handleLoadedmetadata);

      return () => {
        el.removeEventListener('timeupdate', handleTimeupdate);
        el.removeEventListener('play', handlePlay);
        el.removeEventListener('pause', handlePause);
        el.removeEventListener('volumechange', handleVolumechange);
        el.removeEventListener('error', handleError);
        el.removeEventListener('ended', handleEnded);
        el.removeEventListener('loadedmetadata', handleLoadedmetadata);
      };
    }, [
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
    ]);

    return (
      <wa-video ref={videoRef} class={clsx('Video', className)} {...props}>
        {children}
      </wa-video>
    );
  }
);

Video.displayName = 'Video';
