// templates/vue/CopyButton/CopyButton.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './CopyButton.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/copy-button/copy-button.js'));
}

/**
 * Copies text data to the clipboard when clicked
 */
export interface CopyButtonProps {
  value?: string;
  from?: string;
  disabled?: boolean;
  'copy-label'?: string;
  'success-label'?: string;
  'error-label'?: string;
  'feedback-duration'?: number;
  'tooltip-placement'?: 'top' | 'right' | 'bottom' | 'left';
}

const props = defineProps<CopyButtonProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-copy': [event: CustomEvent];
  'wa-error': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaCopy = (e: Event) => emit('wa-copy', e as CustomEvent);
const handleWaError = (e: Event) => emit('wa-error', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-copy', handleWaCopy);
  el.addEventListener('wa-error', handleWaError);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-copy', handleWaCopy);
  el.removeEventListener('wa-error', handleWaError);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-copy-button
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-copy-button>
</template>

// templates/react/CopyButton/CopyButton.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './CopyButton.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/copy-button/copy-button.js'));
}

/**
 * Copies text data to the clipboard when clicked
 *
 * @example
 * ```tsx
 * // Basic usage
 * <CopyButton />
 *
 * // With event handlers
 * <CopyButton
 *   onCopy={(e) => console.log(e)} />
 *
 * ```
 */
export interface CopyButtonProps extends Omit<HTMLAttributes<HTMLElement>, 'onCopy' | 'onError' | 'dir'> {

  /** The text to copy */
  value?: string;

  /** Element selector to copy text from */
  from?: string;

  /** Disables the button */
  disabled?: boolean;

  /** Tooltip label for copy state */
  'copy-label'?: string;

  /** Tooltip label for success state */
  'success-label'?: string;

  /** Tooltip label for error state */
  'error-label'?: string;

  /** Duration of feedback state in milliseconds */
  'feedback-duration'?: number;

  /** Tooltip position */
  'tooltip-placement'?: 'top' | 'right' | 'bottom' | 'left';

  /** Emitted when the data has been copied. */
  onCopy?: (event: CustomEvent) => void;

  /** Emitted when the data could not be copied. */
  onError?: (event: CustomEvent) => void;
}

export interface CopyButtonRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const CopyButton = forwardRef<CopyButtonRef, CopyButtonProps>(
  ({ children, className, onCopy, onError, ...props }, ref) => {
    const copybuttonRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return copybuttonRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = copybuttonRef.current;
      if (!el) return;

      const handleWaCopy = (e: Event) => {
        if (onCopy) onCopy(e as CustomEvent);
      };

      const handleWaError = (e: Event) => {
        if (onError) onError(e as CustomEvent);
      };

      el.addEventListener('wa-copy', handleWaCopy);
      el.addEventListener('wa-error', handleWaError);

      return () => {
        el.removeEventListener('wa-copy', handleWaCopy);
        el.removeEventListener('wa-error', handleWaError);
      };
    }, [onCopy, onError]);

    return (
      <wa-copy-button
        ref={copybuttonRef}
        class={clsx('CopyButton', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-copy-button>
    );
  }
);

CopyButton.displayName = 'CopyButton';
