// docs/src/components/ui/QrCode/QrCode.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/qr-code/qr-code.js';
import './QrCode.css';

/**
 * Generates QR codes for encoding text, URLs, or data
 *
 * @example
 * ```tsx
 * // Basic usage
 * <QrCode />
 *
 * // With event handlers
 * <QrCode />
 *
 * ```
 */
export interface QrCodeProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** The data to encode */
  value?: string;

  /** Accessible label */
  label?: string;

  /** Size in pixels */
  size?: number;

  /**
   * Fill color
   *
   * @deprecated Set the CSS color property on the QR code instead.
   */
  fill?: string;

  /**
   * Background color
   *
   * @deprecated Set the CSS background-color property on the QR code instead.
   */
  background?: string;

  /** Corner radius */
  radius?: number;

  /** Error correction level */
  'error-correction'?: 'L' | 'M' | 'Q' | 'H';

  /** URL or data URI of an image, such as a logo, drawn in the centre of the code */
  image?: string;

  /** Colour filled behind the centre image, so the code does not show through a transparent one */
  'image-background'?: string;

  /** Share of the code's error-correction capacity the centre image may take, from 0 to 1 (0.5 when unset); higher values scan less reliably */
  'image-coverage'?: number;
}

export interface QrCodeRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const QrCode = forwardRef<QrCodeRef, QrCodeProps>(
  ({ children, className, ...props }, ref) => {
    const qrcodeRef = useRef<HTMLElement & {}>(null);

    const setQrcodeRef = useCallback((el: typeof qrcodeRef.current) => {
      qrcodeRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return qrcodeRef.current;
        },
      }),
      []
    );

    return (
      <wa-qr-code
        ref={setQrcodeRef}
        class={clsx('QrCode', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-qr-code>
    );
  }
);

QrCode.displayName = 'QrCode';

// templates/angular/QrCode/qr-code.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/qr-code/qr-code.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/qr-code/qr-code.js'));
}

/**
 * Generates QR codes for encoding text, URLs, or data
 *
 * @see https://webawesome.com/docs/components/qr-code
 */
@Component({
  selector: 'k-qr-code',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-qr-code
      #element
      [attr.value]="value"
      [attr.label]="label"
      [attr.size]="size"
      [attr.fill]="fill"
      [attr.background]="background"
      [attr.radius]="radius"
      [attr.error-correction]="errorCorrection"
      [attr.image]="image"
      [attr.image-background]="imageBackground"
      [attr.image-coverage]="imageCoverage"
    >
      <ng-content />
    </wa-qr-code>
  `,
  styleUrl: './qr-code.component.css',
})
export class QrCodeComponent implements AfterViewInit {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The data to encode */
  @Input() value?: string;
  /** Accessible label */
  @Input() label?: string;
  /** Size in pixels */
  @Input() size?: number;
  /**
   * Fill color
   *
   * @deprecated Set the CSS color property on the QR code instead.
   */
  @Input() fill?: string;
  /**
   * Background color
   *
   * @deprecated Set the CSS background-color property on the QR code instead.
   */
  @Input() background?: string;
  /** Corner radius */
  @Input() radius?: number;
  /** Error correction level */
  @Input() errorCorrection?: 'L' | 'M' | 'Q' | 'H';
  /** URL or data URI of an image, such as a logo, drawn in the centre of the code */
  @Input() image?: string;
  /** Colour filled behind the centre image, so the code does not show through a transparent one */
  @Input() imageBackground?: string;
  /** Share of the code's error-correction capacity the centre image may take, from 0 to 1 (0.5 when unset); higher values scan less reliably */
  @Input() imageCoverage?: number;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}
