// templates/react/FormatNumber/FormatNumber.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './FormatNumber.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-number/format-number.js'));
}

/**
 * Formats a number using the Intl.NumberFormat API
 *
 * @example
 * ```tsx
 * // Basic usage
 * <FormatNumber />
 *
 * // With event handlers
 * <FormatNumber />
 *
 * ```
 */
export interface FormatNumberProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The number to format */
  value?: number;

  /** The formatting style */
  type?: 'currency' | 'decimal' | 'percent';

  /** The currency to use (ISO 4217) */
  currency?: string;

  /** How to display the currency */
  'currency-display'?: 'symbol' | 'narrowSymbol' | 'code' | 'name';

  /** Minimum integer digits */
  'minimum-integer-digits'?: number;

  /** Minimum fraction digits */
  'minimum-fraction-digits'?: number;

  /** Maximum fraction digits */
  'maximum-fraction-digits'?: number;

  /** Minimum significant digits */
  'minimum-significant-digits'?: number;

  /** Maximum significant digits */
  'maximum-significant-digits'?: number;

  /** Disables grouping separators */
  'without-grouping'?: boolean;

  /** The locale to use when formatting */
  lang?: string;
}

export interface FormatNumberRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const FormatNumber = forwardRef<FormatNumberRef, FormatNumberProps>(
  ({ children, className, ...props }, ref) => {
    const formatnumberRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return formatnumberRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-format-number
        ref={formatnumberRef}
        class={clsx('FormatNumber', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-format-number>
    );
  }
);

FormatNumber.displayName = 'FormatNumber';

// templates/vue/FormatNumber/FormatNumber.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './FormatNumber.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/format-number/format-number.js'));
}

/**
 * Formats a number using the Intl.NumberFormat API
 */
export interface FormatNumberProps {
  value?: number;
  type?: 'currency' | 'decimal' | 'percent';
  currency?: string;
  'currency-display'?: 'symbol' | 'narrowSymbol' | 'code' | 'name';
  'minimum-integer-digits'?: number;
  'minimum-fraction-digits'?: number;
  'maximum-fraction-digits'?: number;
  'minimum-significant-digits'?: number;
  'maximum-significant-digits'?: number;
  'without-grouping'?: boolean;
  lang?: string;
}

const props = defineProps<FormatNumberProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-format-number
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-format-number>
</template>
