// docs/src/components/ui/Button/Button.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/button/button.js';
import './Button.css';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Buttons represent actions that are available to the user
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Button />
 *
 * // With event handlers
 * <Button
 *   onBlur={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<ButtonRef>(null);
 * <button onClick={() => ref.current?.click()}>Call Method</button>
 * <Button ref={ref} />
 * ```
 */
export interface ButtonProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onBlur' | 'onFocus' | 'onInvalid' | 'dir'
> {
  /** Semantic variant of the button */
  variant?: 'neutral' | 'brand' | 'success' | 'warning' | 'danger';

  /** Visual appearance style */
  appearance?: 'accent' | 'filled-outlined' | 'filled' | 'outlined' | 'plain';

  /** Button size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Gives the button rounded edges */
  pill?: boolean;

  /** Disables the button */
  disabled?: boolean;

  /** Shows a loading indicator */
  loading?: boolean;

  /** Adds a dropdown indicator caret */
  'with-caret'?: boolean;

  /** Makes the button work like a link */
  href?: string;

  /** Link target (when href is set) */
  target?: '_blank' | '_self' | '_parent' | '_top';

  /** Download filename (when href is set) */
  download?: string;

  /** Link relationship (when href is set) */
  rel?: string;

  /** The button's type for form submission */
  type?: 'button' | 'submit' | 'reset';

  /** The name of the button for form submission */
  name?: string;

  /** The value of the button for form submission */
  value?: string;

  /** Override the form's action attribute */
  formaction?: string;

  /** Override the form's enctype attribute */
  formenctype?: string;

  /** Override the form's method attribute */
  formmethod?: string;

  /** Bypass form validation when this button submits */
  formnovalidate?: boolean;

  /** Override the form's target attribute */
  formtarget?: string;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the button loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the button gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface ButtonRef {
  /** Simulates a click on the button. */
  click: () => void;

  /** Sets focus on the button. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the button. */
  blur: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Button = forwardRef<ButtonRef, ButtonProps>(
  ({ children, className, onBlur, onFocus, onInvalid, ...props }, ref) => {
    const buttonRef = useRef<
      HTMLElement & {
        click?: () => void;
        focus?: (options: FocusOptions) => void;
        blur?: () => void;
      }
    >(null);

    const setButtonRef = useCallback((el: typeof buttonRef.current) => {
      buttonRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        click: () => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.click === 'function'
          ) {
            buttonRef.current.click();
          }
        },
        focus: (options: FocusOptions) => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.focus === 'function'
          ) {
            buttonRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            buttonRef.current &&
            typeof buttonRef.current.blur === 'function'
          ) {
            buttonRef.current.blur();
          }
        },
        get element() {
          return buttonRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = buttonRef.current;
      if (!el) return;

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onBlur, onFocus, onInvalid]);

    return (
      <wa-button
        ref={setButtonRef}
        class={clsx('Button', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-button>
    );
  }
);

Button.displayName = 'Button';

// templates/angular/Button/button.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/button/button.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/button/button.js'));
}

/**
 * Buttons represent actions that are available to the user
 *
 * @see https://webawesome.com/docs/components/button
 */
@Component({
  selector: 'k-button',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-button
      #element
      [attr.variant]="variant"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.pill]="pill || null"
      [attr.disabled]="disabled || null"
      [attr.loading]="loading || null"
      [attr.with-caret]="withCaret || null"
      [attr.href]="href"
      [attr.target]="target"
      [attr.download]="download"
      [attr.rel]="rel"
      [attr.type]="type"
      [attr.name]="name"
      [attr.value]="value"
      [attr.formaction]="formaction"
      [attr.formenctype]="formenctype"
      [attr.formmethod]="formmethod"
      [attr.formnovalidate]="formnovalidate || null"
      [attr.formtarget]="formtarget"
      [attr.title]="title"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-button>
  `,
  styleUrl: './button.component.css',
})
export class ButtonComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Semantic variant of the button */
  @Input() variant?: 'neutral' | 'brand' | 'success' | 'warning' | 'danger';
  /** Visual appearance style */
  @Input() appearance?:
    'accent' | 'filled-outlined' | 'filled' | 'outlined' | 'plain';
  /** Button size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Gives the button rounded edges */
  @Input() pill?: boolean;
  /** Disables the button */
  @Input() disabled?: boolean;
  /** Shows a loading indicator */
  @Input() loading?: boolean;
  /** Adds a dropdown indicator caret */
  @Input() withCaret?: boolean;
  /** Makes the button work like a link */
  @Input() href?: string;
  /** Link target (when href is set) */
  @Input() target?: '_blank' | '_self' | '_parent' | '_top';
  /** Download filename (when href is set) */
  @Input() download?: string;
  /** Link relationship (when href is set) */
  @Input() rel?: string;
  /** The button's type for form submission */
  @Input() type?: 'button' | 'submit' | 'reset';
  /** The name of the button for form submission */
  @Input() name?: string;
  /** The value of the button for form submission */
  @Input() value?: string;
  /** Override the form's action attribute */
  @Input() formaction?: string;
  /** Override the form's enctype attribute */
  @Input() formenctype?: string;
  /** Override the form's method attribute */
  @Input() formmethod?: string;
  /** Bypass form validation when this button submits */
  @Input() formnovalidate?: boolean;
  /** Override the form's target attribute */
  @Input() formtarget?: string;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  click(): void {
    (this.elementRef.nativeElement as unknown as { click: () => void }).click();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
