// .claude/skills/kigumi-vue-workspace/iteration-2/eval-2-dialog-form/with_skill/outputs/output.vue
<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Button, Dialog, Input, Select, Option, Textarea } from '@/components/ui';

const open = ref(false);
const loading = ref(false);

const form = reactive({
  name: '',
  email: '',
  role: '',
  notes: '',
});

function resetForm() {
  form.name = '';
  form.email = '';
  form.role = '';
  form.notes = '';
}

function handleCancel() {
  open.value = false;
}

async function handleSave() {
  loading.value = true;
  try {
    await fetch('/api/users', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form),
    });
    open.value = false;
    resetForm();
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <Button variant="brand" @click="open = true">New User</Button>

  <Dialog
    :open="open"
    label="Add User"
    @wa-hide="open = false"
    @wa-after-hide="resetForm"
  >
    <form class="wa-stack wa-gap-m" @submit.prevent="handleSave">
      <Input
        label="Name"
        required
        @input="(e: Event) => (form.name = (e.target as HTMLInputElement).value)"
      />
      <Input
        label="Email"
        type="email"
        required
        @input="(e: Event) => (form.email = (e.target as HTMLInputElement).value)"
      />
      <Select
        label="Role"
        required
        @input="(e: Event) => (form.role = (e.target as HTMLSelectElement).value)"
      >
        <Option value="admin">Admin</Option>
        <Option value="editor">Editor</Option>
        <Option value="viewer">Viewer</Option>
      </Select>
      <Textarea
        label="Notes"
        placeholder="Optional notes"
        @input="(e: Event) => (form.notes = (e.target as HTMLInputElement).value)"
      />
    </form>

    <div slot="footer" class="wa-cluster wa-justify-content-end wa-gap-s">
      <Button variant="neutral" @click="handleCancel">Cancel</Button>
      <Button variant="brand" :loading="loading" @click="handleSave">Save</Button>
    </div>
  </Dialog>
</template>

// .claude/skills/kigumi-compose-form-workspace/iteration-2/eval-2-login-form/with_skill/outputs/output.tsx
// Install missing components:
// npx kigumi add input switch button callout

import { useState, type FormEvent } from 'react';
import { Button, Callout, Input, Switch } from '@/components/ui';

export function LoginForm() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [remember, setRemember] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password, remember }),
      });
      if (!res.ok) throw new Error('Invalid email or password');
      window.location.href = '/dashboard';
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form
      className="wa-stack wa-gap-l"
      style={{ maxWidth: '400px', margin: '0 auto' }}
      onSubmit={handleSubmit}
    >
      <h1 style={{ textAlign: 'center' }}>Sign In</h1>

      {error && <Callout variant="danger">{error}</Callout>}

      <Input
        label="Email"
        name="email"
        type="email"
        required
        onInput={(e) => setEmail((e.target as HTMLInputElement).value)}
      />

      <Input
        label="Password"
        name="password"
        type="password"
        required
        password-toggle
        onInput={(e) => setPassword((e.target as HTMLInputElement).value)}
      />

      <div className="wa-cluster wa-justify-content-space-between wa-align-items-center">
        <Switch
          onChange={(e) => setRemember((e.target as HTMLInputElement).checked)}
        >
          Remember me
        </Switch>
        <a href="/forgot-password" style={{ fontSize: 'var(--wa-font-size-s)' }}>
          Forgot password?
        </a>
      </div>

      <Button variant="brand" type="submit" loading={loading} style={{ width: '100%' }}>
        Sign In
      </Button>
    </form>
  );
}
