// templates/angular/Switch/switch.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/switch/switch.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/switch/switch.js'));
}

/**
 * Switches allow the user to toggle an option on or off
 *
 * @see https://webawesome.com/docs/components/switch
 */
@Component({
  selector: 'k-switch',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-switch
      #element
      [attr.name]="name"
      [attr.value]="value"
      [attr.size]="size"
      [attr.disabled]="disabled || null"
      [attr.checked]="checked || null"
      [attr.required]="required || null"
      [attr.hint]="hint"
      [attr.title]="title"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-switch>
  `,
  styleUrl: './switch.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => SwitchComponent),
      multi: true,
    },
  ],
})
export class SwitchComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Form field name */
  @Input() name?: string;
  /** Form value when checked */
  @Input() value?: string;
  /** Switch size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Disables the switch */
  @Input() disabled?: boolean;
  /** Whether the switch is on */
  @Input() checked?: boolean;
  /** Makes the switch required */
  @Input() required?: boolean;
  /** Hint text */
  @Input() hint?: string;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() change = new EventEmitter<Event>();
  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleCheckedChange = () =>
      this.onChangeCallback((el as unknown as { checked: boolean }).checked);
    el.addEventListener('change', handleCheckedChange);
    this.cleanups.push(() =>
      el.removeEventListener('change', handleCheckedChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { checked: boolean }
      ).checked = !!value;
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  click(): void {
    (this.elementRef.nativeElement as unknown as { click: () => void }).click();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// docs/src/components/ui/Switch/Switch.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/switch/switch.js';
import './Switch.css';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Switches allow the user to toggle an option on or off
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Switch />
 *
 * // With event handlers
 * <Switch
 *   onChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<SwitchRef>(null);
 * <button onClick={() => ref.current?.click()}>Call Method</button>
 * <Switch ref={ref} />
 * ```
 */
export interface SwitchProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onChange' | 'onInput' | 'onBlur' | 'onFocus' | 'onInvalid' | 'dir'
> {
  /** Form field name */
  name?: string;

  /** Form value when checked */
  value?: string;

  /** Switch size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Disables the switch */
  disabled?: boolean;

  /** Whether the switch is on */
  checked?: boolean;

  /** Makes the switch required */
  required?: boolean;

  /** Hint text */
  hint?: string;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the control's checked state changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the control receives input. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface SwitchRef {
  /** Simulates a click on the switch. */
  click: () => void;

  /** Sets focus on the switch. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the switch. */
  blur: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Switch = forwardRef<SwitchRef, SwitchProps>(
  (
    {
      children,
      className,
      onChange,
      onInput,
      onBlur,
      onFocus,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const switchRef = useRef<
      HTMLElement & {
        click?: () => void;
        focus?: (options: FocusOptions) => void;
        blur?: () => void;
      }
    >(null);

    const setSwitchRef = useCallback((el: typeof switchRef.current) => {
      switchRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        click: () => {
          if (
            switchRef.current &&
            typeof switchRef.current.click === 'function'
          ) {
            switchRef.current.click();
          }
        },
        focus: (options: FocusOptions) => {
          if (
            switchRef.current &&
            typeof switchRef.current.focus === 'function'
          ) {
            switchRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            switchRef.current &&
            typeof switchRef.current.blur === 'function'
          ) {
            switchRef.current.blur();
          }
        },
        get element() {
          return switchRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = switchRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('change', handleChange);
      el.addEventListener('input', handleInput);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('change', handleChange);
        el.removeEventListener('input', handleInput);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onChange, onInput, onBlur, onFocus, onInvalid]);

    return (
      <wa-switch
        ref={setSwitchRef}
        class={clsx('Switch', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-switch>
    );
  }
);

Switch.displayName = 'Switch';
