// templates/react/TabGroup/TabGroup.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './TabGroup.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab-group/tab-group.js'));
}

/**
 * Tab groups organize content into a container that shows one section at a time
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TabGroup />
 *
 * // With event handlers
 * <TabGroup
 *   onTabShow={(e) => console.log(e)} />
 *
 * ```
 */
export interface TabGroupProps extends Omit<HTMLAttributes<HTMLElement>, 'onTabShow' | 'onTabHide' | 'dir'> {

  /** Tab position */
  placement?: 'top' | 'bottom' | 'start' | 'end';

  /** Panel activation method */
  activation?: 'auto' | 'manual';

  /** Disables scroll buttons */
  'without-scroll-controls'?: boolean;

  /** The name of the active tab */
  active?: string;

  /** Emitted when a tab is shown. */
  onTabShow?: (event: CustomEvent) => void;

  /** Emitted when a tab is hidden. */
  onTabHide?: (event: CustomEvent) => void;
}

export interface TabGroupRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const TabGroup = forwardRef<TabGroupRef, TabGroupProps>(
  ({ children, className, onTabShow, onTabHide, ...props }, ref) => {
    const tabgroupRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return tabgroupRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = tabgroupRef.current;
      if (!el) return;

      const handleWaTabShow = (e: Event) => {
        if (onTabShow) onTabShow(e as CustomEvent);
      };

      const handleWaTabHide = (e: Event) => {
        if (onTabHide) onTabHide(e as CustomEvent);
      };

      el.addEventListener('wa-tab-show', handleWaTabShow);
      el.addEventListener('wa-tab-hide', handleWaTabHide);

      return () => {
        el.removeEventListener('wa-tab-show', handleWaTabShow);
        el.removeEventListener('wa-tab-hide', handleWaTabHide);
      };
    }, [onTabShow, onTabHide]);

    return (
      <wa-tab-group
        ref={tabgroupRef}
        class={clsx('TabGroup', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tab-group>
    );
  }
);

TabGroup.displayName = 'TabGroup';

// templates/angular/TabGroup/tab-group.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input, Output, EventEmitter, OnDestroy } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/tab-group/tab-group.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab-group/tab-group.js'));
}

/**
 * Tab groups organize content into a container that shows one section at a time
 *
 * @see https://webawesome.com/docs/components/tab-group
 */
@Component({
  selector: 'k-tab-group',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-tab-group
        #element
        [attr.placement]="placement"
        [attr.activation]="activation"
        [attr.without-scroll-controls]="withoutScrollControls || null"
        [attr.active]="active">
      <ng-content />
    </wa-tab-group>
  `,
  styleUrl: './tab-group.component.css',
})
export class TabGroupComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Tab position */
  @Input() placement?: 'top' | 'bottom' | 'start' | 'end';
  /** Panel activation method */
  @Input() activation?: 'auto' | 'manual';
  /** Disables scroll buttons */
  @Input() withoutScrollControls?: boolean;
  /** The name of the active tab */
  @Input() active?: string;

  @Output() tabShow = new EventEmitter<CustomEvent>();
  @Output() tabHide = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleTabShow = (e: Event) => this.tabShow.emit(e as CustomEvent);
    el.addEventListener('wa-tab-show', handleTabShow);
    this.cleanups.push(() => el.removeEventListener('wa-tab-show', handleTabShow));
    const handleTabHide = (e: Event) => this.tabHide.emit(e as CustomEvent);
    el.addEventListener('wa-tab-hide', handleTabHide);
    this.cleanups.push(() => el.removeEventListener('wa-tab-hide', handleTabHide));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }
}
