// templates/react/Toast/Toast.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaToast from '@awesome.me/webawesome/dist/components/toast/toast.js';
import type { ToastCreateOptions } from '@awesome.me/webawesome/dist/components/toast/toast.js';
import './Toast.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/toast/toast.js'));
}

/**
 * Container that manages and stacks lightweight notification banners at a chosen screen edge
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Toast />
 *
 * // With event handlers
 * <Toast />
 *
 * ```
 */
export interface ToastProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {
  /** Screen corner or edge where notifications are anchored */
  placement?:
    | 'top-start'
    | 'top-center'
    | 'top-end'
    | 'bottom-start'
    | 'bottom-center'
    | 'bottom-end';
}

export interface ToastRef {
  create: (message: string, options?: ToastCreateOptions) => void;
  /** Reference to the underlying HTML element */
  element: WaToast | null;
}

export const Toast = forwardRef<ToastRef, ToastProps>(
  ({ children, className, ...props }, ref) => {
    const toastRef = useRef<WaToast | null>(null);
    const setToastRef = useCallback((el: WaToast | null) => {
      toastRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        create: (message: string, options?: ToastCreateOptions) => {
          if (
            toastRef.current &&
            typeof toastRef.current.create === 'function'
          ) {
            toastRef.current.create(message, options);
          }
        },
        get element() {
          return toastRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-toast
        ref={setToastRef}
        class={clsx('Toast', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-toast>
    );
  }
);

Toast.displayName = 'Toast';

// templates/vue/Toast/Toast.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import type { ToastCreateOptions } from '@awesome.me/webawesome/dist/components/toast/toast.js';
import './Toast.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/toast/toast.js'));
}

/**
 * Container that manages and stacks lightweight notification banners at a chosen screen edge
 */
export interface ToastProps {
  placement?: 'top-start' | 'top-center' | 'top-end' | 'bottom-start' | 'bottom-center' | 'bottom-end';
}

const props = defineProps<ToastProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  create: (message: string, options: ToastCreateOptions) => (elementRef.value as any)?.create?.(message, options),
  element: elementRef,
});
</script>

<template>
  <wa-toast
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-toast>
</template>
