// templates/angular/Dropdown/dropdown.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/dropdown/dropdown.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaSelectEvent } from '@awesome.me/webawesome/dist/events/select.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/dropdown/dropdown.js'));
}

/**
 * Dropdowns expose additional content that pops up when the user interacts with a trigger
 *
 * @see https://webawesome.com/docs/components/dropdown
 */
@Component({
  selector: 'k-dropdown',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-dropdown
      #element
      [attr.open]="open || null"
      [attr.placement]="placement"
      [attr.disabled]="disabled || null"
      [attr.stay-open-on-select]="stayOpenOnSelect || null"
      [attr.distance]="distance"
      [attr.skidding]="skidding"
      [attr.hoist]="hoist || null"
      [attr.size]="size"
    >
      <ng-content />
    </wa-dropdown>
  `,
  styleUrl: './dropdown.component.css',
})
export class DropdownComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Indicates whether the dropdown is open */
  @Input() open?: boolean;
  /** Preferred placement of the dropdown panel */
  @Input() placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** Disables the dropdown */
  @Input() disabled?: boolean;
  /** Keeps the dropdown open when an item is selected */
  @Input() stayOpenOnSelect?: boolean;
  /** Distance from the panel to the trigger */
  @Input() distance?: number;
  /** Offset along the trigger */
  @Input() skidding?: number;
  /** Hoists the dropdown panel to the body */
  @Input() hoist?: boolean;
  /** Dropdown size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  @Output() show = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hide = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();
  @Output() select = new EventEmitter<WaSelectEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShow = (e: Event) => this.show.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShow);
    this.cleanups.push(() => el.removeEventListener('wa-show', handleShow));
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHide = (e: Event) => this.hide.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHide);
    this.cleanups.push(() => el.removeEventListener('wa-hide', handleHide));
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
    const handleSelect = (e: Event) => this.select.emit(e as WaSelectEvent);
    el.addEventListener('wa-select', handleSelect);
    this.cleanups.push(() => el.removeEventListener('wa-select', handleSelect));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }
}

// docs/src/components/ui/Dropdown/Dropdown.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/dropdown/dropdown.js';
import './Dropdown.css';
import type { WaAfterHideEvent } from '@awesome.me/webawesome-pro/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome-pro/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome-pro/dist/events/hide.js';
import type { WaSelectEvent } from '@awesome.me/webawesome-pro/dist/events/select.js';
import type { WaShowEvent } from '@awesome.me/webawesome-pro/dist/events/show.js';

/**
 * Dropdowns expose additional content that pops up when the user interacts with a trigger
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Dropdown />
 *
 * // With event handlers
 * <Dropdown
 *   onShow={(e) => console.log(e)} />
 *
 * ```
 */
export interface DropdownProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'onSelect' | 'dir'
> {
  /** Indicates whether the dropdown is open */
  open?: boolean;

  /** Dropdown size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Preferred placement of the dropdown panel */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';

  /** Disables the dropdown */
  disabled?: boolean;

  /** Keeps the dropdown open when an item is selected */
  'stay-open-on-select'?: boolean;

  /** Distance from the panel to the trigger */
  distance?: number;

  /** Offset along the trigger */
  skidding?: number;

  /** Hoists the dropdown panel to the body */
  hoist?: boolean;

  /** Emitted when the dropdown is about to show. */
  onShow?: (event: WaShowEvent) => void;

  /** Emitted after the dropdown has been shown. */
  onAfterShow?: (event: WaAfterShowEvent) => void;

  /** Emitted when the dropdown is about to hide. */
  onHide?: (event: WaHideEvent) => void;

  /** Emitted after the dropdown has been hidden. */
  onAfterHide?: (event: WaAfterHideEvent) => void;

  /** Emitted when an item in the dropdown is selected. */
  onSelect?: (event: WaSelectEvent) => void;
}

export interface DropdownRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Dropdown = forwardRef<DropdownRef, DropdownProps>(
  (
    {
      children,
      className,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onSelect,
      ...props
    },
    ref
  ) => {
    const dropdownRef = useRef<HTMLElement & {}>(null);

    const setDropdownRef = useCallback((el: typeof dropdownRef.current) => {
      dropdownRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return dropdownRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = dropdownRef.current;
      if (!el) return;

      const handleShow = (e: Event) => {
        if (onShow) onShow(e as WaShowEvent);
      };

      const handleAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as WaAfterShowEvent);
      };

      const handleHide = (e: Event) => {
        if (onHide) onHide(e as WaHideEvent);
      };

      const handleAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as WaAfterHideEvent);
      };

      const handleSelect = (e: Event) => {
        if (onSelect) onSelect(e as WaSelectEvent);
      };

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);
      el.addEventListener('wa-select', handleSelect);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
        el.removeEventListener('wa-select', handleSelect);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide, onSelect]);

    return (
      <wa-dropdown
        ref={setDropdownRef}
        class={clsx('Dropdown', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-dropdown>
    );
  }
);

Dropdown.displayName = 'Dropdown';
