// templates/react/Video/Video.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaVideo from '@awesome.me/webawesome/dist/components/video/video.js';
import './Video.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Video />
 *
 * // With event handlers
 * <Video
 *   onTimeupdate={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<VideoRef>(null);
 * <button onClick={() => ref.current?.play()}>Call Method</button>
 * <Video ref={ref} />
 * ```
 */
export interface VideoProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onTimeupdate'
  | 'onPlay'
  | 'onPause'
  | 'onVolumechange'
  | 'onError'
  | 'onEnded'
  | 'onLoadedmetadata'
  | 'dir'
> {
  /** The set of controls to display */
  controls?: 'none' | 'standard' | 'full';

  /** The video source URL */
  src?: string;

  /** The poster image URL shown before playback */
  poster?: string;

  /** The video title */
  title?: string;

  /** URL to a WebVTT file for timeline thumbnail previews */
  thumbnails?: string;

  /** Whether the video is currently playing */
  playing?: boolean;

  /** Whether the video is muted */
  muted?: boolean;

  /** The volume level from 0 to 1 */
  volume?: number;

  /** Automatically start playback when connected */
  autoplay?: boolean;

  /** Restart playback when the video ends */
  loop?: boolean;

  /** Autoplay in a muted state */
  'autoplay-muted'?: boolean;

  /** Resume playback when scrolled back into view */
  'autoplay-on-visible'?: boolean;

  /** The browser preload strategy */
  preload?: 'auto' | 'metadata' | 'none';

  /** The icon library used for built-in control icons */
  'icon-library'?: string;

  onTimeupdate?: (event: CustomEvent) => void;

  onPlay?: (event: CustomEvent) => void;

  onPause?: (event: CustomEvent) => void;

  onVolumechange?: (event: CustomEvent) => void;

  onError?: (event: Event) => void;

  onEnded?: (event: CustomEvent) => void;

  onLoadedmetadata?: (event: CustomEvent) => void;
}

export interface VideoRef {
  play: () => void;

  pause: () => void;

  togglePlay: () => void;

  toggleMute: () => void;

  seek: (time: number) => void;

  setVolume: (volume: number) => void;

  setPlaybackRate: (rate: number) => void;

  requestFullscreen: () => void;

  exitFullscreen: () => void;

  getVideoElement: () => void;

  getState: () => void;
  /** Reference to the underlying HTML element */
  element: WaVideo | null;
}

export const Video = forwardRef<VideoRef, VideoProps>(
  (
    {
      children,
      className,
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
      ...props
    },
    ref
  ) => {
    const videoRef = useRef<WaVideo | null>(null);
    const setVideoRef = useCallback((el: WaVideo | null) => {
      videoRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        play: () => {
          if (videoRef.current && typeof videoRef.current.play === 'function') {
            videoRef.current.play();
          }
        },
        pause: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.pause === 'function'
          ) {
            videoRef.current.pause();
          }
        },
        togglePlay: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.togglePlay === 'function'
          ) {
            videoRef.current.togglePlay();
          }
        },
        toggleMute: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.toggleMute === 'function'
          ) {
            videoRef.current.toggleMute();
          }
        },
        seek: (time: number) => {
          if (videoRef.current && typeof videoRef.current.seek === 'function') {
            videoRef.current.seek(time);
          }
        },
        setVolume: (volume: number) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setVolume === 'function'
          ) {
            videoRef.current.setVolume(volume);
          }
        },
        setPlaybackRate: (rate: number) => {
          if (
            videoRef.current &&
            typeof videoRef.current.setPlaybackRate === 'function'
          ) {
            videoRef.current.setPlaybackRate(rate);
          }
        },
        requestFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.requestFullscreen === 'function'
          ) {
            videoRef.current.requestFullscreen();
          }
        },
        exitFullscreen: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.exitFullscreen === 'function'
          ) {
            videoRef.current.exitFullscreen();
          }
        },
        getVideoElement: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getVideoElement === 'function'
          ) {
            videoRef.current.getVideoElement();
          }
        },
        getState: () => {
          if (
            videoRef.current &&
            typeof videoRef.current.getState === 'function'
          ) {
            videoRef.current.getState();
          }
        },
        get element() {
          return videoRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = videoRef.current;
      if (!el) return;

      const handleTimeupdate = (e: Event) => {
        if (onTimeupdate) onTimeupdate(e as CustomEvent);
      };

      const handlePlay = (e: Event) => {
        if (onPlay) onPlay(e as CustomEvent);
      };

      const handlePause = (e: Event) => {
        if (onPause) onPause(e as CustomEvent);
      };

      const handleVolumechange = (e: Event) => {
        if (onVolumechange) onVolumechange(e as CustomEvent);
      };

      const handleError = (e: Event) => {
        if (onError) onError(e as Event);
      };

      const handleEnded = (e: Event) => {
        if (onEnded) onEnded(e as CustomEvent);
      };

      const handleLoadedmetadata = (e: Event) => {
        if (onLoadedmetadata) onLoadedmetadata(e as CustomEvent);
      };

      el.addEventListener('timeupdate', handleTimeupdate);
      el.addEventListener('play', handlePlay);
      el.addEventListener('pause', handlePause);
      el.addEventListener('volumechange', handleVolumechange);
      el.addEventListener('error', handleError);
      el.addEventListener('ended', handleEnded);
      el.addEventListener('loadedmetadata', handleLoadedmetadata);

      return () => {
        el.removeEventListener('timeupdate', handleTimeupdate);
        el.removeEventListener('play', handlePlay);
        el.removeEventListener('pause', handlePause);
        el.removeEventListener('volumechange', handleVolumechange);
        el.removeEventListener('error', handleError);
        el.removeEventListener('ended', handleEnded);
        el.removeEventListener('loadedmetadata', handleLoadedmetadata);
      };
    }, [
      onTimeupdate,
      onPlay,
      onPause,
      onVolumechange,
      onError,
      onEnded,
      onLoadedmetadata,
    ]);

    return (
      <wa-video
        ref={setVideoRef}
        class={clsx('Video', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-video>
    );
  }
);

Video.displayName = 'Video';

// templates/vue/Video/Video.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Video.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/video/video.js'));
}

/**
 * Displays a video player with customizable controls, captions, and thumbnails
 */
export interface VideoProps {
  controls?: 'none' | 'standard' | 'full';
  src?: string;
  poster?: string;
  title?: string;
  thumbnails?: string;
  playing?: boolean;
  muted?: boolean;
  volume?: number;
  autoplay?: boolean;
  loop?: boolean;
  'autoplay-muted'?: boolean;
  'autoplay-on-visible'?: boolean;
  preload?: 'auto' | 'metadata' | 'none';
  'icon-library'?: string;
}

const props = defineProps<VideoProps>();

// Strip undefined and false props before forwarding to the web component.
// Vue boolean-prop coercion materializes absent optional Boolean props as
// `false`, but Web Awesome elements read attribute presence as truthy, so
// we must not forward `false` to <wa-*> (would render pill="" / loading="").
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (value !== undefined && value !== false) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  timeupdate: [event: CustomEvent];
  play: [event: CustomEvent];
  pause: [event: CustomEvent];
  volumechange: [event: CustomEvent];
  error: [event: CustomEvent];
  ended: [event: CustomEvent];
  loadedmetadata: [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleTimeupdate = (e: Event) => emit('timeupdate', e as CustomEvent);
const handlePlay = (e: Event) => emit('play', e as CustomEvent);
const handlePause = (e: Event) => emit('pause', e as CustomEvent);
const handleVolumechange = (e: Event) => emit('volumechange', e as CustomEvent);
const handleError = (e: Event) => emit('error', e as CustomEvent);
const handleEnded = (e: Event) => emit('ended', e as CustomEvent);
const handleLoadedmetadata = (e: Event) =>
  emit('loadedmetadata', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('timeupdate', handleTimeupdate);
  el.addEventListener('play', handlePlay);
  el.addEventListener('pause', handlePause);
  el.addEventListener('volumechange', handleVolumechange);
  el.addEventListener('error', handleError);
  el.addEventListener('ended', handleEnded);
  el.addEventListener('loadedmetadata', handleLoadedmetadata);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('timeupdate', handleTimeupdate);
  el.removeEventListener('play', handlePlay);
  el.removeEventListener('pause', handlePause);
  el.removeEventListener('volumechange', handleVolumechange);
  el.removeEventListener('error', handleError);
  el.removeEventListener('ended', handleEnded);
  el.removeEventListener('loadedmetadata', handleLoadedmetadata);
});

defineExpose({
  play: () => (elementRef.value as any)?.play?.(),
  pause: () => (elementRef.value as any)?.pause?.(),
  togglePlay: () => (elementRef.value as any)?.togglePlay?.(),
  toggleMute: () => (elementRef.value as any)?.toggleMute?.(),
  seek: (time: number) => (elementRef.value as any)?.seek?.(time),
  setVolume: (volume: number) => (elementRef.value as any)?.setVolume?.(volume),
  setPlaybackRate: (rate: number) =>
    (elementRef.value as any)?.setPlaybackRate?.(rate),
  requestFullscreen: () => (elementRef.value as any)?.requestFullscreen?.(),
  exitFullscreen: () => (elementRef.value as any)?.exitFullscreen?.(),
  getVideoElement: () => (elementRef.value as any)?.getVideoElement?.(),
  getState: () => (elementRef.value as any)?.getState?.(),
  element: elementRef,
});
</script>

<template>
  <wa-video ref="elementRef" v-bind="definedProps" :class="$attrs.class">
    <slot />
  </wa-video>
</template>
