// templates/react/Tab/Tab.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Tab.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab/tab.js'));
}

/**
 * Tabs are used inside tab groups to represent selectable tabs
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Tab />
 *
 * // With event handlers
 * <Tab />
 *
 * ```
 */
export interface TabProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** Associated panel name */
  panel?: string;

  /** Disables the tab */
  disabled?: boolean;
}

export interface TabRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Tab = forwardRef<TabRef, TabProps>(
  ({ children, className, ...props }, ref) => {
    const tabRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return tabRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-tab
        ref={tabRef}
        class={clsx('Tab', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tab>
    );
  }
);

Tab.displayName = 'Tab';

// templates/vue/Tab/Tab.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Tab.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tab/tab.js'));
}

/**
 * Tabs are used inside tab groups to represent selectable tabs
 */
export interface TabProps {
  panel?: string;
  disabled?: boolean;
}

const props = defineProps<TabProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-tab
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tab>
</template>
