// templates/angular/NumberInput/number-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/number-input/number-input.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/number-input/number-input.js'));
}

/**
 * Number inputs allow users to enter numeric values with optional step controls
 *
 * @see https://webawesome.com/docs/components/number-input
 */
@Component({
  selector: 'k-number-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-number-input
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.value]="value"
      [attr.min]="min"
      [attr.max]="max"
      [attr.step]="step"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.placeholder]="placeholder"
      [attr.size]="size"
      [attr.appearance]="appearance"
      [attr.pill]="pill || null"
      [attr.without-steppers]="withoutSteppers || null"
      [attr.title]="title"
      [attr.name]="name"
      [attr.readonly]="readonly || null"
      [attr.autocomplete]="autocomplete"
      [attr.autofocus]="autofocus || null"
      [attr.enterkeyhint]="enterkeyhint"
      [attr.inputmode]="inputmode"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-number-input>
  `,
  styleUrl: './number-input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => NumberInputComponent),
      multi: true,
    },
  ],
})
export class NumberInputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible label */
  @Input() label?: string;
  /** Descriptive hint text */
  @Input() hint?: string;
  /** Current value */
  @Input() value?: number;
  /** Minimum value */
  @Input() min?: number;
  /** Maximum value */
  @Input() max?: number;
  /** Step increment */
  @Input() step?: number;
  /** Disables the input */
  @Input() disabled?: boolean;
  /** Makes field mandatory */
  @Input() required?: boolean;
  /** Placeholder text */
  @Input() placeholder?: string;
  /** Input size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Visual appearance */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** Gives the input rounded edges */
  @Input() pill?: boolean;
  /** Hides the stepper buttons */
  @Input() withoutSteppers?: boolean;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** Makes the input readonly */
  @Input() readonly?: boolean;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Focuses the control on page load */
  @Input() autofocus?: boolean;
  /** Hint for Enter key label on virtual keyboards */
  @Input() enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';
  /** Hint for virtual keyboard type */
  @Input() inputmode?: 'numeric' | 'decimal';
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() beforeinput = new EventEmitter<InputEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBeforeinput = (e: Event) =>
      this.beforeinput.emit(e as InputEvent);
    el.addEventListener('beforeinput', handleBeforeinput);
    this.cleanups.push(() =>
      el.removeEventListener('beforeinput', handleBeforeinput)
    );
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  select(): void {
    (
      this.elementRef.nativeElement as unknown as { select: () => void }
    ).select();
  }
  stepUp(): void {
    (
      this.elementRef.nativeElement as unknown as { stepUp: () => void }
    ).stepUp();
  }
  stepDown(): void {
    (
      this.elementRef.nativeElement as unknown as { stepDown: () => void }
    ).stepDown();
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// docs/src/components/ui/NumberInput/NumberInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/number-input/number-input.js';
import './NumberInput.css';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

/**
 * Number inputs allow users to enter numeric values with optional step controls
 *
 * @example
 * ```tsx
 * // Basic usage
 * <NumberInput />
 *
 * // With event handlers
 * <NumberInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<NumberInputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <NumberInput ref={ref} />
 * ```
 */
export interface NumberInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onBlur'
  | 'onFocus'
  | 'onBeforeinput'
  | 'onInvalid'
  | 'dir'
> {
  /** Accessible label */
  label?: string;

  /** Descriptive hint text */
  hint?: string;

  /** Current value */
  value?: number;

  /** Minimum value */
  min?: number;

  /** Maximum value */
  max?: number;

  /** Step increment */
  step?: number;

  /** Disables the input */
  disabled?: boolean;

  /** Makes field mandatory */
  required?: boolean;

  /** Placeholder text */
  placeholder?: string;

  /** Input size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Visual appearance */
  appearance?: 'filled' | 'outlined' | 'filled-outlined';

  /** Gives the input rounded edges */
  pill?: boolean;

  /** Hides the stepper buttons */
  'without-steppers'?: boolean;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** The name of the control, submitted with form data */
  name?: string;

  /** Makes the input readonly */
  readonly?: boolean;

  /** Hint for browser autofill */
  autocomplete?: string;

  /** Focuses the control on page load */
  autofocus?: boolean;

  /** Hint for Enter key label on virtual keyboards */
  enterkeyhint?:
    'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send';

  /** Hint for virtual keyboard type */
  inputmode?: 'numeric' | 'decimal';

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the control receives input. */
  onInput?: (event: InputEvent) => void;

  /** Emitted before the value changes. Can be cancelled with `event.preventDefault()` to prevent the value from changing. */
  onBeforeinput?: (event: InputEvent) => void;

  /** Emitted when an alteration to the control's value is committed by the user. */
  onChange?: (event: Event) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface NumberInputRef {
  /** Sets focus on the input. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the input. */
  blur: () => void;

  /** Selects all the text in the input. */
  select: () => void;

  /** Increments the value by the step amount. */
  stepUp: () => void;

  /** Decrements the value by the step amount. */
  stepDown: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const NumberInput = forwardRef<NumberInputRef, NumberInputProps>(
  (
    {
      children,
      className,
      onInput,
      onBeforeinput,
      onChange,
      onBlur,
      onFocus,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const numberinputRef = useRef<
      HTMLElement & {
        focus?: (options: FocusOptions) => void;
        blur?: () => void;
        select?: () => void;
        stepUp?: () => void;
        stepDown?: () => void;
      }
    >(null);

    const setNumberinputRef = useCallback(
      (el: typeof numberinputRef.current) => {
        numberinputRef.current = el;
      },
      []
    );

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.focus === 'function'
          ) {
            numberinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.blur === 'function'
          ) {
            numberinputRef.current.blur();
          }
        },
        select: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.select === 'function'
          ) {
            numberinputRef.current.select();
          }
        },
        stepUp: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.stepUp === 'function'
          ) {
            numberinputRef.current.stepUp();
          }
        },
        stepDown: () => {
          if (
            numberinputRef.current &&
            typeof numberinputRef.current.stepDown === 'function'
          ) {
            numberinputRef.current.stepDown();
          }
        },
        get element() {
          return numberinputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = numberinputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleBeforeinput = (e: Event) => {
        if (onBeforeinput) onBeforeinput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('beforeinput', handleBeforeinput);
      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-invalid', handleInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('beforeinput', handleBeforeinput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-invalid', handleInvalid);
      };
    }, [onInput, onBeforeinput, onChange, onBlur, onFocus, onInvalid]);

    return (
      <wa-number-input
        ref={setNumberinputRef}
        class={clsx('NumberInput', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-number-input>
    );
  }
);

NumberInput.displayName = 'NumberInput';
