// templates/angular/ColorPicker/color-picker.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/color-picker/color-picker.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/color-picker/color-picker.js'));
}

/**
 * Color pickers allow the user to select a color
 *
 * @see https://webawesome.com/docs/components/color-picker
 */
@Component({
  selector: 'k-color-picker',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-color-picker
      #element
      [attr.value]="value"
      [attr.format]="format"
      [attr.opacity]="opacity || null"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.size]="size"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.name]="name"
      [attr.open]="open || null"
      [attr.placement]="placement"
      [attr.swatches]="swatches"
      [attr.uppercase]="uppercase || null"
      [attr.without-format-toggle]="withoutFormatToggle || null"
      [attr.inline]="inline || null"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-color-picker>
  `,
  styleUrl: './color-picker.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => ColorPickerComponent),
      multi: true,
    },
  ],
})
export class ColorPickerComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The current color value */
  @Input() value?: string;
  /** Color format */
  @Input() format?: 'hex' | 'rgb' | 'hsl' | 'hsv';
  /** Enables opacity slider */
  @Input() opacity?: boolean;
  /** Disables the color picker */
  @Input() disabled?: boolean;
  /** Makes field mandatory */
  @Input() required?: boolean;
  /** Color picker size */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Label text */
  @Input() label?: string;
  /** Hint text */
  @Input() hint?: string;
  /** Form field name */
  @Input() name?: string;
  /** Whether the panel is open */
  @Input() open?: boolean;
  /** Preferred placement of the color picker panel */
  @Input() placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** Predefined color swatches */
  @Input() swatches?: string;
  /** Displays hex values in uppercase */
  @Input() uppercase?: boolean;
  /** Hides the format toggle button */
  @Input() withoutFormatToggle?: boolean;
  /** Renders the color picker inline instead of in a dropdown */
  @Input() inline?: boolean;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() change = new EventEmitter<Event>();
  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() showEvent = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hideEvent = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleShowEvent = (e: Event) => this.showEvent.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-show', handleShowEvent)
    );
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-hide', handleHideEvent)
    );
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  getHexString(
    hue: number,
    saturation: number,
    brightness: number,
    alpha?: number
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        getHexString: (
          hue: number,
          saturation: number,
          brightness: number,
          alpha?: number
        ) => void;
      }
    ).getHexString(hue, saturation, brightness, alpha);
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  getFormattedValue(
    format?: 'hex' | 'hexa' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hsv' | 'hsva'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        getFormattedValue: (
          format?:
            'hex' | 'hexa' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hsv' | 'hsva'
        ) => void;
      }
    ).getFormattedValue(format);
  }
  reportValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { reportValidity: () => void }
    ).reportValidity();
  }
  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}

// templates/react/ColorPicker/ColorPicker.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaColorPicker from '@awesome.me/webawesome/dist/components/color-picker/color-picker.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';
import './ColorPicker.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/color-picker/color-picker.js'));
}

/**
 * Color pickers allow the user to select a color
 *
 * @example
 * ```tsx
 * // Basic usage
 * <ColorPicker />
 *
 * // With event handlers
 * <ColorPicker
 *   onChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<ColorPickerRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <ColorPicker ref={ref} />
 * ```
 */
export interface ColorPickerProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onChange'
  | 'onInput'
  | 'onShow'
  | 'onAfterShow'
  | 'onHide'
  | 'onAfterHide'
  | 'onBlur'
  | 'onFocus'
  | 'onInvalid'
  | 'dir'
> {
  /** The current color value */
  value?: string;

  /** Color format */
  format?: 'hex' | 'rgb' | 'hsl' | 'hsv';

  /** Enables opacity slider */
  opacity?: boolean;

  /** Disables the color picker */
  disabled?: boolean;

  /** Makes field mandatory */
  required?: boolean;

  /** Color picker size */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Label text */
  label?: string;

  /** Hint text */
  hint?: string;

  /** Form field name */
  name?: string;

  /** Whether the panel is open */
  open?: boolean;

  /** Preferred placement of the color picker panel */
  placement?:
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'left'
    | 'left-start'
    | 'left-end';

  /** Predefined color swatches */
  swatches?: string;

  /** Displays hex values in uppercase */
  uppercase?: boolean;

  /** Hides the format toggle button */
  'without-format-toggle'?: boolean;

  /** Renders the color picker inline instead of in a dropdown */
  inline?: boolean;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the color picker's value changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the color picker receives input. */
  onInput?: (event: InputEvent) => void;

  onShow?: (event: WaShowEvent) => void;

  onAfterShow?: (event: WaAfterShowEvent) => void;

  onHide?: (event: WaHideEvent) => void;

  onAfterHide?: (event: WaAfterHideEvent) => void;

  /** Emitted when the color picker loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the color picker receives focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface ColorPickerRef {
  /** Generates a hex string from HSV values. Hue must be 0-360. All other arguments must be 0-100. */
  getHexString: (
    hue: number,
    saturation: number,
    brightness: number,
    alpha?: number
  ) => void;

  /** Sets focus on the color picker. */
  focus: (options?: FocusOptions) => void;

  /** Removes focus from the color picker. */
  blur: () => void;

  /** Returns the current value as a string in the specified format. */
  getFormattedValue: (
    format?: 'hex' | 'hexa' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hsv' | 'hsva'
  ) => void;

  /** Checks for validity and shows the browser's validation message if the control is invalid. */
  reportValidity: () => void;

  /** Shows the color picker panel. */
  show: () => void;

  /** Hides the color picker panel */
  hide: () => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaColorPicker | null;
}

export const ColorPicker = forwardRef<ColorPickerRef, ColorPickerProps>(
  (
    {
      children,
      className,
      onChange,
      onInput,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onBlur,
      onFocus,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const colorpickerRef = useRef<WaColorPicker | null>(null);
    const setColorPickerRef = useCallback((el: WaColorPicker | null) => {
      colorpickerRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        getHexString: (
          hue: number,
          saturation: number,
          brightness: number,
          alpha?: number
        ) => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.getHexString === 'function'
          ) {
            colorpickerRef.current.getHexString(
              hue,
              saturation,
              brightness,
              alpha
            );
          }
        },
        focus: (options?: FocusOptions) => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.focus === 'function'
          ) {
            colorpickerRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.blur === 'function'
          ) {
            colorpickerRef.current.blur();
          }
        },
        getFormattedValue: (
          format?:
            'hex' | 'hexa' | 'rgb' | 'rgba' | 'hsl' | 'hsla' | 'hsv' | 'hsva'
        ) => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.getFormattedValue === 'function'
          ) {
            colorpickerRef.current.getFormattedValue(format);
          }
        },
        reportValidity: () => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.reportValidity === 'function'
          ) {
            colorpickerRef.current.reportValidity();
          }
        },
        show: () => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.show === 'function'
          ) {
            colorpickerRef.current.show();
          }
        },
        hide: () => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.hide === 'function'
          ) {
            colorpickerRef.current.hide();
          }
        },
        setCustomValidity: (message: string) => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.setCustomValidity === 'function'
          ) {
            colorpickerRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.formStateRestoreCallback ===
              'function'
          ) {
            colorpickerRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            colorpickerRef.current &&
            typeof colorpickerRef.current.resetValidity === 'function'
          ) {
            colorpickerRef.current.resetValidity();
          }
        },
        get element() {
          return colorpickerRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = colorpickerRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleWaShow = (e: Event) => {
        if (onShow) onShow(e as WaShowEvent);
      };

      const handleWaAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as WaAfterShowEvent);
      };

      const handleWaHide = (e: Event) => {
        if (onHide) onHide(e as WaHideEvent);
      };

      const handleWaAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as WaAfterHideEvent);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('change', handleChange);
      el.addEventListener('input', handleInput);
      el.addEventListener('wa-show', handleWaShow);
      el.addEventListener('wa-after-show', handleWaAfterShow);
      el.addEventListener('wa-hide', handleWaHide);
      el.addEventListener('wa-after-hide', handleWaAfterHide);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('change', handleChange);
        el.removeEventListener('input', handleInput);
        el.removeEventListener('wa-show', handleWaShow);
        el.removeEventListener('wa-after-show', handleWaAfterShow);
        el.removeEventListener('wa-hide', handleWaHide);
        el.removeEventListener('wa-after-hide', handleWaAfterHide);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [
      onChange,
      onInput,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onBlur,
      onFocus,
      onInvalid,
    ]);

    return (
      <wa-color-picker
        ref={setColorPickerRef}
        class={clsx('ColorPicker', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-color-picker>
    );
  }
);

ColorPicker.displayName = 'ColorPicker';
