// templates/react/Option/Option.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Option.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/option/option.js'));
}

/**
 * Options define the selectable items within various form controls
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Option />
 *
 * // With event handlers
 * <Option />
 *
 * ```
 */
export interface OptionProps extends Omit<HTMLAttributes<HTMLElement>, 'dir'> {

  /** The option value */
  value?: string;

  /** Disables the option */
  disabled?: boolean;

  /** Draws the option in a selected state */
  selected?: boolean;

  /** A custom label for the option (used by select's display input) */
  label?: string;
}

export interface OptionRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Option = forwardRef<OptionRef, OptionProps>(
  ({ children, className, ...props }, ref) => {
    const optionRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return optionRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-option
        ref={optionRef}
        class={clsx('Option', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-option>
    );
  }
);

Option.displayName = 'Option';

// templates/vue/Option/Option.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Option.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/option/option.js'));
}

/**
 * Options define the selectable items within various form controls
 */
export interface OptionProps {
  value?: string;
  disabled?: boolean;
  selected?: boolean;
  label?: string;
}

const props = defineProps<OptionProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-option
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-option>
</template>
