// templates/vue/Stepper/Stepper.vue
<script setup lang="ts">
import { ref, onMounted, useAttrs, onBeforeUnmount } from 'vue';
import type WaStepper from '@awesome.me/webawesome/dist/components/stepper/stepper.js';
import type { WaBeforeStepChangeEvent } from '@awesome.me/webawesome/dist/events/before-step-change.js';
import type { WaStepChangeEvent } from '@awesome.me/webawesome/dist/events/step-change.js';
import './Stepper.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/stepper/stepper.js'));
}

/**
 * Steppers walk users through a multi-stage process and show where they are in it
 */
export interface StepperProps {
  active?: string;
  orientation?: 'horizontal' | 'vertical' | 'auto';
  linear?: boolean;
  clickable?: boolean;
  label?: string;
}

const props = defineProps<StepperProps>();

defineOptions({ inheritAttrs: false });

// Forward props and fallthrough attributes to the web component yourself,
// rather than through Vue's default fallthrough:
// - Web Awesome reads attribute presence as truthy, so `false` must never
//   reach <wa-*>. Vue materializes every absent optional Boolean prop as
//   `false`, and would render a fallthrough `false` as the string "false".
//   `aria-*` / `data-*` keep `false`, where "false" is a real value.
// - Vue camelizes declared prop keys (`with-caret` -> `withCaret`). Before
//   the element upgrades, that key lands as the attribute `withcaret`, which
//   Web Awesome never reads, so props go back to their kebab-case names.
// A plain function, not `computed`: `attrs` is tracked per property read,
// so a computed over an empty `attrs` would never see a later attribute.
const attrs = useAttrs();

function hostAttributes(): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(attrs)) {
    if (key === 'class') continue;
    if (value === false && !/^(aria|data)-/.test(key)) continue;
    result[key] = value;
  }
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (value === undefined || value === false) continue;
    result[key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)] = value;
  }
  return result;
}

const emit = defineEmits<{
  'wa-before-step-change': [event: WaBeforeStepChangeEvent];
  'wa-step-change': [event: WaStepChangeEvent];
}>();

const elementRef = ref<WaStepper | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaBeforeStepChange = (e: Event) =>
  emit('wa-before-step-change', e as WaBeforeStepChangeEvent);
const handleWaStepChange = (e: Event) =>
  emit('wa-step-change', e as WaStepChangeEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-before-step-change', handleWaBeforeStepChange);
  el.addEventListener('wa-step-change', handleWaStepChange);
});

onBeforeUnmount(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-before-step-change', handleWaBeforeStepChange);
  el.removeEventListener('wa-step-change', handleWaStepChange);
});

defineExpose({
  goTo: (name: string) => elementRef.value?.goTo?.(name),
  next: () => elementRef.value?.next?.(),
  previous: () => elementRef.value?.previous?.(),
  element: elementRef,
});
</script>

<template>
  <wa-stepper ref="elementRef" v-bind="hostAttributes()" :class="$attrs.class">
    <slot />
  </wa-stepper>
</template>

// templates/angular/Stepper/stepper.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/stepper/stepper.js';
import type { WaBeforeStepChangeEvent } from '@awesome.me/webawesome/dist/events/before-step-change.js';
import type { WaStepChangeEvent } from '@awesome.me/webawesome/dist/events/step-change.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/stepper/stepper.js'));
}

/**
 * Steppers walk users through a multi-stage process and show where they are in it
 *
 * @see https://webawesome.com/docs/components/stepper
 */
@Component({
  selector: 'k-stepper',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-stepper
      #element
      [attr.active]="active"
      [attr.orientation]="orientation"
      [attr.linear]="linear || null"
      [attr.clickable]="clickable || null"
      [attr.label]="label"
    >
      <ng-content />
    </wa-stepper>
  `,
  styleUrl: './stepper.component.css',
})
export class StepperComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Name of the current step; the first step when unset or unmatched */
  @Input() active?: string;
  /** Layout direction; auto stacks the steps when they run out of room */
  @Input() orientation?: 'horizontal' | 'vertical' | 'auto';
  /** Steps can only be reached once the ones before are done */
  @Input() linear?: boolean;
  /** Lets users jump to a step by clicking or activating it */
  @Input() clickable?: boolean;
  /** Accessible name for the stepper */
  @Input() label?: string;

  @Output() beforeStepChange = new EventEmitter<WaBeforeStepChangeEvent>();
  @Output() stepChange = new EventEmitter<WaStepChangeEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleBeforeStepChange = (e: Event) =>
      this.beforeStepChange.emit(e as WaBeforeStepChangeEvent);
    el.addEventListener('wa-before-step-change', handleBeforeStepChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-before-step-change', handleBeforeStepChange)
    );
    const handleStepChange = (e: Event) =>
      this.stepChange.emit(e as WaStepChangeEvent);
    el.addEventListener('wa-step-change', handleStepChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-step-change', handleStepChange)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  goTo(name: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        goTo: (name: string) => void;
      }
    ).goTo(name);
  }
  next(): void {
    (this.elementRef.nativeElement as unknown as { next: () => void }).next();
  }
  previous(): void {
    (
      this.elementRef.nativeElement as unknown as { previous: () => void }
    ).previous();
  }
}
