// docs/src/components/ui/OtpInput/OtpInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaOtpInput from '@awesome.me/webawesome-pro/dist/components/otp-input/otp-input.js';
import '@awesome.me/webawesome-pro/dist/components/otp-input/otp-input.js';
import './OtpInput.css';
import type { WaClearEvent } from '@awesome.me/webawesome-pro/dist/events/clear.js';
import type { WaCompleteEvent } from '@awesome.me/webawesome-pro/dist/events/complete.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome-pro/dist/components/otp-input/otp-input.js'));
}

/**
 * OTP inputs collect one-time passcodes, PINs, and other fixed-length codes, one character per segment
 *
 * @example
 * ```tsx
 * // Basic usage
 * <OtpInput />
 *
 * // With event handlers
 * <OtpInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<OtpInputRef>(null);
 * <button onClick={() => ref.current?.clear()}>Call Method</button>
 * <OtpInput ref={ref} />
 * ```
 */
export interface OtpInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onFocus'
  | 'onBlur'
  | 'onComplete'
  | 'onClear'
  | 'onInvalid'
  | 'dir'
> {
  /** A label shown above the segments */
  label?: string;

  /** Hint text shown below the segments */
  hint?: string;

  /** The current value of the OTP field */
  value?: string;

  /** Number of character segments to display. Overridden by format when set */
  length?: number;

  /** Segment format using # as a placeholder; other characters are literal separators */
  format?: string;

  /** Allowed character class */
  type?: 'numeric' | 'alpha' | 'alphanumeric';

  /** Case transformation applied to entered characters */
  case?: 'preserve' | 'upper' | 'lower';

  /** Visual appearance of the segments */
  appearance?: 'outlined' | 'filled' | 'filled-outlined' | 'contained';

  /** The size of each segment */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Displays entered characters as a mask instead of their real value */
  mask?: boolean;

  /** Shows a mask character in empty segments as a length hint */
  'with-mask'?: boolean;

  /** The autocomplete attribute forwarded to the underlying input */
  autocomplete?: string;

  /** Submits the form automatically once all segments are filled */
  autosubmit?: boolean;

  /** Makes the field required */
  required?: boolean;

  /** Makes the field readonly */
  readonly?: boolean;

  /** Disables the form control */
  disabled?: boolean;

  /** The name of the input, submitted with form data */
  name?: string;

  /** Focuses the control on page load */
  autofocus?: boolean;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when a character is entered or removed. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the value changes and the field loses focus. */
  onChange?: (event: Event) => void;

  /** Emitted when the control gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted once when all segments are filled. Cancelable — call `preventDefault()` to stop `autosubmit` from submitting the form for this completion. */
  onComplete?: (event: WaCompleteEvent) => void;

  /** Emitted when the control's value is cleared. */
  onClear?: (event: WaClearEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface OtpInputRef {
  /** Clears the current value and returns focus to the field. */
  clear: () => void;

  /** Focuses the field. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the field. */
  blur: () => void;

  /** Selects all entered characters in the hidden input. */
  select: () => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaOtpInput | null;
}

export const OtpInput = forwardRef<OtpInputRef, OtpInputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onFocus,
      onBlur,
      onComplete,
      onClear,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const otpinputRef = useRef<WaOtpInput | null>(null);
    const setOtpInputRef = useCallback((el: WaOtpInput | null) => {
      otpinputRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        clear: () => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.clear === 'function'
          ) {
            otpinputRef.current.clear();
          }
        },
        focus: (options: FocusOptions) => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.focus === 'function'
          ) {
            otpinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.blur === 'function'
          ) {
            otpinputRef.current.blur();
          }
        },
        select: () => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.select === 'function'
          ) {
            otpinputRef.current.select();
          }
        },
        setCustomValidity: (message: string) => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.setCustomValidity === 'function'
          ) {
            otpinputRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.formStateRestoreCallback === 'function'
          ) {
            otpinputRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            otpinputRef.current &&
            typeof otpinputRef.current.resetValidity === 'function'
          ) {
            otpinputRef.current.resetValidity();
          }
        },
        get element() {
          return otpinputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = otpinputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as Event);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleWaComplete = (e: Event) => {
        if (onComplete) onComplete(e as WaCompleteEvent);
      };

      const handleWaClear = (e: Event) => {
        if (onClear) onClear(e as WaClearEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('wa-complete', handleWaComplete);
      el.addEventListener('wa-clear', handleWaClear);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('wa-complete', handleWaComplete);
        el.removeEventListener('wa-clear', handleWaClear);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onInput, onChange, onFocus, onBlur, onComplete, onClear, onInvalid]);

    return (
      <wa-otp-input
        ref={setOtpInputRef}
        class={clsx('OtpInput', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-otp-input>
    );
  }
);

OtpInput.displayName = 'OtpInput';

// templates/angular/OtpInput/otp-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/otp-input/otp-input.js';
import type { WaClearEvent } from '@awesome.me/webawesome/dist/events/clear.js';
import type { WaCompleteEvent } from '@awesome.me/webawesome/dist/events/complete.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/otp-input/otp-input.js'));
}

/**
 * OTP inputs collect one-time passcodes, PINs, and other fixed-length codes, one character per segment
 *
 * @see https://webawesome.com/docs/components/otp-input
 */
@Component({
  selector: 'k-otp-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-otp-input
      #element
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.value]="value"
      [attr.length]="length"
      [attr.format]="format"
      [attr.type]="type"
      [attr.case]="case"
      [attr.appearance]="appearance"
      [attr.size]="size"
      [attr.mask]="mask || null"
      [attr.with-mask]="withMask || null"
      [attr.autocomplete]="autocomplete"
      [attr.autosubmit]="autosubmit || null"
      [attr.required]="required || null"
      [attr.readonly]="readonly || null"
      [attr.disabled]="disabled || null"
      [attr.name]="name"
      [attr.autofocus]="autofocus || null"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-otp-input>
  `,
  styleUrl: './otp-input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => OtpInputComponent),
      multi: true,
    },
  ],
})
export class OtpInputComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** A label shown above the segments */
  @Input() label?: string;
  /** Hint text shown below the segments */
  @Input() hint?: string;
  /** The current value of the OTP field */
  @Input() value?: string;
  /** Number of character segments to display. Overridden by format when set */
  @Input() length?: number;
  /** Segment format using # as a placeholder; other characters are literal separators */
  @Input() format?: string;
  /** Allowed character class */
  @Input() type?: 'numeric' | 'alpha' | 'alphanumeric';
  /** Case transformation applied to entered characters */
  @Input() case?: 'preserve' | 'upper' | 'lower';
  /** Visual appearance of the segments */
  @Input() appearance?: 'outlined' | 'filled' | 'filled-outlined' | 'contained';
  /** The size of each segment */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Displays entered characters as a mask instead of their real value */
  @Input() mask?: boolean;
  /** Shows a mask character in empty segments as a length hint */
  @Input() withMask?: boolean;
  /** The autocomplete attribute forwarded to the underlying input */
  @Input() autocomplete?: string;
  /** Submits the form automatically once all segments are filled */
  @Input() autosubmit?: boolean;
  /** Makes the field required */
  @Input() required?: boolean;
  /** Makes the field readonly */
  @Input() readonly?: boolean;
  /** Disables the form control */
  @Input() disabled?: boolean;
  /** The name of the input, submitted with form data */
  @Input() name?: string;
  /** Focuses the control on page load */
  @Input() autofocus?: boolean;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() complete = new EventEmitter<WaCompleteEvent>();
  @Output() clearEvent = new EventEmitter<WaClearEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleComplete = (e: Event) =>
      this.complete.emit(e as WaCompleteEvent);
    el.addEventListener('wa-complete', handleComplete);
    this.cleanups.push(() =>
      el.removeEventListener('wa-complete', handleComplete)
    );
    const handleClearEvent = (e: Event) =>
      this.clearEvent.emit(e as WaClearEvent);
    el.addEventListener('wa-clear', handleClearEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-clear', handleClearEvent)
    );
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleValueChange = () =>
      this.onChangeCallback((el as unknown as { value: unknown }).value);
    el.addEventListener('input', handleValueChange);
    this.cleanups.push(() =>
      el.removeEventListener('input', handleValueChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (this.elementRef.nativeElement as unknown as { value: unknown }).value =
        value ?? '';
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  clear(): void {
    (this.elementRef.nativeElement as unknown as { clear: () => void }).clear();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  select(): void {
    (
      this.elementRef.nativeElement as unknown as { select: () => void }
    ).select();
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
