// docs/src/components/ui/TimeInput/TimeInput.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/time-input/time-input.js';
import './TimeInput.css';
import type { WaAfterHideEvent } from '@awesome.me/webawesome-pro/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome-pro/dist/events/after-show.js';
import type { WaClearEvent } from '@awesome.me/webawesome-pro/dist/events/clear.js';
import type { WaHideEvent } from '@awesome.me/webawesome-pro/dist/events/hide.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome-pro/dist/events/invalid.js';
import type { WaShowEvent } from '@awesome.me/webawesome-pro/dist/events/show.js';

/**
 * Time inputs collect a time of day from the user
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TimeInput />
 *
 * // With event handlers
 * <TimeInput
 *   onInput={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TimeInputRef>(null);
 * <button onClick={() => ref.current?.focus()}>Call Method</button>
 * <TimeInput ref={ref} />
 * ```
 */
export interface TimeInputProps extends Omit<
  HTMLAttributes<HTMLElement>,
  | 'onInput'
  | 'onChange'
  | 'onFocus'
  | 'onBlur'
  | 'onClear'
  | 'onShow'
  | 'onAfterShow'
  | 'onHide'
  | 'onAfterHide'
  | 'onInvalid'
  | 'dir'
> {
  /** The name of the control, submitted with form data */
  name?: string;

  /** The current value as a 24-hour `HH:mm:ss` string */
  value?: string;

  /** Whether the control is disabled */
  disabled?: boolean;

  /** Whether a value is required before form submission */
  required?: boolean;

  /** Whether the control is read-only */
  readonly?: boolean;

  /** Controls the overall dimensions of the control */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** The visual style of the control */
  appearance?: 'filled' | 'outlined' | 'filled-outlined';

  /** Draws the control with rounded edges */
  pill?: boolean;

  /** The control label. Use the `label` slot for rich labels. */
  label?: string;

  /** Help text shown below the control. Use the `hint` slot for rich hints. */
  hint?: string;

  /** Shows a clear button when the control has a value */
  'with-clear'?: boolean;

  /** Shows a button that sets the value to the current time */
  'with-now'?: boolean;

  /** The earliest acceptable time */
  min?: string;

  /** The latest acceptable time */
  max?: string;

  /** The granularity of the value in seconds */
  step?: number;

  /** Whether to display a 12- or 24-hour clock. `auto` follows the locale. */
  'hour-format'?: 'auto' | '12' | '24';

  /** Whether the time picker dropdown is open */
  open?: boolean;

  /** The preferred placement of the dropdown */
  placement?:
    'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end';

  /** Gap in pixels between the input and the dropdown */
  distance?: number;

  /** Hint for browser autofill */
  autocomplete?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted as the user types into a segment or interacts with the popup columns. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the committed value changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the control receives focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the control loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the clear button is activated. */
  onClear?: (event: WaClearEvent) => void;

  /** Emitted when the popup is about to open. Cancelable. */
  onShow?: (event: WaShowEvent) => void;

  /** Emitted after the popup opens and animations complete. */
  onAfterShow?: (event: WaAfterShowEvent) => void;

  /** Emitted when the popup is about to close. Cancelable. */
  onHide?: (event: WaHideEvent) => void;

  /** Emitted after the popup closes and animations complete. */
  onAfterHide?: (event: WaAfterHideEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface TimeInputRef {
  /** Sets focus on the first empty (else first) segment. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the time picker. */
  blur: () => void;

  /** Opens the popup. */
  show: () => void;

  /** Closes the popup. */
  hide: () => void;

  /** Called when the browser is trying to restore element's state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (state: string | File | FormData | null) => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const TimeInput = forwardRef<TimeInputRef, TimeInputProps>(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onFocus,
      onBlur,
      onClear,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const timeinputRef = useRef<
      HTMLElement & {
        focus?: (options?: FocusOptions) => void;
        blur?: () => void;
        show?: () => void;
        hide?: () => void;
        formStateRestoreCallback?: (
          state: string | File | FormData | null
        ) => void;
        setCustomValidity?: (message: string) => void;
        resetValidity?: () => void;
      }
    >(null);

    const setTimeinputRef = useCallback((el: typeof timeinputRef.current) => {
      timeinputRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        focus: (options: FocusOptions) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.focus === 'function'
          ) {
            timeinputRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.blur === 'function'
          ) {
            timeinputRef.current.blur();
          }
        },
        show: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.show === 'function'
          ) {
            timeinputRef.current.show();
          }
        },
        hide: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.hide === 'function'
          ) {
            timeinputRef.current.hide();
          }
        },
        formStateRestoreCallback: (state: string | File | FormData | null) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.formStateRestoreCallback === 'function'
          ) {
            timeinputRef.current.formStateRestoreCallback(state);
          }
        },
        setCustomValidity: (message: string) => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.setCustomValidity === 'function'
          ) {
            timeinputRef.current.setCustomValidity(message);
          }
        },
        resetValidity: () => {
          if (
            timeinputRef.current &&
            typeof timeinputRef.current.resetValidity === 'function'
          ) {
            timeinputRef.current.resetValidity();
          }
        },
        get element() {
          return timeinputRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      const el = timeinputRef.current;
      if (!el) return;

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleChange = (e: Event) => {
        if (onChange) onChange(e);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleWaClear = (e: Event) => {
        if (onClear) onClear(e as WaClearEvent);
      };

      const handleWaShow = (e: Event) => {
        if (onShow) onShow(e as WaShowEvent);
      };

      const handleWaAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as WaAfterShowEvent);
      };

      const handleWaHide = (e: Event) => {
        if (onHide) onHide(e as WaHideEvent);
      };

      const handleWaAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as WaAfterHideEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('wa-clear', handleWaClear);
      el.addEventListener('wa-show', handleWaShow);
      el.addEventListener('wa-after-show', handleWaAfterShow);
      el.addEventListener('wa-hide', handleWaHide);
      el.addEventListener('wa-after-hide', handleWaAfterHide);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('wa-clear', handleWaClear);
        el.removeEventListener('wa-show', handleWaShow);
        el.removeEventListener('wa-after-show', handleWaAfterShow);
        el.removeEventListener('wa-hide', handleWaHide);
        el.removeEventListener('wa-after-hide', handleWaAfterHide);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [
      onInput,
      onChange,
      onFocus,
      onBlur,
      onClear,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      onInvalid,
    ]);

    return (
      <wa-time-input
        ref={setTimeinputRef}
        class={clsx('TimeInput', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-time-input>
    );
  }
);

TimeInput.displayName = 'TimeInput';

// templates/angular/TimeInput/time-input.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/time-input/time-input.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaClearEvent } from '@awesome.me/webawesome/dist/events/clear.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/time-input/time-input.js'));
}

/**
 * Time inputs collect a time of day from the user
 *
 * @see https://webawesome.com/docs/components/time-input
 */
@Component({
  selector: 'k-time-input',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-time-input
      #element
      [attr.name]="name"
      [attr.value]="value"
      [attr.disabled]="disabled || null"
      [attr.required]="required || null"
      [attr.readonly]="readonly || null"
      [attr.size]="size"
      [attr.appearance]="appearance"
      [attr.pill]="pill || null"
      [attr.label]="label"
      [attr.hint]="hint"
      [attr.with-clear]="withClear || null"
      [attr.with-now]="withNow || null"
      [attr.min]="min"
      [attr.max]="max"
      [attr.step]="step"
      [attr.hour-format]="hourFormat"
      [attr.open]="open || null"
      [attr.placement]="placement"
      [attr.distance]="distance"
      [attr.autocomplete]="autocomplete"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-time-input>
  `,
  styleUrl: './time-input.component.css',
})
export class TimeInputComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The name of the control, submitted with form data */
  @Input() name?: string;
  /** The current value as a 24-hour `HH:mm:ss` string */
  @Input() value?: string;
  /** Whether the control is disabled */
  @Input() disabled?: boolean;
  /** Whether a value is required before form submission */
  @Input() required?: boolean;
  /** Whether the control is read-only */
  @Input() readonly?: boolean;
  /** Controls the overall dimensions of the control */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** The visual style of the control */
  @Input() appearance?: 'filled' | 'outlined' | 'filled-outlined';
  /** Draws the control with rounded edges */
  @Input() pill?: boolean;
  /** The control label. Use the `label` slot for rich labels. */
  @Input() label?: string;
  /** Help text shown below the control. Use the `hint` slot for rich hints. */
  @Input() hint?: string;
  /** Shows a clear button when the control has a value */
  @Input() withClear?: boolean;
  /** Shows a button that sets the value to the current time */
  @Input() withNow?: boolean;
  /** The earliest acceptable time */
  @Input() min?: string;
  /** The latest acceptable time */
  @Input() max?: string;
  /** The granularity of the value in seconds */
  @Input() step?: number;
  /** Whether to display a 12- or 24-hour clock. `auto` follows the locale. */
  @Input() hourFormat?: 'auto' | '12' | '24';
  /** Whether the time picker dropdown is open */
  @Input() open?: boolean;
  /** The preferred placement of the dropdown */
  @Input() placement?:
    'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end';
  /** Gap in pixels between the input and the dropdown */
  @Input() distance?: number;
  /** Hint for browser autofill */
  @Input() autocomplete?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() clear = new EventEmitter<WaClearEvent>();
  @Output() showEvent = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hideEvent = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleClear = (e: Event) => this.clear.emit(e as WaClearEvent);
    el.addEventListener('wa-clear', handleClear);
    this.cleanups.push(() => el.removeEventListener('wa-clear', handleClear));
    const handleShowEvent = (e: Event) => this.showEvent.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-show', handleShowEvent)
    );
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHideEvent = (e: Event) => this.hideEvent.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHideEvent);
    this.cleanups.push(() =>
      el.removeEventListener('wa-hide', handleHideEvent)
    );
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  hide(): void {
    (this.elementRef.nativeElement as unknown as { hide: () => void }).hide();
  }
  formStateRestoreCallback(state: string | File | FormData | null): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state: string | File | FormData | null
        ) => void;
      }
    ).formStateRestoreCallback(state);
  }
  setCustomValidity(message: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message: string) => void;
      }
    ).setCustomValidity(message);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
