// templates/react/Pagination/Pagination.jsx
import React from 'react';
import clsx from 'clsx';
import './Pagination.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/pagination/pagination.js'));
}

/**
 * Pagination splits long lists of content into pages, letting users navigate between them
 *
 * @example
 * ```jsx
 * <Pagination total={237} page-size={10} page={3} label="Search results" />
 * <Pagination total={237} format="compact" with-summary />
 * ```
 */
export const Pagination = React.forwardRef(
  (
    { children, className, onBeforePageChange, onPageChange, ...props },
    ref
  ) => {
    const paginationRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        get element() {
          return paginationRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = paginationRef.current;
      if (!el) return;

      const handleWaBeforePageChange = (e) => {
        if (onBeforePageChange) onBeforePageChange(e);
      };

      const handleWaPageChange = (e) => {
        if (onPageChange) onPageChange(e);
      };

      el.addEventListener('wa-before-page-change', handleWaBeforePageChange);
      el.addEventListener('wa-page-change', handleWaPageChange);

      return () => {
        el.removeEventListener(
          'wa-before-page-change',
          handleWaBeforePageChange
        );
        el.removeEventListener('wa-page-change', handleWaPageChange);
      };
    }, [onBeforePageChange, onPageChange]);

    return (
      <wa-pagination
        ref={paginationRef}
        class={clsx('Pagination', className)}
        {...props}
      >
        {children}
      </wa-pagination>
    );
  }
);

Pagination.displayName = 'Pagination';

// templates/vue/Pagination/Pagination.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './Pagination.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/pagination/pagination.js'));
}

/**
 * Pagination splits long lists of content into pages, letting users navigate between them
 */
export interface PaginationProps {
  total?: number;
  'page-size'?: number;
  page?: number;
  'sibling-count'?: number;
  'boundary-count'?: number;
  'without-nav'?: boolean;
  'with-edges'?: boolean;
  'with-summary'?: boolean;
  format?: 'standard' | 'compact';
  'href-template'?: string;
  'hide-single-page'?: boolean;
  label?: string;
  appearance?: 'outlined' | 'filled' | 'plain';
  disabled?: boolean;
}

const props = defineProps<PaginationProps>();

// Strip undefined and false props before forwarding to the web component.
// Vue boolean-prop coercion materializes absent optional Boolean props as
// `false`, but Web Awesome elements read attribute presence as truthy, so
// we must not forward `false` to <wa-*> (would render pill="" / loading="").
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props as Record<string, unknown>)) {
    if (value !== undefined && value !== false) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-before-page-change': [event: CustomEvent];
  'wa-page-change': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaBeforePageChange = (e: Event) =>
  emit('wa-before-page-change', e as CustomEvent);
const handleWaPageChange = (e: Event) =>
  emit('wa-page-change', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-before-page-change', handleWaBeforePageChange);
  el.addEventListener('wa-page-change', handleWaPageChange);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-before-page-change', handleWaBeforePageChange);
  el.removeEventListener('wa-page-change', handleWaPageChange);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-pagination ref="elementRef" v-bind="definedProps" :class="$attrs.class">
    <slot />
  </wa-pagination>
</template>
