// templates/react/TreeItem/TreeItem.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './TreeItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tree-item/tree-item.js'));
}

/**
 * Tree items are used inside trees to represent hierarchical items
 *
 * @example
 * ```tsx
 * // Basic usage
 * <TreeItem />
 *
 * // With event handlers
 * <TreeItem
 *   onExpand={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<TreeItemRef>(null);
 * <button onClick={() => ref.current?.getChildrenItems()}>Call Method</button>
 * <TreeItem ref={ref} />
 * ```
 */
export interface TreeItemProps extends Omit<HTMLAttributes<HTMLElement>, 'onExpand' | 'onAfterExpand' | 'onCollapse' | 'onAfterCollapse' | 'onLazyChange' | 'onLazyLoad' | 'dir'> {

  /** Expands the item */
  expanded?: boolean;

  /** Selects the item */
  selected?: boolean;

  /** Disables the item */
  disabled?: boolean;

  /** Enables lazy loading */
  lazy?: boolean;

  /** Emitted when the tree item expands. */
  onExpand?: (event: CustomEvent) => void;

  /** Emitted after the tree item expands and all animations are complete. */
  onAfterExpand?: (event: CustomEvent) => void;

  /** Emitted when the tree item collapses. */
  onCollapse?: (event: CustomEvent) => void;

  /** Emitted after the tree item collapses and all animations are complete. */
  onAfterCollapse?: (event: CustomEvent) => void;

  /** Emitted when the tree item's lazy state changes. */
  onLazyChange?: (event: CustomEvent) => void;

  /** Emitted when a lazy item is selected. Use this event to asynchronously load data and append items to the tree before expanding. After appending new items, remove the `lazy` attribute to remove the loading state and update the tree. */
  onLazyLoad?: (event: CustomEvent) => void;
}

export interface TreeItemRef {

  /** Gets all the nested tree items in this node. */
  getChildrenItems: ({ includeDisabled = true }: { includeDisabled?: boolean }) => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const TreeItem = forwardRef<TreeItemRef, TreeItemProps>(
  ({ children, className, onExpand, onAfterExpand, onCollapse, onAfterCollapse, onLazyChange, onLazyLoad, ...props }, ref) => {
    const treeitemRef = useRef<HTMLElement & {
      getChildrenItems?: ({ includeDisabled = true }: { includeDisabled?: boolean }) => void;
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        getChildrenItems: ({ includeDisabled = true }: { includeDisabled?: boolean }) => {
          if (treeitemRef.current && typeof treeitemRef.current.getChildrenItems === 'function') {
            treeitemRef.current.getChildrenItems({ includeDisabled = true });
          }
        },
        get element() {
          return treeitemRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = treeitemRef.current;
      if (!el) return;

      const handleWaExpand = (e: Event) => {
        if (onExpand) onExpand(e as CustomEvent);
      };

      const handleWaAfterExpand = (e: Event) => {
        if (onAfterExpand) onAfterExpand(e as CustomEvent);
      };

      const handleWaCollapse = (e: Event) => {
        if (onCollapse) onCollapse(e as CustomEvent);
      };

      const handleWaAfterCollapse = (e: Event) => {
        if (onAfterCollapse) onAfterCollapse(e as CustomEvent);
      };

      const handleWaLazyChange = (e: Event) => {
        if (onLazyChange) onLazyChange(e as CustomEvent);
      };

      const handleWaLazyLoad = (e: Event) => {
        if (onLazyLoad) onLazyLoad(e as CustomEvent);
      };

      el.addEventListener('wa-expand', handleWaExpand);
      el.addEventListener('wa-after-expand', handleWaAfterExpand);
      el.addEventListener('wa-collapse', handleWaCollapse);
      el.addEventListener('wa-after-collapse', handleWaAfterCollapse);
      el.addEventListener('wa-lazy-change', handleWaLazyChange);
      el.addEventListener('wa-lazy-load', handleWaLazyLoad);

      return () => {
        el.removeEventListener('wa-expand', handleWaExpand);
        el.removeEventListener('wa-after-expand', handleWaAfterExpand);
        el.removeEventListener('wa-collapse', handleWaCollapse);
        el.removeEventListener('wa-after-collapse', handleWaAfterCollapse);
        el.removeEventListener('wa-lazy-change', handleWaLazyChange);
        el.removeEventListener('wa-lazy-load', handleWaLazyLoad);
      };
    }, [onExpand, onAfterExpand, onCollapse, onAfterCollapse, onLazyChange, onLazyLoad]);

    return (
      <wa-tree-item
        ref={treeitemRef}
        class={clsx('TreeItem', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-tree-item>
    );
  }
);

TreeItem.displayName = 'TreeItem';

// templates/vue/TreeItem/TreeItem.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import './TreeItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/tree-item/tree-item.js'));
}

/**
 * Tree items are used inside trees to represent hierarchical items
 */
export interface TreeItemProps {
  expanded?: boolean;
  selected?: boolean;
  disabled?: boolean;
  lazy?: boolean;
}

const props = defineProps<TreeItemProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-expand': [event: CustomEvent];
  'wa-after-expand': [event: CustomEvent];
  'wa-collapse': [event: CustomEvent];
  'wa-after-collapse': [event: CustomEvent];
  'wa-lazy-change': [event: CustomEvent];
  'wa-lazy-load': [event: CustomEvent];
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

const handleWaExpand = (e: Event) => emit('wa-expand', e as CustomEvent);
const handleWaAfterExpand = (e: Event) => emit('wa-after-expand', e as CustomEvent);
const handleWaCollapse = (e: Event) => emit('wa-collapse', e as CustomEvent);
const handleWaAfterCollapse = (e: Event) => emit('wa-after-collapse', e as CustomEvent);
const handleWaLazyChange = (e: Event) => emit('wa-lazy-change', e as CustomEvent);
const handleWaLazyLoad = (e: Event) => emit('wa-lazy-load', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-expand', handleWaExpand);
  el.addEventListener('wa-after-expand', handleWaAfterExpand);
  el.addEventListener('wa-collapse', handleWaCollapse);
  el.addEventListener('wa-after-collapse', handleWaAfterCollapse);
  el.addEventListener('wa-lazy-change', handleWaLazyChange);
  el.addEventListener('wa-lazy-load', handleWaLazyLoad);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-expand', handleWaExpand);
  el.removeEventListener('wa-after-expand', handleWaAfterExpand);
  el.removeEventListener('wa-collapse', handleWaCollapse);
  el.removeEventListener('wa-after-collapse', handleWaAfterCollapse);
  el.removeEventListener('wa-lazy-change', handleWaLazyChange);
  el.removeEventListener('wa-lazy-load', handleWaLazyLoad);
});

defineExpose({
  getChildrenItems: ({ includeDisabled = true }: { includeDisabled?: boolean }) => (elementRef.value as any)?.getChildrenItems?.({ includeDisabled = true }),
  element: elementRef,
});
</script>

<template>
  <wa-tree-item
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-tree-item>
</template>
