// templates/angular/AccordionItem/accordion-item.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/accordion-item/accordion-item.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/accordion-item/accordion-item.js'));
}

/**
 * Accordion items are the individual disclosure panels placed inside an accordion
 *
 * @see https://webawesome.com/docs/components/accordion-item
 */
@Component({
  selector: 'k-accordion-item',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-accordion-item
      #element
      [attr.label]="label"
      [attr.expanded]="expanded || null"
      [attr.disabled]="disabled || null"
    >
      <ng-content />
    </wa-accordion-item>
  `,
  styleUrl: './accordion-item.component.css',
})
export class AccordionItemComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The header text. Use the `label` slot for markup-rich headers. */
  @Input() label?: string;
  /** Whether the item is expanded */
  @Input() expanded?: boolean;
  /** Whether the item is disabled and cannot be toggled */
  @Input() disabled?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }

  expand(): void {
    (
      this.elementRef.nativeElement as unknown as { expand: () => void }
    ).expand();
  }
  collapse(): void {
    (
      this.elementRef.nativeElement as unknown as { collapse: () => void }
    ).collapse();
  }
  toggle(): void {
    (
      this.elementRef.nativeElement as unknown as { toggle: () => void }
    ).toggle();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
}

// templates/react/AccordionItem/AccordionItem.jsx
import React from 'react';
import clsx from 'clsx';
import './AccordionItem.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/accordion-item/accordion-item.js'));
}

/**
 * Accordion items are the individual disclosure panels placed inside an accordion
 *
 * @example
 * ```jsx
 * // Basic usage
 * <AccordionItem label="Section title">Content</AccordionItem>
 *
 * // With ref methods
 * const ref = React.useRef(null);
 * <button onClick={() => ref.current?.expand()}>Expand</button>
 * <AccordionItem ref={ref} label="Section title">Content</AccordionItem>
 * ```
 *
 * @param {Object} props
 * @param {string} [props.label] - The header text. Use the `label` slot for markup-rich headers.
 * @param {boolean} [props.expanded] - Whether the item is expanded
 * @param {boolean} [props.disabled] - Whether the item is disabled and cannot be toggled
 * @param {string} [props.className] - Additional CSS classes
 * @param {React.ReactNode} [props.children] - Item content
 * @param {React.Ref} ref - Ref with methods: expand(), collapse(), toggle(), focus(options)
 */
export const AccordionItem = React.forwardRef(
  ({ children, className, ...props }, ref) => {
    const accordionitemRef = React.useRef(null);
    const setAccordionItemRef = React.useCallback((el) => {
      accordionitemRef.current = el;
    }, []);

    React.useImperativeHandle(
      ref,
      () => ({
        expand: () => {
          if (
            accordionitemRef.current &&
            typeof accordionitemRef.current.expand === 'function'
          ) {
            accordionitemRef.current.expand();
          }
        },
        collapse: () => {
          if (
            accordionitemRef.current &&
            typeof accordionitemRef.current.collapse === 'function'
          ) {
            accordionitemRef.current.collapse();
          }
        },
        toggle: () => {
          if (
            accordionitemRef.current &&
            typeof accordionitemRef.current.toggle === 'function'
          ) {
            accordionitemRef.current.toggle();
          }
        },
        focus: (options) => {
          if (
            accordionitemRef.current &&
            typeof accordionitemRef.current.focus === 'function'
          ) {
            accordionitemRef.current.focus(options);
          }
        },
        get element() {
          return accordionitemRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-accordion-item
        ref={setAccordionItemRef}
        class={clsx('AccordionItem', className)}
        {...{ suppressHydrationWarning: true, ...props }}
      >
        {children}
      </wa-accordion-item>
    );
  }
);

AccordionItem.displayName = 'AccordionItem';
