// templates/angular/DatePicker/date-picker.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/date-picker/date-picker.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/date-picker/date-picker.js'));
}

/**
 * An inline calendar for selecting a single date or a date range
 *
 * @see https://webawesome.com/docs/components/date-picker
 */
@Component({
  selector: 'k-date-picker',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-date-picker
      #element
      [attr.mode]="mode"
      [attr.value]="value"
      [attr.min]="min"
      [attr.max]="max"
      [attr.today]="today"
      [attr.focused-date]="focusedDate"
      [attr.view]="view"
      [attr.months]="months"
      [attr.page-by]="pageBy"
      [attr.first-day-of-week]="firstDayOfWeek"
      [attr.with-outside-days]="withOutsideDays || null"
      [attr.with-week-numbers]="withWeekNumbers || null"
      [attr.weekday-format]="weekdayFormat"
      [attr.disabled]="disabled || null"
      [attr.readonly]="readonly || null"
      [attr.disabled-dates]="disabledDates"
      [attr.disabled-days-of-week]="disabledDaysOfWeek"
      [attr.disable-past]="disablePast || null"
      [attr.disable-future]="disableFuture || null"
      [attr.min-range]="minRange"
      [attr.max-range]="maxRange"
      [attr.size]="size"
      [attr.locale]="locale"
    >
      <ng-content />
    </wa-date-picker>
  `,
  styleUrl: './date-picker.component.css',
})
export class DatePickerComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** The selection mode */
  @Input() mode?: 'single' | 'range';
  /** The selected date(s) in ISO format */
  @Input() value?: string;
  /** The earliest selectable date (YYYY-MM-DD) */
  @Input() min?: string;
  /** The latest selectable date (YYYY-MM-DD) */
  @Input() max?: string;
  /** Overrides the date considered "today" */
  @Input() today?: string;
  /** The currently focused date */
  @Input() focusedDate?: string;
  /** The current calendar view */
  @Input() view?: 'months' | 'days' | 'years';
  /** The number of months rendered side-by-side */
  @Input() months?: '1' | '2';
  /** Whether prev/next advances by the visible range or one month */
  @Input() pageBy?: 'single' | 'months';
  /** The first day of the week */
  @Input() firstDayOfWeek?:
    'auto' | 'sun' | 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat';
  /** Show leading/trailing days from adjacent months */
  @Input() withOutsideDays?: boolean;
  /** Show the ISO week-number column */
  @Input() withWeekNumbers?: boolean;
  /** The weekday header format */
  @Input() weekdayFormat?: 'narrow' | 'short' | 'long';
  /** Disables the entire picker */
  @Input() disabled?: boolean;
  /** Displays the value without allowing changes */
  @Input() readonly?: boolean;
  /** Whitespace-separated ISO dates to disable */
  @Input() disabledDates?: string;
  /** Space-separated 3-letter weekday names to disable */
  @Input() disabledDaysOfWeek?: string;
  /** Disable all dates before today */
  @Input() disablePast?: boolean;
  /** Disable all dates after today */
  @Input() disableFuture?: boolean;
  /** Minimum range length in days (range mode); 0 disables the check */
  @Input() minRange?: number;
  /** Maximum range length in days (range mode); 0 disables the check */
  @Input() maxRange?: number;
  /** The visual size */
  @Input() size?: 'xs' | 's' | 'm' | 'l' | 'xl';
  /** A BCP-47 locale override */
  @Input() locale?: string;

  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() change = new EventEmitter<Event>();
  @Output() focusDay = new EventEmitter<CustomEvent>();
  @Output() viewChange = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleFocusDay = (e: Event) => this.focusDay.emit(e as CustomEvent);
    el.addEventListener('wa-focus-day', handleFocusDay);
    this.cleanups.push(() =>
      el.removeEventListener('wa-focus-day', handleFocusDay)
    );
    const handleViewChange = (e: Event) =>
      this.viewChange.emit(e as CustomEvent);
    el.addEventListener('wa-view-change', handleViewChange);
    this.cleanups.push(() =>
      el.removeEventListener('wa-view-change', handleViewChange)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  goToDate(date?: string | Date): void {
    (
      this.elementRef.nativeElement as unknown as {
        goToDate: (date?: string | Date) => void;
      }
    ).goToDate(date);
  }
  goToToday(): void {
    (
      this.elementRef.nativeElement as unknown as { goToToday: () => void }
    ).goToToday();
  }
  clear(): void {
    (this.elementRef.nativeElement as unknown as { clear: () => void }).clear();
  }
}

// templates/react/DatePicker/DatePicker.jsx
import React from 'react';
import clsx from 'clsx';
import './DatePicker.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/date-picker/date-picker.js'));
}

/**
 * An inline calendar for selecting a single date or a date range
 *
 * @example
 * ```jsx
 * // Basic usage
 * <DatePicker value="2026-07-02" />
 *
 * // Range selection
 * <DatePicker mode="range" onChange={(e) => console.log(e.target.value)} />
 *
 * // Using ref methods
 * const pickerRef = React.useRef(null);
 * <button onClick={() => pickerRef.current?.goToToday()}>Today</button>
 * <DatePicker ref={pickerRef} />
 * ```
 *
 * @typedef {Object} DatePickerProps
 * @property {string} [mode] - The selection mode: single | range
 * @property {string} [value] - The selected date(s) in ISO format
 * @property {string} [min] - The earliest selectable date (YYYY-MM-DD)
 * @property {string} [max] - The latest selectable date (YYYY-MM-DD)
 * @property {string} [today] - Overrides the date considered "today"
 * @property {string} [focused-date] - The currently focused date
 * @property {string} [view] - The current calendar view: months | days | years
 * @property {string} [months] - The number of months rendered side-by-side: 1 | 2
 * @property {string} [page-by] - Whether prev/next advances by visible range or one month
 * @property {string} [first-day-of-week] - The first day of the week
 * @property {boolean} [with-outside-days] - Show leading/trailing days from adjacent months
 * @property {boolean} [with-week-numbers] - Show the ISO week-number column
 * @property {string} [weekday-format] - The weekday header format: narrow | short | long
 * @property {boolean} [disabled] - Disables the entire picker
 * @property {boolean} [readonly] - Displays the value without allowing changes
 * @property {string} [disabled-dates] - Whitespace-separated ISO dates to disable
 * @property {string} [disabled-days-of-week] - Space-separated 3-letter weekday names to disable
 * @property {boolean} [disable-past] - Disable all dates before today
 * @property {boolean} [disable-future] - Disable all dates after today
 * @property {number} [min-range] - Minimum range length in days (range mode)
 * @property {number} [max-range] - Maximum range length in days (range mode)
 * @property {string} [size] - The visual size: xs | s | m | l | xl
 * @property {string} [locale] - A BCP-47 locale override
 * @property {function} [onInput] - Event fired when the value changes during interaction
 * @property {function} [onChange] - Event fired when the user commits a new value
 * @property {function} [onFocusDay] - Event fired when the focused day changes
 * @property {function} [onViewChange] - Event fired when the view changes
 */

export const DatePicker = React.forwardRef(
  (
    {
      children,
      className,
      onInput,
      onChange,
      onFocusDay,
      onViewChange,
      ...props
    },
    ref
  ) => {
    const datepickerRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        focus: (options) => {
          if (
            datepickerRef.current &&
            typeof datepickerRef.current.focus === 'function'
          ) {
            datepickerRef.current.focus(options);
          }
        },
        goToDate: (date) => {
          if (
            datepickerRef.current &&
            typeof datepickerRef.current.goToDate === 'function'
          ) {
            datepickerRef.current.goToDate(date);
          }
        },
        goToToday: () => {
          if (
            datepickerRef.current &&
            typeof datepickerRef.current.goToToday === 'function'
          ) {
            datepickerRef.current.goToToday();
          }
        },
        clear: () => {
          if (
            datepickerRef.current &&
            typeof datepickerRef.current.clear === 'function'
          ) {
            datepickerRef.current.clear();
          }
        },
        get element() {
          return datepickerRef.current;
        },
      }),
      []
    );

    React.useEffect(() => {
      ensureLoaded();
      const el = datepickerRef.current;
      if (!el) return;

      const handleInput = (e) => {
        if (onInput) onInput(e);
      };

      const handleChange = (e) => {
        if (onChange) onChange(e);
      };

      const handleFocusDay = (e) => {
        if (onFocusDay) onFocusDay(e);
      };

      const handleViewChange = (e) => {
        if (onViewChange) onViewChange(e);
      };

      el.addEventListener('input', handleInput);
      el.addEventListener('change', handleChange);
      el.addEventListener('wa-focus-day', handleFocusDay);
      el.addEventListener('wa-view-change', handleViewChange);

      return () => {
        el.removeEventListener('input', handleInput);
        el.removeEventListener('change', handleChange);
        el.removeEventListener('wa-focus-day', handleFocusDay);
        el.removeEventListener('wa-view-change', handleViewChange);
      };
    }, [onInput, onChange, onFocusDay, onViewChange]);

    return (
      <wa-date-picker
        ref={datepickerRef}
        class={clsx('DatePicker', className)}
        {...props}
      >
        {children}
      </wa-date-picker>
    );
  }
);

DatePicker.displayName = 'DatePicker';
