// templates/angular/BubbleChart/bubble-chart.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/bubble-chart/bubble-chart.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/bubble-chart/bubble-chart.js'));
}

/**
 * Plots three-dimensional data using position and circle size to encode a third variable
 *
 * @see https://webawesome.com/docs/components/bubble-chart
 */
@Component({
  selector: 'k-bubble-chart',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-bubble-chart
        #element
        [attr.label]="label"
        [attr.description]="description"
        [attr.x-label]="xLabel"
        [attr.y-label]="yLabel"
        [attr.legend-position]="legendPosition"
        [attr.stacked]="stacked || null"
        [attr.index-axis]="indexAxis"
        [attr.grid]="grid"
        [attr.min]="min"
        [attr.max]="max"
        [attr.without-animation]="withoutAnimation || null"
        [attr.without-legend]="withoutLegend || null"
        [attr.without-tooltip]="withoutTooltip || null">
      <ng-content />
    </wa-bubble-chart>
  `,
  styleUrl: './bubble-chart.component.css',
})
export class BubbleChartComponent implements AfterViewInit {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Accessible name announced by assistive technology */
  @Input() label?: string;
  /** Extended accessible description for the chart */
  @Input() description?: string;
  /** Caption displayed beneath the horizontal axis */
  @Input() xLabel?: string;
  /** Caption displayed beside the vertical axis */
  @Input() yLabel?: string;
  /** Placement of the dataset legend relative to the chart */
  @Input() legendPosition?: 'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';
  /** Layers multiple datasets on a single axis */
  @Input() stacked?: boolean;
  /** Base axis for category labels (swap to flip chart orientation) */
  @Input() indexAxis?: 'x' | 'y';
  /** Selects which background grid lines are drawn */
  @Input() grid?: 'x' | 'y' | 'both' | 'none';
  /** Floor value for the value axis scale */
  @Input() min?: number;
  /** Ceiling value for the value axis scale */
  @Input() max?: number;
  /** Disables entrance and update motion effects */
  @Input() withoutAnimation?: boolean;
  /** Hides the dataset legend entirely */
  @Input() withoutLegend?: boolean;
  /** Prevents hover tooltips from appearing on data points */
  @Input() withoutTooltip?: boolean;

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }
  }
}

// docs/src/components/ui/BubbleChart/BubbleChart.tsx
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/bubble-chart/bubble-chart.js';
import './BubbleChart.css';

/**
 * Plots three-dimensional data using position and circle size to encode a third variable
 *
 * @example
 * ```tsx
 * <BubbleChart label="Population vs GDP">
 *   <script type="application/json">{JSON.stringify({
 *     data: {
 *       datasets: [{ label: 'Countries', data: [{ x: 20, y: 30, r: 15 }, { x: 40, y: 10, r: 10 }] }]
 *     }
 *   })}</script>
 * </BubbleChart>
 * ```
 */
export interface BubbleChartProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** Accessible name announced by assistive technology */
  label?: string;

  /** Extended accessible description for the chart */
  description?: string;

  /** Caption displayed beneath the horizontal axis */
  'x-label'?: string;

  /** Caption displayed beside the vertical axis */
  'y-label'?: string;

  /** Placement of the dataset legend relative to the chart */
  'legend-position'?: 'top' | 'right' | 'bottom' | 'left' | 'start' | 'end';

  /** Layers multiple datasets on a single axis */
  stacked?: boolean;

  /** Base axis for category labels */
  'index-axis'?: 'x' | 'y';

  /** Selects which background grid lines are drawn */
  grid?: 'x' | 'y' | 'both' | 'none';

  /** Floor value for the value axis scale */
  min?: number;

  /** Ceiling value for the value axis scale */
  max?: number;

  /** Disables entrance and update motion effects */
  'without-animation'?: boolean;

  /** Hides the dataset legend entirely */
  'without-legend'?: boolean;

  /** Prevents hover tooltips from appearing on data points */
  'without-tooltip'?: boolean;
}

export interface BubbleChartRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const BubbleChart = forwardRef<BubbleChartRef, BubbleChartProps>(
  ({ children, className, ...props }, ref) => {
    const bubbleChartRef = useRef<HTMLElement>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return bubbleChartRef.current;
        },
      }),
      []
    );

    return (
      <wa-bubble-chart
        ref={bubbleChartRef}
        class={clsx('BubbleChart', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-bubble-chart>
    );
  }
);

BubbleChart.displayName = 'BubbleChart';
