// templates/react/Dropdown/Dropdown.tsx
import { forwardRef, useRef, useImperativeHandle, useEffect, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import './Dropdown.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/dropdown/dropdown.js'));
}

/**
 * Dropdowns expose additional content that pops up when the user interacts with a trigger
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Dropdown />
 *
 * // With event handlers
 * <Dropdown
 *   onShow={(e) => console.log(e)} />
 *
 * ```
 */
export interface DropdownProps extends Omit<HTMLAttributes<HTMLElement>, 'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'onSelect' | 'dir'> {

  /** Indicates whether the dropdown is open */
  open?: boolean;

  /** Preferred placement of the dropdown panel */
  placement?: 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end';

  /** Disables the dropdown */
  disabled?: boolean;

  /** Keeps the dropdown open when an item is selected */
  'stay-open-on-select'?: boolean;

  /** Distance from the panel to the trigger */
  distance?: number;

  /** Offset along the trigger */
  skidding?: number;

  /** Hoists the dropdown panel to the body */
  hoist?: boolean;

  /** Dropdown size */
  size?: 'small' | 'medium' | 'large';

  /** Emitted when the dropdown is about to show. */
  onShow?: (event: CustomEvent) => void;

  /** Emitted after the dropdown has been shown. */
  onAfterShow?: (event: CustomEvent) => void;

  /** Emitted when the dropdown is about to hide. */
  onHide?: (event: CustomEvent) => void;

  /** Emitted after the dropdown has been hidden. */
  onAfterHide?: (event: CustomEvent) => void;

  /** Emitted when an item in the dropdown is selected. */
  onSelect?: (event: CustomEvent) => void;
}

export interface DropdownRef {
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Dropdown = forwardRef<DropdownRef, DropdownProps>(
  ({ children, className, onShow, onAfterShow, onHide, onAfterHide, onSelect, ...props }, ref) => {
    const dropdownRef = useRef<HTMLElement & {
    }>(null);

    useImperativeHandle(
      ref,
      () => ({
        get element() {
          return dropdownRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = dropdownRef.current;
      if (!el) return;

      const handleWaShow = (e: Event) => {
        if (onShow) onShow(e as CustomEvent);
      };

      const handleWaAfterShow = (e: Event) => {
        if (onAfterShow) onAfterShow(e as CustomEvent);
      };

      const handleWaHide = (e: Event) => {
        if (onHide) onHide(e as CustomEvent);
      };

      const handleWaAfterHide = (e: Event) => {
        if (onAfterHide) onAfterHide(e as CustomEvent);
      };

      const handleWaSelect = (e: Event) => {
        if (onSelect) onSelect(e as CustomEvent);
      };

      el.addEventListener('wa-show', handleWaShow);
      el.addEventListener('wa-after-show', handleWaAfterShow);
      el.addEventListener('wa-hide', handleWaHide);
      el.addEventListener('wa-after-hide', handleWaAfterHide);
      el.addEventListener('wa-select', handleWaSelect);

      return () => {
        el.removeEventListener('wa-show', handleWaShow);
        el.removeEventListener('wa-after-show', handleWaAfterShow);
        el.removeEventListener('wa-hide', handleWaHide);
        el.removeEventListener('wa-after-hide', handleWaAfterHide);
        el.removeEventListener('wa-select', handleWaSelect);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide, onSelect]);

    return (
      <wa-dropdown
        ref={dropdownRef}
        class={clsx('Dropdown', className)}
        suppressHydrationWarning
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-dropdown>
    );
  }
);

Dropdown.displayName = 'Dropdown';

// templates/vue/Dropdown/Dropdown.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue';
import './Dropdown.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/dropdown/dropdown.js'));
}

/**
 * Dropdowns expose additional content that pops up when the user interacts with a trigger
 */
export interface DropdownProps {
  placement?: 'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end';
  disabled?: boolean;
  'stay-open-on-select'?: boolean;
  distance?: number;
  skidding?: number;
  hoist?: boolean;
  size?: 'small' | 'medium' | 'large';
}

const props = defineProps<DropdownProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  'wa-show': [event: CustomEvent];
  'wa-after-show': [event: CustomEvent];
  'wa-hide': [event: CustomEvent];
  'wa-after-hide': [event: CustomEvent];
  'wa-select': [event: CustomEvent];
}>();

const open = defineModel<boolean>('open', { default: false });

const elementRef = ref<HTMLElement | null>(null);

watch(open, (newOpen) => {
  const el = elementRef.value as any;
  if (!el) return;
  const isOpen = el.open ?? false;
  if (newOpen && !isOpen) el.show?.();
  else if (!newOpen && isOpen) el.hide?.();
});

onMounted(() => {
  ensureLoaded();
});

const handleWaShow = (e: Event) => { open.value = true; emit('wa-show', e as CustomEvent); };
const handleWaAfterShow = (e: Event) => emit('wa-after-show', e as CustomEvent);
const handleWaHide = (e: Event) => { open.value = false; emit('wa-hide', e as CustomEvent); };
const handleWaAfterHide = (e: Event) => emit('wa-after-hide', e as CustomEvent);
const handleWaSelect = (e: Event) => emit('wa-select', e as CustomEvent);

onMounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.addEventListener('wa-show', handleWaShow);
  el.addEventListener('wa-after-show', handleWaAfterShow);
  el.addEventListener('wa-hide', handleWaHide);
  el.addEventListener('wa-after-hide', handleWaAfterHide);
  el.addEventListener('wa-select', handleWaSelect);
});

onUnmounted(() => {
  const el = elementRef.value;
  if (!el) return;

  el.removeEventListener('wa-show', handleWaShow);
  el.removeEventListener('wa-after-show', handleWaAfterShow);
  el.removeEventListener('wa-hide', handleWaHide);
  el.removeEventListener('wa-after-hide', handleWaAfterHide);
  el.removeEventListener('wa-select', handleWaSelect);
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-dropdown
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
    :open="open"
  >
    <slot />
  </wa-dropdown>
</template>
