// templates/react/Drawer/Drawer.jsx
import React from 'react';
import { createPortal } from 'react-dom';
import clsx from 'clsx';
import './Drawer.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/drawer/drawer.js'));
}

/**
 * Drawers slide in from a container edge to expose additional options
 *
 * @example
 * // Using open prop (recommended)
 * const [open, setOpen] = React.useState(false);
 * <Drawer open={open} label="Drawer Title" onHide={() => setOpen(false)}>
 *   <p>Drawer content</p>
 * </Drawer>
 *
 * // Using ref methods (alternative)
 * const drawerRef = React.useRef(null);
 * <Drawer ref={drawerRef} label="Drawer Title">
 *   <p>Drawer content</p>
 * </Drawer>
 * drawerRef.current?.show();
 *
 * @typedef {Object} DrawerRef
 * @property {() => void} show
 * @property {() => void} hide
 * @property {() => void} requestClose
 * @property {HTMLElement | null} element
 *
 * @param {Object} props
 * @param {boolean} [props.open] - Indicates whether the drawer is open
 * @param {string} [props.label] - The drawer's label as displayed in the header
 * @param {'top' | 'end' | 'bottom' | 'start'} [props.placement] - The direction from which the drawer will open
 * @param {boolean} [props['light-dismiss']] - Closes the drawer when the user clicks outside of it
 * @param {boolean} [props['without-header']] - Removes the header
 * @param {function} [props.onShow] - Event fired when the drawer is shown
 * @param {function} [props.onAfterShow] - Event fired after the drawer is shown
 * @param {function} [props.onHide] - Event fired when the drawer is about to hide
 * @param {function} [props.onAfterHide] - Event fired after the drawer is hidden
 * @param {string} [props.className] - Additional CSS classes
 * @param {React.ReactNode} [props.children] - Drawer content
 * @param {React.Ref} ref - Ref with methods: show(), hide()
 */
export const Drawer = React.forwardRef(
  (
    {
      children,
      className,
      open,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      ...props
    },
    ref
  ) => {
    const drawerRef = React.useRef(null);

    React.useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (drawerRef.current) drawerRef.current.open = true;
        },
        hide: () => {
          if (drawerRef.current) drawerRef.current.open = false;
        },
        requestClose: () => {
          if (drawerRef.current) drawerRef.current.open = false;
        },
        get element() {
          return drawerRef.current;
        },
      }),
      []
    );

    // Sync open prop with drawer element
    React.useEffect(() => {
      ensureLoaded();
      const el = drawerRef.current;
      if (!el || open === undefined) return;
      el.open = open;
    }, [open]);

    // Setup event listeners
    React.useEffect(() => {
      const el = drawerRef.current;
      if (!el) return;

      const handleShow = (e) => onShow?.(e);
      const handleAfterShow = (e) => onAfterShow?.(e);
      const handleHide = (e) => onHide?.(e);
      const handleAfterHide = (e) => onAfterHide?.(e);

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return createPortal(
      <wa-drawer ref={drawerRef} class={clsx('Drawer', className)} {...props}>
        {children}
      </wa-drawer>,
      document.body
    );
  }
);

Drawer.displayName = 'Drawer';

// templates/angular/Drawer/drawer.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, ElementRef, ViewChild, AfterViewInit, inject, Input, Output, EventEmitter, OnDestroy } from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/drawer/drawer.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/drawer/drawer.js'));
}

/**
 * Drawers slide in from a container edge to expose additional options
 *
 * @see https://webawesome.com/docs/components/drawer
 */
@Component({
  selector: 'k-drawer',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-drawer
        #element
        [attr.open]="open || null"
        [attr.label]="label"
        [attr.placement]="placement"
        [attr.light-dismiss]="lightDismiss || null"
        [attr.without-header]="withoutHeader || null">
      <ng-content />
    </wa-drawer>
  `,
  styleUrl: './drawer.component.css',
})
export class DrawerComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element') elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Indicates whether the drawer is open */
  @Input() open?: boolean;
  /** The drawer's label as displayed in the header */
  @Input() label?: string;
  /** The direction from which the drawer will open */
  @Input() placement?: 'top' | 'end' | 'bottom' | 'start';
  /** Closes the drawer when the user clicks outside of it */
  @Input() lightDismiss?: boolean;
  /** Removes the header */
  @Input() withoutHeader?: boolean;

  @Output() showEvent = new EventEmitter<CustomEvent>();
  @Output() afterShow = new EventEmitter<CustomEvent>();
  @Output() hide = new EventEmitter<CustomEvent>();
  @Output() afterHide = new EventEmitter<CustomEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShowEvent = (e: Event) => this.showEvent.emit(e as CustomEvent);
    el.addEventListener('wa-show', handleShowEvent);
    this.cleanups.push(() => el.removeEventListener('wa-show', handleShowEvent));
    const handleAfterShow = (e: Event) => this.afterShow.emit(e as CustomEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() => el.removeEventListener('wa-after-show', handleAfterShow));
    const handleHide = (e: Event) => this.hide.emit(e as CustomEvent);
    el.addEventListener('wa-hide', handleHide);
    this.cleanups.push(() => el.removeEventListener('wa-hide', handleHide));
    const handleAfterHide = (e: Event) => this.afterHide.emit(e as CustomEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() => el.removeEventListener('wa-after-hide', handleAfterHide));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  show(): void {
    (this.elementRef.nativeElement as unknown as { show: () => void }).show();
  }
  requestClose(): void {
    (this.elementRef.nativeElement as unknown as { requestClose: () => void }).requestClose();
  }
}
