// docs/src/components/ui/Drawer/Drawer.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import { createPortal } from 'react-dom';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/drawer/drawer.js';
import './Drawer.css';
import type { WaAfterHideEvent } from '@awesome.me/webawesome-pro/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome-pro/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome-pro/dist/events/hide.js';
import type { WaShowEvent } from '@awesome.me/webawesome-pro/dist/events/show.js';

/**
 * Drawers slide in from a container edge to expose additional options
 *
 * @example
 * ```tsx
 * // Using open prop (recommended)
 * import { useState } from 'react';
 *
 * function App() {
 *   const [open, setOpen] = useState(false);
 *
 *   return (
 *     <>
 *       <Button onClick={() => setOpen(true)}>Open Drawer</Button>
 *       <Drawer open={open} label="Drawer Title" onHide={() => setOpen(false)}>
 *         <p>Drawer content</p>
 *       </Drawer>
 *     </>
 *   );
 * }
 *
 * // Using ref methods (alternative)
 * import { useRef } from 'react';
 * const drawerRef = useRef<DrawerRef>(null);
 *
 * <Button onClick={() => drawerRef.current?.show()}>Open Drawer</Button>
 * <Drawer ref={drawerRef} label="Drawer Title">
 *   <p>Drawer content</p>
 * </Drawer>
 * ```
 */
export interface DrawerProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onShow' | 'onAfterShow' | 'onHide' | 'onAfterHide' | 'dir'
> {
  /** Indicates whether the drawer is open */
  open?: boolean;

  /** The drawer's label as displayed in the header */
  label?: string;

  /** The direction from which the drawer will open */
  placement?: 'top' | 'end' | 'bottom' | 'start';

  /** Closes the drawer when the user clicks outside of it */
  'light-dismiss'?: boolean;

  /** Removes the header */
  'without-header'?: boolean;

  /** Emitted when the drawer opens. */
  onShow?: (event: WaShowEvent) => void;

  /** Emitted after the drawer opens and all animations are complete. */
  onAfterShow?: (event: WaAfterShowEvent) => void;

  /** Emitted when the drawer is requesting to close. Calling `event.preventDefault()` will prevent the drawer from closing. You can inspect `event.detail.source` to see which element caused the drawer to close. If the source is the drawer element itself, the user has pressed [[Escape]] or the drawer has been closed programmatically. Avoid using this unless closing the drawer will result in destructive behavior such as data loss. */
  onHide?: (event: WaHideEvent) => void;

  /** Emitted after the drawer closes and all animations are complete. */
  onAfterHide?: (event: WaAfterHideEvent) => void;
}

export interface DrawerRef {
  show: () => void;
  hide: () => void;
  requestClose: () => void;
  /** Reference to the underlying HTML element */
  element: HTMLElement | null;
}

export const Drawer = forwardRef<DrawerRef, DrawerProps>(
  (
    {
      children,
      className,
      open,
      onShow,
      onAfterShow,
      onHide,
      onAfterHide,
      ...props
    },
    ref
  ) => {
    const drawerRef = useRef<HTMLElement & { open?: boolean }>(null);

    const setDrawerRef = useCallback((el: typeof drawerRef.current) => {
      drawerRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        show: () => {
          if (drawerRef.current) drawerRef.current.open = true;
        },
        hide: () => {
          if (drawerRef.current) drawerRef.current.open = false;
        },
        requestClose: () => {
          if (drawerRef.current) drawerRef.current.open = false;
        },
        get element() {
          return drawerRef.current;
        },
      }),
      []
    );

    // Sync open prop with drawer element
    useEffect(() => {
      const el = drawerRef.current;
      if (!el || open === undefined) return;
      el.open = open;
    }, [open]);

    // Setup event listeners
    useEffect(() => {
      const el = drawerRef.current;
      if (!el) return;

      const handleShow = (e: Event) => onShow?.(e as WaShowEvent);
      const handleAfterShow = (e: Event) =>
        onAfterShow?.(e as WaAfterShowEvent);
      const handleHide = (e: Event) => onHide?.(e as WaHideEvent);
      const handleAfterHide = (e: Event) =>
        onAfterHide?.(e as WaAfterHideEvent);

      el.addEventListener('wa-show', handleShow);
      el.addEventListener('wa-after-show', handleAfterShow);
      el.addEventListener('wa-hide', handleHide);
      el.addEventListener('wa-after-hide', handleAfterHide);

      return () => {
        el.removeEventListener('wa-show', handleShow);
        el.removeEventListener('wa-after-show', handleAfterShow);
        el.removeEventListener('wa-hide', handleHide);
        el.removeEventListener('wa-after-hide', handleAfterHide);
      };
    }, [onShow, onAfterShow, onHide, onAfterHide]);

    return createPortal(
      <wa-drawer
        ref={setDrawerRef}
        class={clsx('Drawer', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-drawer>,
      document.body
    );
  }
);

Drawer.displayName = 'Drawer';

// templates/angular/Drawer/drawer.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
} from '@angular/core';
import type WaElement from '@awesome.me/webawesome/dist/components/drawer/drawer.js';
import type { WaAfterHideEvent } from '@awesome.me/webawesome/dist/events/after-hide.js';
import type { WaAfterShowEvent } from '@awesome.me/webawesome/dist/events/after-show.js';
import type { WaHideEvent } from '@awesome.me/webawesome/dist/events/hide.js';
import type { WaShowEvent } from '@awesome.me/webawesome/dist/events/show.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/drawer/drawer.js'));
}

/**
 * Drawers slide in from a container edge to expose additional options
 *
 * @see https://webawesome.com/docs/components/drawer
 *
 * @remarks Open and close programmatically by toggling the `open` attribute (e.g. `[open]="isOpen"`). The previous `show()` / `requestClose()` methods are marked private in WA 3.5.0+ and are no longer exposed.
 */
@Component({
  selector: 'k-drawer',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-drawer
      #element
      [attr.open]="open || null"
      [attr.label]="label"
      [attr.placement]="placement"
      [attr.light-dismiss]="lightDismiss || null"
      [attr.without-header]="withoutHeader || null"
    >
      <ng-content />
    </wa-drawer>
  `,
  styleUrl: './drawer.component.css',
})
export class DrawerComponent implements AfterViewInit, OnDestroy {
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Indicates whether the drawer is open */
  @Input() open?: boolean;
  /** The drawer's label as displayed in the header */
  @Input() label?: string;
  /** The direction from which the drawer will open */
  @Input() placement?: 'top' | 'end' | 'bottom' | 'start';
  /** Closes the drawer when the user clicks outside of it */
  @Input() lightDismiss?: boolean;
  /** Removes the header */
  @Input() withoutHeader?: boolean;

  @Output() show = new EventEmitter<WaShowEvent>();
  @Output() afterShow = new EventEmitter<WaAfterShowEvent>();
  @Output() hide = new EventEmitter<WaHideEvent>();
  @Output() afterHide = new EventEmitter<WaAfterHideEvent>();

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleShow = (e: Event) => this.show.emit(e as WaShowEvent);
    el.addEventListener('wa-show', handleShow);
    this.cleanups.push(() => el.removeEventListener('wa-show', handleShow));
    const handleAfterShow = (e: Event) =>
      this.afterShow.emit(e as WaAfterShowEvent);
    el.addEventListener('wa-after-show', handleAfterShow);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-show', handleAfterShow)
    );
    const handleHide = (e: Event) => this.hide.emit(e as WaHideEvent);
    el.addEventListener('wa-hide', handleHide);
    this.cleanups.push(() => el.removeEventListener('wa-hide', handleHide));
    const handleAfterHide = (e: Event) =>
      this.afterHide.emit(e as WaAfterHideEvent);
    el.addEventListener('wa-after-hide', handleAfterHide);
    this.cleanups.push(() =>
      el.removeEventListener('wa-after-hide', handleAfterHide)
    );
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }
}
