// docs/src/components/ui/Breadcrumb/Breadcrumb.tsx
import { forwardRef, type HTMLAttributes } from 'react';
import clsx from 'clsx';
import '@awesome.me/webawesome-pro/dist/components/breadcrumb/breadcrumb.js';
import './Breadcrumb.css';

/**
 * Breadcrumbs provide a group of links so users can easily navigate a website hierarchy
 *
 * @example
 * ```tsx
 * import { Breadcrumb, BreadcrumbItem } from './components/ui';
 *
 * <Breadcrumb>
 *   <BreadcrumbItem>Home</BreadcrumbItem>
 *   <BreadcrumbItem>Category</BreadcrumbItem>
 *   <BreadcrumbItem>Product</BreadcrumbItem>
 * </Breadcrumb>
 *
 * // With links
 * <Breadcrumb>
 *   <BreadcrumbItem href="/">Home</BreadcrumbItem>
 *   <BreadcrumbItem href="/products">Products</BreadcrumbItem>
 *   <BreadcrumbItem>Current Page</BreadcrumbItem>
 * </Breadcrumb>
 *
 * // With custom separator
 * <Breadcrumb>
 *   <wa-icon slot="separator" name="angle-right" />
 *   <BreadcrumbItem>First</BreadcrumbItem>
 *   <BreadcrumbItem>Second</BreadcrumbItem>
 * </Breadcrumb>
 * ```
 */
export interface BreadcrumbProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'dir'
> {
  /** The label to use for the breadcrumb control for assistive devices */
  label?: string;
}

export const Breadcrumb = forwardRef<HTMLElement, BreadcrumbProps>(
  ({ children, className, ...props }, ref) => {
    return (
      <wa-breadcrumb
        ref={ref}
        class={clsx('Breadcrumb', className)}
        {...(props as Record<string, unknown>)}
      >
        {children}
      </wa-breadcrumb>
    );
  }
);

Breadcrumb.displayName = 'Breadcrumb';

// templates/vue/Breadcrumb/Breadcrumb.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './Breadcrumb.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/breadcrumb/breadcrumb.js'));
}

/**
 * Breadcrumbs provide a group of links so users can easily navigate a website hierarchy
 */
export interface BreadcrumbProps {
  label?: string;
}

const props = defineProps<BreadcrumbProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-breadcrumb
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-breadcrumb>
</template>
