// templates/react/Checkbox/Checkbox.tsx
import {
  forwardRef,
  useRef,
  useCallback,
  useImperativeHandle,
  useEffect,
  type HTMLAttributes,
} from 'react';
import clsx from 'clsx';
import type WaCheckbox from '@awesome.me/webawesome/dist/components/checkbox/checkbox.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';
import './Checkbox.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/checkbox/checkbox.js'));
}

/**
 * Checkboxes allow the user to toggle an option on or off
 *
 * @example
 * ```tsx
 * // Basic usage
 * <Checkbox />
 *
 * // With event handlers
 * <Checkbox
 *   onChange={(e) => console.log(e)} />
 *
 * // With ref methods
 * const ref = useRef<CheckboxRef>(null);
 * <button onClick={() => ref.current?.click()}>Call Method</button>
 * <Checkbox ref={ref} />
 * ```
 */
export interface CheckboxProps extends Omit<
  HTMLAttributes<HTMLElement>,
  'onChange' | 'onBlur' | 'onFocus' | 'onInput' | 'onInvalid' | 'dir'
> {
  /** Draws checkbox in checked state */
  checked?: boolean;

  /** Disables the checkbox */
  disabled?: boolean;

  /** Descriptive helper text */
  hint?: string;

  /** Mixed/parent selection state */
  indeterminate?: boolean;

  /** Form submission identifier */
  name?: string;

  /** Makes field mandatory */
  required?: boolean;

  /** Adjusts checkbox dimensions */
  size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';

  /** Form submission value */
  value?: string;

  /** Native tooltip text, shown on hover */
  title?: string;

  /** Custom validation message; the control is invalid while it is set */
  'custom-error'?: string;

  /** Emitted when the checked state changes. */
  onChange?: (event: Event) => void;

  /** Emitted when the checkbox loses focus. */
  onBlur?: (event: FocusEvent) => void;

  /** Emitted when the checkbox gains focus. */
  onFocus?: (event: FocusEvent) => void;

  /** Emitted when the checkbox receives input. */
  onInput?: (event: InputEvent) => void;

  /** Emitted when the form control has been checked for validity and its constraints aren't satisfied. */
  onInvalid?: (event: WaInvalidEvent) => void;
}

export interface CheckboxRef {
  /** Simulates a click on the checkbox. */
  click: () => void;

  /** Sets focus on the checkbox. */
  focus: (options: FocusOptions) => void;

  /** Removes focus from the checkbox. */
  blur: () => void;

  /** Do not use this when creating a "Validator". This is intended for end users of components.
We track manually defined custom errors so we don't clear them on accident in our validators. */
  setCustomValidity: (message: string) => void;

  /** Called when the browser is trying to restore element’s state to state in which case reason is "restore", or when
the browser is trying to fulfill autofill on behalf of user in which case reason is "autocomplete". In the case of
"restore", state is a string, File, or FormData object previously set as the second argument to setFormValue. */
  formStateRestoreCallback: (
    state: string | File | FormData | null,
    reason: 'autocomplete' | 'restore'
  ) => void;

  /** Reset validity is a way of removing manual custom errors and native validation. */
  resetValidity: () => void;
  /** Reference to the underlying HTML element */
  element: WaCheckbox | null;
}

export const Checkbox = forwardRef<CheckboxRef, CheckboxProps>(
  (
    {
      children,
      className,
      onChange,
      onBlur,
      onFocus,
      onInput,
      onInvalid,
      ...props
    },
    ref
  ) => {
    const checkboxRef = useRef<WaCheckbox | null>(null);
    const setCheckboxRef = useCallback((el: WaCheckbox | null) => {
      checkboxRef.current = el;
    }, []);

    useImperativeHandle(
      ref,
      () => ({
        click: () => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.click === 'function'
          ) {
            checkboxRef.current.click();
          }
        },
        focus: (options: FocusOptions) => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.focus === 'function'
          ) {
            checkboxRef.current.focus(options);
          }
        },
        blur: () => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.blur === 'function'
          ) {
            checkboxRef.current.blur();
          }
        },
        setCustomValidity: (message: string) => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.setCustomValidity === 'function'
          ) {
            checkboxRef.current.setCustomValidity(message);
          }
        },
        formStateRestoreCallback: (
          state: string | File | FormData | null,
          reason: 'autocomplete' | 'restore'
        ) => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.formStateRestoreCallback === 'function'
          ) {
            checkboxRef.current.formStateRestoreCallback(state, reason);
          }
        },
        resetValidity: () => {
          if (
            checkboxRef.current &&
            typeof checkboxRef.current.resetValidity === 'function'
          ) {
            checkboxRef.current.resetValidity();
          }
        },
        get element() {
          return checkboxRef.current;
        },
      }),
      []
    );

    useEffect(() => {
      ensureLoaded();
      const el = checkboxRef.current;
      if (!el) return;

      const handleChange = (e: Event) => {
        if (onChange) onChange(e as Event);
      };

      const handleBlur = (e: Event) => {
        if (onBlur) onBlur(e as FocusEvent);
      };

      const handleFocus = (e: Event) => {
        if (onFocus) onFocus(e as FocusEvent);
      };

      const handleInput = (e: Event) => {
        if (onInput) onInput(e as InputEvent);
      };

      const handleWaInvalid = (e: Event) => {
        if (onInvalid) onInvalid(e as WaInvalidEvent);
      };

      el.addEventListener('change', handleChange);
      el.addEventListener('blur', handleBlur);
      el.addEventListener('focus', handleFocus);
      el.addEventListener('input', handleInput);
      el.addEventListener('wa-invalid', handleWaInvalid);

      return () => {
        el.removeEventListener('change', handleChange);
        el.removeEventListener('blur', handleBlur);
        el.removeEventListener('focus', handleFocus);
        el.removeEventListener('input', handleInput);
        el.removeEventListener('wa-invalid', handleWaInvalid);
      };
    }, [onChange, onBlur, onFocus, onInput, onInvalid]);

    return (
      <wa-checkbox
        ref={setCheckboxRef}
        class={clsx('Checkbox', className)}
        {...({ suppressHydrationWarning: true, ...props } as Record<
          string,
          unknown
        >)}
      >
        {children}
      </wa-checkbox>
    );
  }
);

Checkbox.displayName = 'Checkbox';

// templates/angular/Checkbox/checkbox.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  inject,
  Input,
  Output,
  EventEmitter,
  OnDestroy,
  forwardRef,
} from '@angular/core';
import { NG_VALUE_ACCESSOR, type ControlValueAccessor } from '@angular/forms';
import type WaElement from '@awesome.me/webawesome/dist/components/checkbox/checkbox.js';
import type { WaInvalidEvent } from '@awesome.me/webawesome/dist/events/invalid.js';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/checkbox/checkbox.js'));
}

/**
 * Checkboxes allow the user to toggle an option on or off
 *
 * @see https://webawesome.com/docs/components/checkbox
 */
@Component({
  selector: 'k-checkbox',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <wa-checkbox
      #element
      [attr.checked]="checked || null"
      [attr.disabled]="disabled || null"
      [attr.hint]="hint"
      [attr.indeterminate]="indeterminate || null"
      [attr.name]="name"
      [attr.required]="required || null"
      [attr.size]="size"
      [attr.value]="value"
      [attr.title]="title"
      [attr.custom-error]="customError"
    >
      <ng-content />
    </wa-checkbox>
  `,
  styleUrl: './checkbox.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CheckboxComponent),
      multi: true,
    },
  ],
})
export class CheckboxComponent
  implements AfterViewInit, OnDestroy, ControlValueAccessor
{
  @ViewChild('element', { static: true }) elementRef!: ElementRef<WaElement>;
  private hostRef = inject(ElementRef<HTMLElement>);

  /** Draws checkbox in checked state */
  @Input() checked?: boolean;
  /** Disables the checkbox */
  @Input() disabled?: boolean;
  /** Descriptive helper text */
  @Input() hint?: string;
  /** Mixed/parent selection state */
  @Input() indeterminate?: boolean;
  /** Form submission identifier */
  @Input() name?: string;
  /** Makes field mandatory */
  @Input() required?: boolean;
  /** Adjusts checkbox dimensions */
  @Input() size?: 'small' | 'medium' | 'large' | 'xs' | 's' | 'm' | 'l' | 'xl';
  /** Form submission value */
  @Input() value?: string;
  /** Native tooltip text, shown on hover */
  @Input() title?: string;
  /** Custom validation message; the control is invalid while it is set */
  @Input() customError?: string;

  @Output() change = new EventEmitter<Event>();
  @Output() blurEvent = new EventEmitter<FocusEvent>();
  @Output() focusEvent = new EventEmitter<FocusEvent>();
  @Output() inputEvent = new EventEmitter<InputEvent>();
  @Output() invalid = new EventEmitter<WaInvalidEvent>();

  private onChangeCallback: (value: unknown) => void = () => {};
  private onTouchedCallback: () => void = () => {};

  private cleanups: (() => void)[] = [];

  ngAfterViewInit(): void {
    ensureLoaded();
    const el = this.elementRef.nativeElement;

    // Forward host attributes to inner wa-* element
    const host = this.hostRef.nativeElement;
    const hostStyle = host.getAttribute('style');
    if (hostStyle) {
      el.setAttribute('style', hostStyle);
      host.removeAttribute('style');
    }
    // When slotted, override display:contents so ::slotted() margins apply
    if (host.hasAttribute('slot')) {
      host.style.display = 'inline';
    }

    const handleChange = (e: Event) => this.change.emit(e as Event);
    el.addEventListener('change', handleChange);
    this.cleanups.push(() => el.removeEventListener('change', handleChange));
    const handleBlurEvent = (e: Event) => this.blurEvent.emit(e as FocusEvent);
    el.addEventListener('blur', handleBlurEvent);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurEvent));
    const handleFocusEvent = (e: Event) =>
      this.focusEvent.emit(e as FocusEvent);
    el.addEventListener('focus', handleFocusEvent);
    this.cleanups.push(() => el.removeEventListener('focus', handleFocusEvent));
    const handleInputEvent = (e: Event) =>
      this.inputEvent.emit(e as InputEvent);
    el.addEventListener('input', handleInputEvent);
    this.cleanups.push(() => el.removeEventListener('input', handleInputEvent));
    const handleInvalid = (e: Event) => this.invalid.emit(e as WaInvalidEvent);
    el.addEventListener('wa-invalid', handleInvalid);
    this.cleanups.push(() =>
      el.removeEventListener('wa-invalid', handleInvalid)
    );

    const handleCheckedChange = () =>
      this.onChangeCallback((el as unknown as { checked: boolean }).checked);
    el.addEventListener('change', handleCheckedChange);
    this.cleanups.push(() =>
      el.removeEventListener('change', handleCheckedChange)
    );
    const handleBlurTouch = () => this.onTouchedCallback();
    el.addEventListener('blur', handleBlurTouch);
    this.cleanups.push(() => el.removeEventListener('blur', handleBlurTouch));
  }

  ngOnDestroy(): void {
    this.cleanups.forEach((fn) => fn());
  }

  writeValue(value: unknown): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { checked: boolean }
      ).checked = !!value;
    }
  }

  registerOnChange(fn: (value: unknown) => void): void {
    this.onChangeCallback = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onTouchedCallback = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    if (this.elementRef?.nativeElement) {
      (
        this.elementRef.nativeElement as unknown as { disabled: boolean }
      ).disabled = isDisabled;
    }
  }

  click(): void {
    (this.elementRef.nativeElement as unknown as { click: () => void }).click();
  }
  focus(options?: FocusOptions): void {
    (
      this.elementRef.nativeElement as unknown as {
        focus: (options?: FocusOptions) => void;
      }
    ).focus(options);
  }
  blur(): void {
    (this.elementRef.nativeElement as unknown as { blur: () => void }).blur();
  }
  setCustomValidity(message?: string): void {
    (
      this.elementRef.nativeElement as unknown as {
        setCustomValidity: (message?: string) => void;
      }
    ).setCustomValidity(message);
  }
  formStateRestoreCallback(
    state?: string | File | FormData | null,
    reason?: 'autocomplete' | 'restore'
  ): void {
    (
      this.elementRef.nativeElement as unknown as {
        formStateRestoreCallback: (
          state?: string | File | FormData | null,
          reason?: 'autocomplete' | 'restore'
        ) => void;
      }
    ).formStateRestoreCallback(state, reason);
  }
  resetValidity(): void {
    (
      this.elementRef.nativeElement as unknown as { resetValidity: () => void }
    ).resetValidity();
  }
}
