// templates/vue/CarouselItem/CarouselItem.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import './CarouselItem.css';

let loadPromise: Promise<unknown> | null = null;
function ensureLoaded() {
  return (loadPromise ??= import('@awesome.me/webawesome/dist/components/carousel-item/carousel-item.js'));
}

/**
 * Represents an individual slide within a carousel component
 */
export interface CarouselItemProps {

}

const props = defineProps<CarouselItemProps>();

// Strip undefined props so Vue doesn't override web component defaults (e.g. wa-icon library)
const definedProps = computed(() => {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) result[key] = value;
  }
  return result;
});

const emit = defineEmits<{
  // No events for this component
}>();

const elementRef = ref<HTMLElement | null>(null);

onMounted(() => {
  ensureLoaded();
});

defineExpose({
  element: elementRef,
});
</script>

<template>
  <wa-carousel-item
    ref="elementRef"
    v-bind="definedProps"
    :class="$attrs.class"
  >
    <slot />
  </wa-carousel-item>
</template>

// templates/react/CarouselItem/CarouselItem.jsx
import React from 'react';
import clsx from 'clsx';
import './CarouselItem.css';

let loadPromise = null;
function ensureLoaded() {
  return (loadPromise ??=
    import('@awesome.me/webawesome/dist/components/carousel-item/carousel-item.js'));
}

/**
 * Represents an individual slide within a carousel component
 *
 * @example
 * ```jsx
 * <Carousel>
 *   <CarouselItem>
 *     <img src="slide1.jpg" alt="Slide 1" />
 *   </CarouselItem>
 * </Carousel>
 * ```
 */
export const CarouselItem = React.forwardRef(
  ({ children, className, ...props }, ref) => {
    React.useEffect(() => {
      ensureLoaded();
    }, []);

    return (
      <wa-carousel-item
        ref={ref}
        class={clsx('CarouselItem', className)}
        {...props}
      >
        {children}
      </wa-carousel-item>
    );
  }
);

CarouselItem.displayName = 'CarouselItem';
